In [417]:
import pandas as pd
import os
import json
import random
import numpy as np
import warnings

with warnings.catch_warnings():
    warnings.simplefilter("ignore")

In [419]:
cwd = os.getcwd()

train = pd.read_parquet(f'{cwd}\\Vulnerable-Verified-Smart-Contracts\\train.parquet')
test = pd.read_parquet(f'{cwd}\\Vulnerable-Verified-Smart-Contracts\\test.parquet')
validation = pd.read_parquet(f'{cwd}\\Vulnerable-Verified-Smart-Contracts\\validation.parquet')

In [420]:
print("train:", train.columns.tolist())

train: ['contract_name', 'file_path', 'contract_address', 'language', 'source_code', 'overlapping', 'soldetector', 'slither', 'oyente', 'smartcheck', 'compiler_version', 'license_type', 'swarm_source']

In [421]:
random_row = random.randint(0, len(train) - 1)  # Generates a number between 0 and (len(train) - 1) (inclusive)
print("Random row:", random_row)

source_code = train.iloc[random_row]['source_code']
overlapping = train.iloc[random_row]['overlapping']
slither = train.iloc[random_row]['slither']
print("\nsource code: \n" + source_code + "\n" + "\noverlapping: \n" + overlapping + "\nslither: \n" + slither)

Random row: 0

source code:
pragma solidity ^0.4.22;

contract Gift
{
    bool closed = false;
    uint unlockTime = 43200;
    address sender;
    address receiver;

    function Put(address _receiver) public payable {
        if ((!closed && msg.value > 0.5 ether) || sender == 0x0 ) {
            sender = msg.sender;
            receiver = _receiver;
            unlockTime += now;
        }
    }

    function SetTime(uint _unixTime) public {
        if (msg.sender == sender) {
            unlockTime = _unixTime;
        }
    }

    function Get() public payable {
        if (receiver == msg.sender && now >= unlockTime) {
            msg.sender.transfer(address(this).balance);
        }
    }

    function Close() public {
        if (sender == msg.sender) {
           closed=true;
        }
    }

    function() public payable { }
}

overlapping:
{"IOU": [[{"defect": "Integer_overflow_and_underflow", "lines": [14], "severity": "High", "tool": "soldetector", "type": "Code_specification"}, {"error": "Integer Overflow.", "level": "Warning", "line": 14, "tool": "oyente"}]], "TD": [[{"defect": "Dependency_of_timestamp", "lines": [25], "severity": "Medium", "tool": "soldetector", "type": "Business_logic"}, {"check": "timestamp", "confidence": "Medium", "impact": "Low", "lines": [25], "tool": "slither"}, {"error": "Timestamp Dependency.", "level": "Warning", "line": 25, "tool": "oyente"}]]}
slither:
[{"check": "external-function", "impact": "Optimization", "confidence": "High", "lines": [{"Gift.sol": [32, 33, 34, 30, 31]}]}, {"check": "external-function", "impact": "Optimization", "confidence": "High", "lines": [{"Gift.sol": [36]}]}, {"check": "external-function", "impact": "Optimization", "confidence": "High", "lines": [{"Gift.sol": [24, 25, 26, 27, 28]}]}, {"check": "external-function", "impact": "Optimization", "confidence": "High", "lines": [{"Gift.sol": [10, 11, 12, 13, 14, 15, 16]}]}, {"check": "external-function", "impact": "Optimization", "confidence": "High", "lines": [{"Gift.sol": [18, 19, 20, 21, 22]}]}, {"check": "solc-version", "impact": "Informational", "confidence": "High", "lines": [{"Gift.sol": [1]}]}, {"check": "events-maths", "impact": "Low", "confidence": "Medium", "lines": [{"Gift.sol": [20]}]}, {"check": "missing-zero-check", "impact": "Low", "confidence": "Medium", "lines": [{"Gift.sol": [13]}]}, {"check": "naming-convention", "impact": "Informational", "confidence": "High", "lines": [{"Gift.sol": [24, 25, 26, 27, 28]}]}, {"check": "naming-convention", "impact": "Informational", "confidence": "High", "lines": [{"Gift.sol": [18]}]}, {"check": "naming-convention", "impact": "Informational", "confidence": "High", "lines": [{"Gift.sol": [32, 33, 34, 30, 31]}]}, {"check": "naming-convention", "impact": "Informational", "confidence": "High", "lines": [{"Gift.sol": [18, 19, 20, 21, 22]}]}, {"check": "naming-convention", "impact": "Informational", "confidence": "High", "lines": [{"Gift.sol": [10]}]}, {"check": "naming-convention", "impact": "Informational", "confidence": "High", "lines": [{"Gift.sol": [10, 11, 12, 13, 14, 15, 16]}]}, {"check": "timestamp", "impact": "Low", "confidence": "Medium", "lines": [{"Gift.sol": [25]}]}]

In [425]:
overlapping = train.iloc[random_row]['overlapping']

# Parse JSON string to Python dictionary
data = json.loads(overlapping)

# Output the dictionary
print(data)
print(type(data))  # <class 'dict'>
print(data.keys())

{'IOU': [[{'defect': 'Integer_overflow_and_underflow', 'lines': [14], 'severity': 'High', 'tool': 'soldetector', 'type': 'Code_specification'}, {'error': 'Integer Overflow.', 'level': 'Warning', 'line': 14, 'tool': 'oyente'}]], 'TD': [[{'defect': 'Dependency_of_timestamp', 'lines': [25], 'severity': 'Medium', 'tool': 'soldetector', 'type': 'Business_logic'}, {'check': 'timestamp', 'confidence': 'Medium', 'impact': 'Low', 'lines': [25], 'tool': 'slither'}, {'error': 'Timestamp Dependency.', 'level': 'Warning', 'line': 25, 'tool': 'oyente'}]]}
<class 'dict'>
dict_keys(['IOU', 'TD'])

In [426]:
def check_vuln_types(dataset):
    count = 0
    vulnerability_keys = set()
    
    for index, row in dataset.iterrows():
        overlapping = row['overlapping']
    
        # Parse JSON string to Python dictionary
        data = json.loads(overlapping)
    
        vuln = data.keys()
        for key in vuln:
            vulnerability_keys.add(key)
        count += len(vuln)
    return str(vulnerability_keys) + ", " + str(len(vulnerability_keys)) + " keys, total vulnerabilities: " + str(count)

print("train", check_vuln_types(train))
print("test", check_vuln_types(test))
print("valid", check_vuln_types(validation))

train {'FE', 'TOD', 'TO', 'UcC', 'IOU', 'RE', 'UpS', 'TD', 'NC', 'DC'}, 10 keys, total vulnerabilities: 710
test {'TOD', 'UcC', 'IOU', 'RE', 'UpS', 'TD', 'NC', 'DC'}, 8 keys, total vulnerabilities: 46
valid {'TO', 'TOD', 'UcC', 'IOU', 'RE', 'UpS', 'TD', 'NC', 'DC'}, 9 keys, total vulnerabilities: 66

In [123]:
def add_new_columns(dataset):
    vulns = ['IOU', 'TOD', 'RE', 'UcC', 'UpS', 'TD', 'TO', 'DC', 'NC', 'FE']
    tools = ['soldetector', 'slither', 'oyente', 'smartcheck']

    # Initialize new columns
    for vuln in vulns:
        dataset[f'{vuln}'] = "Undetected"
        for tool in tools:
            dataset[f'{vuln}_{tool}'] = "Undetected"
            
    for index, row in dataset.iterrows():
        overlapping = row['overlapping']
    
        # Parse JSON string to Python dictionary
        data = json.loads(overlapping)
    
        vulns = data.keys()
        for vuln in vulns:
            info_dict_list = data[vuln][0]
            dataset.at[index, f'{vuln}'] = "Detected"
            for info_dict in info_dict_list:
                # print(info_dict)
                try:
                    lines = str(info_dict['lines'])
                except KeyError as e:
                    lines = "[" + str(info_dict['line']) + "]"
                tool = info_dict['tool']
                dataset.at[index, f'{vuln}_{tool}'] = lines
add_new_columns(test)

In [125]:
test.columns

Index(['contract_name', 'file_path', 'contract_address', 'language',
       'source_code', 'overlapping', 'soldetector', 'slither', 'oyente',
       'smartcheck', 'compiler_version', 'license_type', 'swarm_source', 'IOU',
       'IOU_soldetector', 'IOU_slither', 'IOU_oyente', 'IOU_smartcheck', 'TOD',
       'TOD_soldetector', 'TOD_slither', 'TOD_oyente', 'TOD_smartcheck', 'RE',
       'RE_soldetector', 'RE_slither', 'RE_oyente', 'RE_smartcheck', 'UcC',
       'UcC_soldetector', 'UcC_slither', 'UcC_oyente', 'UcC_smartcheck', 'UpS',
       'UpS_soldetector', 'UpS_slither', 'UpS_oyente', 'UpS_smartcheck', 'TD',
       'TD_soldetector', 'TD_slither', 'TD_oyente', 'TD_smartcheck', 'TO',
       'TO_soldetector', 'TO_slither', 'TO_oyente', 'TO_smartcheck', 'DC',
       'DC_soldetector', 'DC_slither', 'DC_oyente', 'DC_smartcheck', 'NC',
       'NC_soldetector', 'NC_slither', 'NC_oyente', 'NC_smartcheck', 'FE',
       'FE_soldetector', 'FE_slither', 'FE_oyente', 'FE_smartcheck'],
      dtype='object')

In [127]:
test

,contract_name,file_path,contract_address,language,source_code,overlapping,soldetector,slither,oyente,smartcheck,...,NC,NC_soldetector,NC_slither,NC_oyente,NC_smartcheck,FE,FE_soldetector,FE_slither,FE_oyente,FE_smartcheck
0,CrystalReignShard,CrystalReignShard.sol,0x5108e432d40d34a4d0ed88c12e83db0e571bfc75,Solidity,pragma solidity ^0.4.4;\r\n\r\n\r\n/**\r\n* @t...,"{""IOU"": [[{""defect"": ""Integer_overflow_and_und...","[{""defect"": ""Leaking_to_arbitary_address"", ""ty...","[{""check"": ""constable-states"", ""impact"": ""Opti...","[{""error"": ""Integer Underflow."", ""line"": 147, ...","[{""rule"": ""SOLIDITY_ADDRESS_HARDCODED"", ""line""...",...,Detected,[220],[221],Undetected,[220],Undetected,Undetected,Undetected,Undetected,Undetected
1,WrapperLockEth,WrapperLockEth.sol,0x9fb2fd4bce3061b826bf1a0b53b737c6f3e0e586,Solidity,pragma solidity ^0.4.22;\r\n\r\n\r\n\r\n/**\r\...,"{""TD"": [[{""defect"": ""Dependency_of_timestamp"",...","[{""defect"": ""Erroneous_constructor_name"", ""typ...","[{""check"": ""constable-states"", ""impact"": ""Opti...","[{""error"": ""Integer Overflow."", ""line"": 114, ""...","[{""rule"": ""SOLIDITY_ADDRESS_HARDCODED"", ""line""...",...,Undetected,Undetected,Undetected,Undetected,Undetected,Undetected,Undetected,Undetected,Undetected,Undetected
2,GetsBurned,GetsBurned.sol,0x5f15d2d4c60e229586a5bdfe2eec1981f92845c1,Solidity,pragma solidity ^0.4.25; \r\n\r\ncontract Get...,"{""UpS"": [[{""defect"": ""Unprotected_Suicide"", ""l...","[{""defect"": ""Unprotected_Suicide"", ""type"": ""Fu...","[{""check"": ""external-function"", ""impact"": ""Opt...",[],"[{""rule"": ""SOLIDITY_PRAGMAS_VERSION"", ""line"": ...",...,Undetected,Undetected,Undetected,Undetected,Undetected,Undetected,Undetected,Undetected,Undetected,Undetected
3,guess_tw,guess_tw.sol,0xa9aebbf67433e3e8206af6fc2ddd99ff8e7cc137,Solidity,pragma solidity ^0.4.20;\r\n\r\ncontract guess...,"{""TOD"": [[{""defect"": ""Transaction_order_depend...","[{""defect"": ""Transaction_order_dependency"", ""t...","[{""check"": ""external-function"", ""impact"": ""Opt...","[{""error"": ""Integer Underflow."", ""line"": 11, ""...","[{""rule"": ""SOLIDITY_PRAGMAS_VERSION"", ""line"": ...",...,Undetected,Undetected,Undetected,Undetected,Undetected,Undetected,Undetected,Undetected,Undetected,Undetected
4,WithdrawContract,WithdrawContract.sol,0x0efef0b34638addc8833ba729ae20016b5f24ffc,Solidity,//File: node_modules/giveth-common-contracts/c...,"{""IOU"": [[{""defect"": ""Integer_overflow_and_und...","[{""defect"": ""Leaking_to_arbitary_address"", ""ty...","[{""check"": ""arbitrary-send"", ""impact"": ""High"",...","[{""error"": ""Transaction-Ordering Dependency."",...","[{""rule"": ""SOLIDITY_ADDRESS_HARDCODED"", ""line""...",...,Undetected,Undetected,Undetected,Undetected,Undetected,Undetected,Undetected,Undetected,Undetected,Undetected
5,we_play,we_play.sol,0x6df766e4b524aa1d4b4b9405994ca69dc161da3f,Solidity,pragma solidity ^0.4.25;\r\n\r\ncontract we_pl...,"{""TOD"": [[{""defect"": ""Transaction_order_depend...","[{""defect"": ""Transaction_order_dependency"", ""t...","[{""check"": ""external-function"", ""impact"": ""Opt...","[{""error"": ""Integer Underflow."", ""line"": 8, ""l...","[{""rule"": ""SOLIDITY_ADDRESS_HARDCODED"", ""line""...",...,Undetected,Undetected,Undetected,Undetected,Undetected,Undetected,Undetected,Undetected,Undetected,Undetected
6,EthCapsule,EthCapsule.sol,0x5274a2293dbe075a82d41e873bb927403a9dce46,Solidity,pragma solidity ^0.4.11;\r\n\r\ncontract Ownab...,"{""IOU"": [[{""defect"": ""Integer_overflow_and_und...","[{""defect"": ""Leaking_to_arbitary_address"", ""ty...","[{""check"": ""external-function"", ""impact"": ""Opt...","[{""error"": ""Integer Overflow."", ""line"": 107, ""...","[{""rule"": ""SOLIDITY_DEPRECATED_CONSTRUCTIONS"",...",...,Undetected,Undetected,Undetected,Undetected,Undetected,Undetected,Undetected,Undetected,Undetected,Undetected
7,PonziToken,PonziToken.sol,0x33f00114d5aca3dee03189d4ed9d4f886dad84b0,Solidity,pragma solidity ^0.4.18;\r\n\r\n// If you wann...,"{""UpS"": [[{""defect"": ""Unprotected_Suicide"", ""l...","[{""defect"": ""Leaking_to_arbitary_address"", ""ty...","[{""check"": ""divide-before-multiply"", ""impact"":...","[{""error"": ""Integer Underflow."", ""line"": 238, ...","[{""rule"": ""SOLIDITY_ADDRESS_HARDCODED"", ""line""...",...,Undetected,Undetected,Undetected,Undetected,Undetected,Undetected,Undetected,Undetected,Undetected,Undetected
8,USTputOption,USTputOption.sol,0x07227ab560609efc6d45d953ee333a76f329a74b,Solidity,pragma solidity ^0.4.21;\r\n\r\ncontract Owned...,"{""IOU"": [[{""defect"": ""Integer_overflow_and_und...","[{""defect"": ""Leaking_to_arbitary_address"", ""ty...","[{""check"": ""boolean-equal"", ""impact"": ""Informa...","[{""error"": ""Integer Underflow."", ""line"": 108, ...","[{""rule"": ""SOLIDITY_ADDRESS_HARDCODED"", ""line""...",...,Undetected,Undetected,Undetected,Undetected,Undetected,Undetected,Undetected,Undetected,Undetected,Undetected
9,MultiEthSender,MultiEthSender.sol,0x11352d75f63804d5f8fdb88bddf9efe9b52d6723,Solidity,pragma solidity ^0.4.24;\r\n\r\n/**\r\n * @tit...,"{""NC"": [[{""defect"": ""Nest_Call"", ""lines"": [79]...","[{""defect"": ""Nest_Call"", ""type"": ""Business_log...","[{""check"": ""arbitrary-send"", ""impact"": ""High"",...","[{""error"": ""Integer Overflow."", ""line"": 74, ""l...","[{""rule"": ""SOLIDITY_EXTRA_GAS_IN_LOOPS"", ""line...",...,Detected,[79],[80],Undetected,[79],Undetected,Undetected,Undetected,Undetected,Undetected
10,CryptoRomeLandComposableNFT,CryptoRomeLandComposableNFT.sol,0x86e4dc25259ee2191cd8ae40e1865b9f0319646c,Solidity,pragma solidity ^0.4.24;\r\n\r\n/**\r\n * @sum...,"{""IOU"": [[{""defect"": ""Integer_overflow_and_und...","[{""defect"": ""Leaking_to_arbitary_address"", ""ty...","[{""check"": ""controlled-array-length"", ""impact""...","[{""error"": ""Transaction-Ordering Dependency."",...","[{""rule"": ""SOLIDITY_ADDRESS_HARDCODED"", ""line""...",...,Undetected,Undetected,Undetected,Undetected,Undetected,Undetected,Undetected,Undetected,Undetected,Undetected
11,DTT_Exchange,DTT_Exchange.sol,0x7abe2a84368af480ffd4beb7676133c30f37dc05,Solidity,pragma solidity ^0.4.26;\r\n\r\ncontract DTT_E...,"{""IOU"": [[{""defect"": ""Integer_overflow_and_und...","[{""defect"": ""Leaking_to_arbitary_address"", ""ty...","[{""check"": ""boolean-equal"", ""impact"": ""Informa...","[{""error"": ""Integer Underflow."", ""line"": 36, ""...","[{""rule"": ""SOLIDITY_ADDRESS_HARDCODED"", ""line""...",...,Undetected,Undetected,Undetected,Undetected,Undetected,Undetected,Undetected,Undetected,Undetected,Undetected
12,CNCICO,CNCICO.sol,0x720e794b39f31f0c2746f688c655c7a637f04db4,Solidity,pragma solidity 0.4.24;\r\n/**\r\n* @title CNC...,"{""TD"": [[{""defect"": ""Dependency_of_timestamp"",...","[{""defect"": ""Leaking_to_arbitary_address"", ""ty...","[{""check"": ""arbitrary-send"", ""impact"": ""High"",...","[{""error"": ""Integer Underflow."", ""line"": 134, ...","[{""rule"": ""SOLIDITY_ADDRESS_HARDCODED"", ""line""...",...,Undetected,Undetected,Undetected,Undetected,Undetected,Undetected,Undetected,Undetected,Undetected,Undetected
13,qui_qz,qui_qz.sol,0x3fab284a3cd0a6d88d18d0fda4bc1a76cdacd68a,Solidity,pragma solidity ^0.4.20;\r\n\r\ncontract qui_q...,"{""TOD"": [[{""defect"": ""Transaction_order_depend...","[{""defect"": ""Transaction_order_dependency"", ""t...","[{""check"": ""external-function"", ""impact"": ""Opt...","[{""error"": ""Integer Underflow."", ""line"": 11, ""...","[{""rule"": ""SOLIDITY_PRAGMAS_VERSION"", ""line"": ...",...,Undetected,Undetected,Undetected,Undetected,Undetected,Undetected,Undetected,Undetected,Undetected,Undetected
14,ObirumCrowdsale,ObirumCrowdsale.sol,0x0532dd9ecb00c424c72335df4f60c11c03229ec0,Solidity,pragma solidity ^0.4.18;\r\n\r\n/**\r\n * @tit...,"{""TD"": [[{""defect"": ""Dependency_of_timestamp"",...","[{""defect"": ""Leaking_to_arbitary_address"", ""ty...","[{""check"": ""arbitrary-send"", ""impact"": ""High"",...","[{""error"": ""Integer Overflow."", ""line"": 30, ""l...","[{""rule"": ""SOLIDITY_DEPRECATED_CONSTRUCTIONS"",...",...,Undetected,Undetected,Undetected,Undetected,Undetected,Undetected,Undetected,Undetected,Undetected,Undetected
15,eTrustmoney,eTrustmoney.sol,0xa5c62860475ce15c5e38a8443ca53f72113c0a5c,Solidity,pragma solidity 0.4.24;\r\n\r\n\r\n\r\n/**\r\n...,"{""NC"": [[{""defect"": ""Nest_Call"", ""lines"": [57]...","[{""defect"": ""Nest_Call"", ""type"": ""Business_log...","[{""check"": ""arbitrary-send"", ""impact"": ""High"",...","[{""error"": ""Integer Overflow."", ""line"": 54, ""l...","[{""rule"": ""SOLIDITY_EXTRA_GAS_IN_LOOPS"", ""line...",...,Detected,[57],[60],Undetected,[57],Undetected,Undetected,Undetected,Undetected,Undetected
16,Pair,Pair.sol,0x0b3ded1b54e89f8899482cfccf515d525835bc2b,Solidity,// SPDX-License-Identifier: UNLICENSED\n\nprag...,"{""DC"": [[{""defect"": ""DelegateCall"", ""lines"": [...","[{""defect"": ""Leaking_to_arbitary_address"", ""ty...","[{""check"": ""assembly"", ""impact"": ""Informationa...",[],"[{""rule"": ""SOLIDITY_ADDRESS_HARDCODED"", ""line""...",...,Undetected,Undetected,Undetected,Undetected,Undetected,Undetected,Undetected,Undetected,Undetected,Undetected
17,DEP_BANK,DEP_BANK.sol,0xaae1f51cf3339f18b6d3f3bdc75a5facd744b0b8,Solidity,pragma solidity ^0.4.19;\r\n\r\ncontract DEP_B...,"{""RE"": [[{""defect"": ""Reentrancy"", ""lines"": [47...","[{""defect"": ""Erroneous_constructor_name"", ""typ...","[{""check"": ""controlled-array-length"", ""impact""...","[{""error"": ""Re-Entrancy Vulnerability."", ""line...","[{""rule"": ""SOLIDITY_CALL_WITHOUT_DATA"", ""line""...",...,Undetected,Undetected,Undetected,Undetected,Undetected,Undetected,Undetected,Undetected,Undetected,Undetected
18,MultiTransfer,MultiTransfer.sol,0xc7e3632f9977a73eefa8ca2ab3d8218182eccb24,Solidity,pragma solidity ^0.4.25;\r\ncontract MultiTran...,"{""UcC"": [[{""defect"": ""Unchecked_send"", ""lines""...","[{""defect"": ""Nest_Call"", ""type"": ""Business_log...","[{""check"": ""arbitrary-send"", ""impact"": ""High"",...","[{""error"": ""Integer Overflow."", ""line"": 14, ""l...","[{""rule"": ""SOLIDITY_CALL_WITHOUT_DATA"", ""line""...",...,Undetected,Undetected,Undetected,Undetected,Undetected,Undetected,Undetected,Undetected,Undetected,Undetected
19,FutureDeposit,FutureDeposit.sol,0xbddd99e8aaeb85847703c31a83277856d49961d9,Solidity,pragma solidity ^0.4.11;\r\n\r\ncontract Futur...,"{""UpS"": [[{""defect"": ""Unprotected_Suicide"", ""l...","[{""defect"": ""Unprotected_Suicide"", ""type"": ""Fu...","[{""check"": ""external-function"", ""impact"": ""Opt...","[{""error"": ""Integer Overflow."", ""line"": 39, ""l...","[{""rule"": ""SOLIDITY_BALANCE_EQUALITY"", ""line"":...",...,Undetected,Undetected,Undetected,Undetected,Undetected,Undetected,Undetected,Undetected,Undetected,Undetected
20,PiggyBank,PiggyBank.sol,0x7a0ec191d8f44f3bc3cbb4d1105ced31c30ff492,Solidity,pragma solidity ^0.4.24;\r\n\r\ncontract Piggy...,"{""UpS"": [[{""defect"": ""Unprotected_Suicide"", ""l...","[{""defect"": ""Unprotected_Suicide"", ""type"": ""Fu...","[{""check"": ""constable-states"", ""impact"": ""Opti...","[{""error"": ""Integer Underflow."", ""line"": 4, ""l...","[{""rule"": ""SOLIDITY_DIV_MUL"", ""line"": 39, ""sev...",...,Undetected,Undetected,Undetected,Undetected,Undetected,Undetected,Undetected,Undetected,Undetected,Undetected
21,CCCP,CCCP.sol,0xa60e456630a802bfb801a2a4202a820d74d687d2,Solidity,pragma solidity ^0.4.11;\r\n\r\nlibrary SafeMa...,"{""TOD"": [[{""defect"": ""Transaction_order_depend...","[{""defect"": ""Leaking_to_arbitary_address"", ""ty...","[{""check"": ""controlled-array-length"", ""impact""...","[{""error"": ""Integer Overflow."", ""line"": 106, ""...","[{""rule"": ""SOLIDITY_DEPRECATED_CONSTRUCTIONS"",...",...,Undetected,Undetected,Undetected,Undetected,Undetected,Undetected,Undetected,Undetected,Undetected,Undetected
22,QUESTQUESTION,QUESTQUESTION.sol,0xc77081641129a028d622f85671ea172ac5595938,Solidity,pragma solidity ^0.4.20;\r\n\r\ncontract QUEST...,"{""TOD"": [[{""defect"": ""Transaction_order_depend...","[{""defect"": ""Transaction_order_dependency"", ""t...","[{""check"": ""external-function"", ""impact"": ""Opt...","[{""error"": ""Integer Underflow."", ""line"": 16, ""...","[{""rule"": ""SOLIDITY_PRAGMAS_VERSION"", ""line"": ...",...,Undetected,Undetected,Undetected,Undetected,Undetected,Undetected,Undetected,Undetected,Undetected,Undetected
23,Multiplexer,Multiplexer.sol,0x7b138cc83ecccd6331cd7651c75ee3eb2ec6682e,Solidity,pragma solidity ^0.4.15;\r\ncontract Ownable {...,"{""NC"": [[{""defect"": ""Nest_Call"", ""lines"": [34]...","[{""defect"": ""Leaking_to_arbitary_address"", ""ty...","[{""check"": ""arbitrary-send"", ""impact"": ""High"",...","[{""error"": ""Integer Overflow."", ""line"": 39, ""l...","[{""rule"": ""SOLIDITY_EXTRA_GAS_IN_LOOPS"", ""line...",...,Detected,[34],[35],Undetected,[34],Undetected,Undetected,Undetected,Undetected,Undetected
24,TokenTycoonIGO,TokenTycoonIGO.sol,0xfb673f08fc82807b4d0e139e794e3b328d63551f,Solidity,pragma solidity ^0.4.20;\r\n\r\ncontract Acces...,"{""IOU"": [[{""defect"": ""Integer_overflow_and_und...","[{""defect"": ""Unused_state_variable"", ""type"": ""...","[{""check"": ""constable-states"", ""impact"": ""Opti...","[{""error"": ""Transaction-Ordering Dependency."",...","[{""rule"": ""SOLIDITY_ERC20_APPROVE"", ""line"": 12...",...,Undetected,Undetected,Undetected,Undetected,Undetected,Undetected,Undetected,Undetected,Undetected,Undetected
25,just_try,just_try.sol,0xa72baa9e9097e5913cf7d136c5ee3f06c6170ae7,Solidity,pragma solidity ^0.4.25;\r\n\r\ncontract just_...,"{""TOD"": [[{""defect"": ""Transaction_order_depend...","[{""defect"": ""Transaction_order_dependency"", ""t...","[{""check"": ""external-function"", ""impact"": ""Opt...","[{""error"": ""Integer Underflow."", ""line"": 9, ""l...","[{""rule"": ""SOLIDITY_ADDRESS_HARDCODED"", ""line""...",...,Undetected,Undetected,Undetected,Undetected,Undetected,Undetected,Undetected,Undetected,Undetected,Undetected
26,BetCenter,BetCenter.sol,0x35bab7165a301e99c75c3e59b48817856b4d5e5c,Solidity,pragma solidity ^0.4.18;\r\n\r\n// zeppelin-so...,"{""NC"": [[{""defect"": ""Nest_Call"", ""lines"": [485...","[{""defect"": ""Nest_Call"", ""type"": ""Business_log...","[{""check"": ""arbitrary-send"", ""impact"": ""High"",...","[{""error"": ""Integer Underflow."", ""line"": 17, ""...","[{""rule"": ""SOLIDITY_ADDRESS_HARDCODED"", ""line""...",...,Detected,[485],[486],Undetected,[485],Undetected,Undetected,Undetected,Undetected,Undetected
27,MonedaICO,MonedaICO.sol,0x5ddf3e8cfaa2b1cc1f49a57f78b6c4a982757849,Solidity,pragma solidity 0.4.21;\r\n\r\n/**\r\n * @titl...,"{""TD"": [[{""defect"": ""Dependency_of_timestamp"",...","[{""defect"": ""Leaking_to_arbitary_address"", ""ty...","[{""check"": ""dead-code"", ""impact"": ""Information...","[{""error"": ""Timestamp Dependency."", ""line"": 15...","[{""rule"": ""SOLIDITY_SAFEMATH"", ""line"": 46, ""se...",...,Undetected,Undetected,Undetected,Undetected,Undetected,Undetected,Undetected,Undetected,Undetected,Undetected
28,Crowdsale,Crowdsale.sol,0xca4e51d78c1c41032b44923bbfa1bd99bcc194cc,Solidity,pragma solidity ^0.4.23;\r\n\r\n/**\r\n * @tit...,"{""TD"": [[{""defect"": ""Dependency_of_timestamp"",...","[{""defect"": ""Leaking_to_arbitary_address"", ""ty...","[{""check"": ""divide-before-multiply"", ""impact"":...","[{""error"": ""Integer Overflow."", ""line"": 43, ""l...","[{""rule"": ""SOLIDITY_ADDRESS_HARDCODED"", ""line""...",...,Undetected,Undetected,Undetected,Undetected,Undetected,Undetected,Undetected,Undetected,Undetected,Undetected
29,TRU_GAME,TRU_GAME.sol,0xa2016c28291a9a460095ada5c52c88cd3fd9a656,Solidity,pragma solidity ^0.4.25;\r\n\r\ncontract TRU_G...,"{""TOD"": [[{""defect"": ""Transaction_order_depend...","[{""defect"": ""Transaction_order_dependency"", ""t...","[{""check"": ""external-function"", ""impact"": ""Opt...","[{""error"": ""Integer Underflow."", ""line"": 14, ""...","[{""rule"": ""SOLIDITY_ADDRESS_HARDCODED"", ""line""...",...,Undetected,Undetected,Undetected,Undetected,Undetected,Undetected,Undetected,Undetected,Undetected,Undetected
30,BEthy,BEthy.sol,0x248fda6a145642bd9bba9d5d349164e8ffe933cc,Solidity,pragma solidity ^0.4.24;\r\n\r\ncontract Excha...,"{""IOU"": [[{""defect"": ""Integer_overflow_and_und...","[{""defect"": ""Leaking_to_arbitary_address"", ""ty...","[{""check"": ""controlled-array-length"", ""impact""...","[{""error"": ""Integer Overflow."", ""line"": 190, ""...","[{""rule"": ""SOLIDITY_ADDRESS_HARDCODED"", ""line""...",...,Detected,[144],[147],Undetected,[144],Undetected,Undetected,Undetected,Undetected,Undetected
31,GUESS_THE_WORD,GUESS_THE_WORD.sol,0xbb51397fb8d3b91a08eff3c34d5c869c1d149ec5,Solidity,pragma solidity ^0.4.20;\r\n\r\ncontract GUESS...,"{""TOD"": [[{""defect"": ""Transaction_order_depend...","[{""defect"": ""Transaction_order_dependency"", ""t...","[{""check"": ""external-function"", ""impact"": ""Opt...","[{""error"": ""Integer Underflow."", ""line"": 5, ""l...","[{""rule"": ""SOLIDITY_PRAGMAS_VERSION"", ""line"": ...",...,Undetected,Undetected,Undetected,Undetected,Undetected,Undetected,Undetected,Undetected,Undetected,Undetected
32,ChampionSimple,ChampionSimple.sol,0xbd8dd6d726c3fcdbfa9a1279a98a7320cfe4d800,Solidity,pragma solidity ^0.4.18;\r\n\r\n// zeppelin-so...,"{""NC"": [[{""defect"": ""Nest_Call"", ""lines"": [244...","[{""defect"": ""Leaking_to_arbitary_address"", ""ty...","[{""check"": ""dead-code"", ""impact"": ""Information...","[{""error"": ""Integer Overflow."", ""line"": 164, ""...","[{""rule"": ""SOLIDITY_EXTRA_GAS_IN_LOOPS"", ""line...",...,Detected,[244],[245],Undetected,[244],Undetected,Undetected,Undetected,Undetected,Undetected
33,THE_BANK,THE_BANK.sol,0xcb6fe98097fe7d6e00415bb6623d5fc3effa4e83,Solidity,pragma solidity ^0.4.25;\r\n\r\ncontract THE_B...,"{""RE"": [[{""defect"": ""Reentrancy"", ""lines"": [22...","[{""defect"": ""Unused_state_variable"", ""type"": ""...","[{""check"": ""controlled-array-length"", ""impact""...","[{""error"": ""Integer Underflow."", ""line"": 65, ""...","[{""rule"": ""SOLIDITY_CALL_WITHOUT_DATA"", ""line""...",...,Undetected,Undetected,Undetected,Undetected,Undetected,Undetected,Undetected,Undetected,Undetected,Undetected
34,Q_GAME,Q_GAME.sol,0x5838f878000fe44b6f6c677bbf839e12f097c147,Solidity,pragma solidity ^0.4.20;\r\n\r\ncontract Q_GAM...,"{""TOD"": [[{""defect"": ""Transaction_order_depend...","[{""defect"": ""Transaction_order_dependency"", ""t...","[{""check"": ""external-function"", ""impact"": ""Opt...","[{""error"": ""Integer Underflow."", ""line"": 8, ""l...","[{""rule"": ""SOLIDITY_PRAGMAS_VERSION"", ""line"": ...",...,Undetected,Undetected,Undetected,Undetected,Undetected,Undetected,Undetected,Undetected,Undetected,Undetected

In [129]:
# Now we need to check entries that have unequal line numbers marked as vulnerable by different tools
# First let's check for Reentrancy vulnerability
def check_for_improper_detections(dataset):
    vulns = ['IOU', 'TOD', 'RE', 'UcC', 'UpS', 'TD', 'TO', 'DC', 'NC', 'FE']
    tools = ['soldetector', 'slither', 'oyente', 'smartcheck']
    result = dict()
    
    for vuln in vulns:
        vuln_df = dataset[dataset[vuln] == "Detected"]

        if len(vuln_df) > 0:
            print("Vulnerability: ", vuln, "Number of samples: ", len(vuln_df))
            df = pd.DataFrame(columns=["file_path", "contract_address", "soldetector", "slither", "oyente", "smartcheck", "need_intervention"])
            # Set all columns except 'need_intervention' to 'object' type
            df[df.columns.difference(['need_intervention'])] = df[df.columns.difference(['need_intervention'])].astype('object')
            
            row_index = 0
            for index, row in vuln_df.iterrows():
                df.loc[row_index] = [row['file_path'], row['contract_address'], None, None, None, None, False]
                vul_lines_set_for_all_tool = []
                need_intervention = False
                for tool in tools:
                    vul_lines_set_for_tool = set()
                    if row[f'{vuln}_{tool}'] != "Undetected":
                        line_list = eval(row[f'{vuln}_{tool}'])
                        vul_lines_set_for_tool.update(line_list)
                        vul_lines_set_for_all_tool.append(vul_lines_set_for_tool)
                        if len(vul_lines_set_for_tool) > 0:
                            df.loc[row_index, tool] = str(vul_lines_set_for_tool)
                for i in range(len(vul_lines_set_for_all_tool)):
                    for j in range(len(vul_lines_set_for_all_tool)):
                        if i == j:
                            continue
                        if vul_lines_set_for_all_tool[i] != vul_lines_set_for_all_tool[j]:
                            need_intervention = True
                df.loc[row_index, "need_intervention"] = need_intervention
                row_index += 1
            result[vuln] = df
    return result

result_dict = check_for_improper_detections(test)

Vulnerability:  IOU Number of samples:  11
Vulnerability:  TOD Number of samples:  12
Vulnerability:  RE Number of samples:  2
Vulnerability:  UcC Number of samples:  1
Vulnerability:  UpS Number of samples:  4
Vulnerability:  TD Number of samples:  8
Vulnerability:  DC Number of samples:  1
Vulnerability:  NC Number of samples:  7

In [131]:
def count_need_intervention(result_dict):
    print("Vulberability types: ", list(result_dict.keys()))
    print("Number of vulnerability types: ", len(result_dict.keys()))
    count_dict = dict()
    count_sum = 0
    for key in result_dict.keys():
        df = result_dict[key]
        true_count = (df['need_intervention'] == True).sum()
        count_sum += true_count
        count_dict[key] = true_count
    return count_sum, count_dict

count, count_dict = count_need_intervention(result_dict)
print("Number of contracts needing intervention: ", count)
print("Number of contracts needing intervention by vuln. type: ", count_dict)
display(result_dict['DC'])

Vulberability types:  ['IOU', 'TOD', 'RE', 'UcC', 'UpS', 'TD', 'DC', 'NC']
Number of vulnerability types:  8
Number of contracts needing intervention:  16
Number of contracts needing intervention by vuln. type:  {'IOU': 2, 'TOD': 0, 'RE': 2, 'UcC': 0, 'UpS': 3, 'TD': 1, 'DC': 1, 'NC': 7}

,file_path,contract_address,soldetector,slither,oyente,smartcheck,need_intervention
0,Pair.sol,0x0b3ded1b54e89f8899482cfccf515d525835bc2b,{472},"{472, 473}",None,None,True

# Finding the smart contracts that need intervention across all the datasets(train, validation, test)

## Vulnerabilities

- **DC (DelegateCall)** : The address.delegatecall() function allows a smart contract to dynamically load external contracts from address at runtime. If the attacker can control the external contract and affect the current contract status, the contract is vulnerable to DC.
- **IOU (Arithmetic/Integer Overflow and Underflow)**: An arithmetic overflow or underflow, often called Integer Overflow or Underflow (IOU), occurs when an arithmetic operation attempts to create a numeric variable value that is larger than the maximum value or smaller than the minimum value of the variable type. If the arithmetic operation may pass a variable type’s maximum or minimum value and  is performed without using SafeMath, the contract is vulnerable to IOU.
- **NC (Nested Call)**: The function containing the loop has a high risk of exceeding its gas limitation and causing an out-of-gas error. If the attacker can control the loop iteration and causes the out-of-gas error, the contract is vulnerable to NC.
- **RE (Reentrancy)**: The contract vulnerable to RE uses the call() function to transfer ether to an external contract. The external contract can reenter the vulnerable contract by fallback function. If the state variable change is after the call() function, the reentrance will cause status inconsistency
- **TD (Timestamp Dependency)**: The contract uses the timestamp as the deciding factor for critical operations, e.g., sending ether. If the attacker can get ether from the contract by manipulating the timestamp or affecting the critical operations, the contract is vulnerable to TD
- **TO (TxOrigin)**: If the contract only uses tx.origin to verify the caller's identification for critical operations, it is vulnerable to TO
- **TOD (Transaction Order Dependency)**: The contract may send out ether differently according to different values of a global state variable or different balance values of the contract. If the attackers can get ether from the contract by manipulating the transaction sequences, the contract is vulnerable to TOD.
- **UcC (Unchecked Call)**: The contract uses the function call() or send() without result checking. If the send() or call()  function fails and leads to status inconsistency, the contract is vulnerable to UcC.
- **UpS(Unprotected Suicide)**: If an attacker can self-destruct the contract by calling the selfdestruct(address) function, the contract is vulnerable to UpS.
- **FE (Frozen Ether)**:  the contract can receive ether but cannot transfer it by itself, it is vulnerable to FE.

In [47]:
import pandas as pd
import pickle
import os
import json
import random
import numpy as np
import anthropic
import warnings
import time

with warnings.catch_warnings():
    warnings.simplefilter("ignore")

In [49]:
cwd = os.getcwd()

train = pd.read_parquet(f'{cwd}\\Vulnerable-Verified-Smart-Contracts\\train.parquet')
test = pd.read_parquet(f'{cwd}\\Vulnerable-Verified-Smart-Contracts\\test.parquet')
validation = pd.read_parquet(f'{cwd}\\Vulnerable-Verified-Smart-Contracts\\validation.parquet')

## Helper functions

In [52]:
def add_new_columns(dataset):
    vulns = ['IOU', 'TOD', 'RE', 'UcC', 'UpS', 'TD', 'TO', 'DC', 'NC', 'FE']
    tools = ['soldetector', 'slither', 'oyente', 'smartcheck']

    # Initialize new columns
    for vuln in vulns:
        dataset[f'{vuln}'] = "Undetected"
        for tool in tools:
            dataset[f'{vuln}_{tool}'] = "Undetected"
            
    for index, row in dataset.iterrows():
        overlapping = row['overlapping']
    
        # Parse JSON string to Python dictionary
        data = json.loads(overlapping)
    
        vulns = data.keys()
        for vuln in vulns:
            info_dict_list = data[vuln][0]
            dataset.at[index, f'{vuln}'] = "Detected"
            for info_dict in info_dict_list:
                # print(info_dict)
                try:
                    lines = str(info_dict['lines'])
                except KeyError as e:
                    lines = "[" + str(info_dict['line']) + "]"
                tool = info_dict['tool']
                dataset.at[index, f'{vuln}_{tool}'] = lines

def check_for_improper_detections(dataset):
    vulns = ['IOU', 'TOD', 'RE', 'UcC', 'UpS', 'TD', 'TO', 'DC', 'NC', 'FE']
    tools = ['soldetector', 'slither', 'oyente', 'smartcheck']
    result = dict()
    
    for vuln in vulns:
        vuln_df = dataset[dataset[vuln] == "Detected"]

        if len(vuln_df) > 0:
            # print("Vulnerability: ", vuln, "Number of samples: ", len(vuln_df))
            df = pd.DataFrame(columns=["file_path", "contract_address", "soldetector", "slither", "oyente", "smartcheck", "need_intervention"])
            # Set all columns except 'need_intervention' to 'object' type
            df[df.columns.difference(['need_intervention'])] = df[df.columns.difference(['need_intervention'])].astype('object')
            
            row_index = 0
            for index, row in vuln_df.iterrows():
                df.loc[row_index] = [row['file_path'], row['contract_address'], None, None, None, None, False]
                vul_lines_set_for_all_tool = []
                need_intervention = False
                for tool in tools:
                    vul_lines_set_for_tool = set()
                    if row[f'{vuln}_{tool}'] != "Undetected":
                        line_list = eval(row[f'{vuln}_{tool}'])
                        vul_lines_set_for_tool.update(line_list)
                        vul_lines_set_for_all_tool.append(vul_lines_set_for_tool)
                        if len(vul_lines_set_for_tool) > 0:
                            df.loc[row_index, tool] = str(vul_lines_set_for_tool)
                for i in range(len(vul_lines_set_for_all_tool)):
                    for j in range(len(vul_lines_set_for_all_tool)):
                        if i == j:
                            continue
                        if vul_lines_set_for_all_tool[i] != vul_lines_set_for_all_tool[j]:
                            need_intervention = True
                df.loc[row_index, "need_intervention"] = need_intervention
                row_index += 1
            result[vuln] = df
    return result

def count_need_intervention(result_dict):
    # print("Vulberability types: ", list(result_dict.keys()))
    # print("Number of vulnerability types: ", len(result_dict.keys()))
    count_dict = dict()
    count_sum = 0
    for key in result_dict.keys():
        df = result_dict[key]
        true_count = (df['need_intervention'] == True).sum()
        count_sum += true_count
        count_dict[key] = true_count
    return count_sum, count_dict

In [54]:
# Add new columns to the dataframes for further processing
add_new_columns(train)
add_new_columns(test)
add_new_columns(validation)

In [56]:
result_dict_train = check_for_improper_detections(train)
result_dict_test = check_for_improper_detections(test)
result_dict_validation = check_for_improper_detections(validation)

count_train, count_dict_train = count_need_intervention(result_dict_train)
count_test, count_dict_test = count_need_intervention(result_dict_test)
count_validation, count_dict_validation = count_need_intervention(result_dict_validation)

print("Train dataset\n===============================\n")
print("Number of contracts needing intervention: ", count_train)
print("Number of contracts needing intervention by vuln. type: ", count_dict_train)

print("\n\nTest dataset\n===============================\n")
print("Number of contracts needing intervention: ", count_test)
print("Number of contracts needing intervention by vuln. type: ", count_dict_test)

print("\n\nValidation dataset\n===============================")
print("Number of contracts needing intervention: ", count_validation)
print("Number of contracts needing intervention by vuln. type: ", count_dict_validation)

Train dataset
===============================

Number of contracts needing intervention:  267
Number of contracts needing intervention by vuln. type:  {'IOU': 30, 'TOD': 1, 'RE': 56, 'UcC': 0, 'UpS': 64, 'TD': 5, 'TO': 0, 'DC': 9, 'NC': 100, 'FE': 2}


Test dataset
===============================

Number of contracts needing intervention:  16
Number of contracts needing intervention by vuln. type:  {'IOU': 2, 'TOD': 0, 'RE': 2, 'UcC': 0, 'UpS': 3, 'TD': 1, 'DC': 1, 'NC': 7}


Validation dataset
===============================
Number of contracts needing intervention:  18
Number of contracts needing intervention by vuln. type:  {'IOU': 0, 'TOD': 0, 'RE': 1, 'UcC': 0, 'UpS': 5, 'TD': 0, 'TO': 0, 'DC': 1, 'NC': 11}

## Check one example to build a prompt suitable for narrowing the vulnerable line with the help of a LLM

In [272]:
df = result_dict_train['RE']

In [15]:
example_address = "0xdd71e35f680bb5adc77c6d1d9ef5793598e613dc"
processed_row = df[df['contract_address'] == example_address].iloc[0]
original_row = train[train['contract_address'] == example_address]
print("Information\n======================")
soldetector_lines = processed_row['soldetector']
slither_lines = processed_row['slither']
oyente_lines = processed_row['oyente']
smartcheck_lines = processed_row['smartcheck']
print("soldetector_line: ", soldetector_lines)
print("slither_line: ", slither_lines)
print("oyente_line: ", oyente_lines)
print("smartcheck_line: ", smartcheck_lines)


print("\n\nSource code\n====================")
source_code_value = original_row.iloc[0]['source_code']
print(source_code_value)

print("\n\nLine extraction\n====================")
if soldetector_lines != None:
    print("soldetector--------------------------------------------------")
    lines = source_code_value.splitlines()
    line_numbers = list(eval(soldetector_lines))
    line_numbers.sort()
    for line_number in line_numbers:
        l = lines[line_number - 1]
        print(l)

if slither_lines != None:
    print("slither--------------------------------------------------")
    lines = source_code_value.splitlines()
    line_numbers = list(eval(slither_lines))
    line_numbers.sort()
    for line_number in line_numbers:
        l = lines[line_number - 1]
        print(l)
        
if oyente_lines != None:
    print("oyente--------------------------------------------------")
    lines = source_code_value.splitlines()
    line_numbers = list(eval(oyente_lines))
    line_numbers.sort()
    for line_number in line_numbers:
        l = lines[line_number - 1]
        print(l)

if smartcheck_lines != None:
    print("smartcheck--------------------------------------------------")
    lines = source_code_value.splitlines()
    line_numbers = list(eval(smartcheck_lines))
    line_numbers.sort()
    for line_number in line_numbers:
        l = lines[line_number - 1]
        print(l)

Information
======================
soldetector_line:  {22}
slither_line:  {24}
oyente_line:  {22}
smartcheck_line:  None


Source code
====================
pragma solidity ^0.4.25;

contract Piggy_BanK
{
    function Put(uint _unlockTime)
    public
    payable
    {
        var acc = Acc[msg.sender];
        acc.balance += msg.value;
        acc.unlockTime = _unlockTime>now?_unlockTime:now;
        LogFile.AddMessage(msg.sender,msg.value,"Put");
    }

    function Collect(uint _am)
    public
    payable
    {
        var acc = Acc[msg.sender];
        if( acc.balance>=MinSum && acc.balance>=_am && now>acc.unlockTime)
        {
            if(msg.sender.call.value(_am)())
            {
                acc.balance-=_am;
                LogFile.AddMessage(msg.sender,_am,"Collect");
            }
        }
    }

    function()
    public
    payable
    {
        Put(0);
    }

    struct Holder
    {
        uint unlockTime;
        uint balance;
    }

    mapping (address => Holder) public Acc;

    Log LogFile;

    uint public MinSum = 1 ether;

    function Piggy_BanK(address log) public{
        LogFile = Log(log);
    }
}


contract Log
{
    struct Message
    {
        address Sender;
        string  Data;
        uint Val;
        uint  Time;
    }

    Message[] public History;

    Message LastMsg;

    function AddMessage(address _adr,uint _val,string _data)
    public
    {
        LastMsg.Sender = _adr;
        LastMsg.Time = now;
        LastMsg.Val = _val;
        LastMsg.Data = _data;
        History.push(LastMsg);
    }
}


Line extraction
====================
soldetector--------------------------------------------------
            if(msg.sender.call.value(_am)())
slither--------------------------------------------------
                acc.balance-=_am;
oyente--------------------------------------------------
            if(msg.sender.call.value(_am)())

In [41]:
client = anthropic.Anthropic(
    # defaults to os.environ.get("ANTHROPIC_API_KEY")
    # api_key="",
)

In [43]:
client.models.list(limit=20)

SyncPage[ModelInfo](data=[ModelInfo(id='claude-3-7-sonnet-20250219', created_at=datetime.datetime(2025, 2, 24, 0, 0, tzinfo=datetime.timezone.utc), display_name='Claude 3.7 Sonnet', type='model'), ModelInfo(id='claude-3-5-sonnet-20241022', created_at=datetime.datetime(2024, 10, 22, 0, 0, tzinfo=datetime.timezone.utc), display_name='Claude 3.5 Sonnet (New)', type='model'), ModelInfo(id='claude-3-5-haiku-20241022', created_at=datetime.datetime(2024, 10, 22, 0, 0, tzinfo=datetime.timezone.utc), display_name='Claude 3.5 Haiku', type='model'), ModelInfo(id='claude-3-5-sonnet-20240620', created_at=datetime.datetime(2024, 6, 20, 0, 0, tzinfo=datetime.timezone.utc), display_name='Claude 3.5 Sonnet (Old)', type='model'), ModelInfo(id='claude-3-haiku-20240307', created_at=datetime.datetime(2024, 3, 7, 0, 0, tzinfo=datetime.timezone.utc), display_name='Claude 3 Haiku', type='model'), ModelInfo(id='claude-3-opus-20240229', created_at=datetime.datetime(2024, 2, 29, 0, 0, tzinfo=datetime.timezone.utc), display_name='Claude 3 Opus', type='model')], has_more=False, first_id='claude-3-7-sonnet-20250219', last_id='claude-3-opus-20240229')

In [45]:
message = client.messages.create(
    model="claude-3-7-sonnet-20250219",
    max_tokens=1024,
    messages=[
        {"role": "user", "content": "Hello, Claude"}
    ]
)
print(message.content)

[TextBlock(citations=None, text="Hello! It's nice to meet you. How can I help you today? I'm here to assist with information, answer questions, have a conversation, or help with various tasks. What would you like to discuss or explore?", type='text')]

In [60]:
prompt_part_1 = """
Analyze the smart contract for reentrancy vulnerabilities and identify which line or lines make the smart contract vulnerable to reentrancy attacks.  

Here's the scenario:

Contract code:
```
{contract_code}
```

"""
prompt_part_2 = """
Vulnerability detection tool #{tool_number} identified {this_line_or_these_lines} as vulnerable:
{line_or_lines}

"""

prompt_part_3 = """
Think before you give the final answer. First, think about what a reentrancy vulnerability is and what are the possible ways the reentrancy vulnerability can occur in a smart contract. Then, examine the smart contract code and the results of the vulnerability detection tools to guide your analysis of how reentrancy vulnerability can occur in the given smart contract, and identify the scenarios in which reentrancy vulnerability occurs. Then evaluate scenarios to verify they are correct. Then output only the line or lines that make the smart contract vulnerable to reentrancy attacks. 

Provide your response in exactly this format:
VULNERABLE_LINES: [List all the lines that create the reenctrancy vulnerability a possibility in the given smart contract]
"""

In [62]:
prompt = prompt_part_1.format(contract_code=source_code_value)
prompt += prompt_part_2.format(tool_number="1", this_line_or_these_lines="this line", line_or_lines="```if(msg.sender.call.value(_am)())```")
prompt += prompt_part_2.format(tool_number="2", this_line_or_these_lines="this line", line_or_lines="```acc.balance-=_am;```")
prompt += prompt_part_2.format(tool_number="3", this_line_or_these_lines="this line", line_or_lines="```if(msg.sender.call.value(_am)())```")
prompt += prompt_part_3

print(prompt)

Analyze the smart contract for reentrancy vulnerabilities and identify which line or lines make the smart contract vulnerable to reentrancy attacks.

Here's the scenario:

Contract code:
```
pragma solidity ^0.4.25;

contract Piggy_BanK
{
    function Put(uint _unlockTime)
    public
    payable
    {
        var acc = Acc[msg.sender];
        acc.balance += msg.value;
        acc.unlockTime = _unlockTime>now?_unlockTime:now;
        LogFile.AddMessage(msg.sender,msg.value,"Put");
    }

    function Collect(uint _am)
    public
    payable
    {
        var acc = Acc[msg.sender];
        if( acc.balance>=MinSum && acc.balance>=_am && now>acc.unlockTime)
        {
            if(msg.sender.call.value(_am)())
            {
                acc.balance-=_am;
                LogFile.AddMessage(msg.sender,_am,"Collect");
            }
        }
    }

    function()
    public
    payable
    {
        Put(0);
    }

    struct Holder
    {
        uint unlockTime;
        uint balance;
    }

    mapping (address => Holder) public Acc;

    Log LogFile;

    uint public MinSum = 1 ether;

    function Piggy_BanK(address log) public{
        LogFile = Log(log);
    }
}


contract Log
{
    struct Message
    {
        address Sender;
        string  Data;
        uint Val;
        uint  Time;
    }

    Message[] public History;

    Message LastMsg;

    function AddMessage(address _adr,uint _val,string _data)
    public
    {
        LastMsg.Sender = _adr;
        LastMsg.Time = now;
        LastMsg.Val = _val;
        LastMsg.Data = _data;
        History.push(LastMsg);
    }
}
```


Vulnerability detection tool #1 identified this line as vulnerable:
```if(msg.sender.call.value(_am)())```


Vulnerability detection tool #2 identified this line as vulnerable:
```acc.balance-=_am;```


Vulnerability detection tool #3 identified this line as vulnerable:
```if(msg.sender.call.value(_am)())```


Think before you give the final answer. First, think about what a reentrancy vulnerability is and what are the possible ways the reentrancy vulnerability can occur in a smart contract. Then, examine the smart contract code and the results of the vulnerability detection tools to guide your analysis of how reentrancy vulnerability can occur in the given smart contract, and identify the scenarios in which reentrancy vulnerability occurs. Then evaluate scenarios to verify they are correct. Then output only the line or lines that make the smart contract vulnerable to reentrancy attacks.

Provide your response in exactly this format:
VULNERABLE_LINES: [List all the lines that create the reenctrancy vulnerability a possibility in the given smart contract]

In [64]:
response = client.messages.create(
    model="claude-3-7-sonnet-20250219",
    max_tokens=8000,
    system="You are a blockchain security expert specializing in smart contract vulnerability analysis. Your task is to analyze Solidity smart contracts for reentrancy vulnerabilities.",
    thinking={
        "type": "enabled",
        "budget_tokens": 4000
    },
    messages=[{
        "role": "user",
        "content": prompt
    }]
)

In [66]:
print(response.content[1].text)

I need to analyze this contract for reentrancy vulnerabilities by examining how it handles external calls and state updates.

A reentrancy vulnerability occurs when a contract:
1. Makes an external call to an untrusted address
2. Updates its state after that external call
3. Lacks protection against recursive calls

Looking at the `Collect` function:

```solidity
function Collect(uint _am)
public
payable
{
    var acc = Acc[msg.sender];
    if( acc.balance>=MinSum && acc.balance>=_am && now>acc.unlockTime)
    {
        if(msg.sender.call.value(_am)())
        {
            acc.balance-=_am;
            LogFile.AddMessage(msg.sender,_am,"Collect");
        }
    }
}
```

The vulnerability exists because:
1. The contract performs an external call with `msg.sender.call.value(_am)()` which can trigger code execution on the recipient address
2. The contract then updates the user's balance AFTER this call with `acc.balance-=_am;`
3. If the recipient is a malicious contract, its fallback function could call back into `Collect()` before the balance is updated

This violates the "checks-effects-interactions" pattern, where state changes should happen before external calls.

In an attack scenario:
- Attacker calls `Collect()`
- Contract verifies balance and sends Ether via `call.value()`
- Attacker's fallback function calls `Collect()` again
- Since balance hasn't been updated yet, the check passes again
- This repeats until gas is exhausted or funds are drained

VULNERABLE_LINES: [if(msg.sender.call.value(_am)()), acc.balance-=_am;]

## Analyze the smart contract that need intervention with the help of Claude 3.7 Sonet LLM model

In [59]:
client = anthropic.Anthropic(
    # defaults to os.environ.get("ANTHROPIC_API_KEY")
    # api_key="",
)

In [61]:
system_prompt_template = "You are a blockchain security expert specializing in smart contract vulnerability analysis. Your task is to analyze Solidity smart contracts for {vulnerability} vulnerabilities."

prompt_part_1 = """
Analyze the smart contract for {vulnerability} vulnerabilities and identify which line or lines make the smart contract vulnerable to {vulnerability} attacks.  

Here's the scenario:

Contract code:
```
{contract_code}
```

"""
prompt_part_2 = """
Vulnerability detection tool #{tool_number} identified {this_line_or_these_lines} as vulnerable:
{line_or_lines}

"""

prompt_part_3 = """
Think before you give the final answer. First, think about what a {vulnerability} vulnerability is and what are the possible ways the {vulnerability} vulnerability can occur in a smart contract. Then, examine the smart contract code and the results of the vulnerability detection tools to guide your analysis of how {vulnerability} vulnerability can occur in the given smart contract, and identify the scenarios in which {vulnerability} vulnerability occurs. Then evaluate scenarios to verify they are correct. Then output only the line or lines that make the smart contract vulnerable to {vulnerability} attacks. 

Provide your response in exactly this format:
VULNERABLE_LINES: [List all the lines that create the {vulnerability} vulnerability a possibility in the given smart contract]
"""

## Helper functions

In [84]:
def prepare_prompt_part_2(detected_lines_list, source_code_lines, prompt, tool_number):
    lines_for_prompt_list = None
    if detected_lines_list is not None and len(detected_lines_list) > 0:
        lines_for_prompt = ""
        lines_for_prompt_list = []
        this_line_or_these_lines = ""
        detected_lines_list.sort()
        for i in range(len(detected_lines_list)):
            line = detected_lines_list[i]
            if len(detected_lines_list) == 1:
                lines_for_prompt += "```" + source_code_lines[line - 1].strip() + "```"
                lines_for_prompt_list.append(source_code_lines[line - 1].strip())
                this_line_or_these_lines = "this line"
            else:
                this_line_or_these_lines = "these lines"
                if i == (len(detected_lines_list) - 1):
                    lines_for_prompt += "```" + source_code_lines[line - 1].strip() + "```"
                    lines_for_prompt_list.append(source_code_lines[line - 1].strip())
                else:
                    lines_for_prompt += "```" + source_code_lines[line - 1].strip() + "```,\n"
                    lines_for_prompt_list.append(source_code_lines[line - 1].strip())
        prompt += prompt_part_2.format(tool_number=tool_number, this_line_or_these_lines=this_line_or_these_lines, line_or_lines=lines_for_prompt)
    return prompt, lines_for_prompt_list

def evaluate_set_string_to_list(set_string):
    if set_string != None:
        return list(eval(set_string))
    else:
        return None

def call_anthropic_api(prompt, system_prompt):
    response = client.messages.create(
    model="claude-3-7-sonnet-20250219",
    max_tokens=8000,
    system=system_prompt,
    thinking={
        "type": "enabled",
        "budget_tokens": 4000
    },
    messages=[{
        "role": "user",
        "content": prompt
    }])
    return response.content

def change_vulnerability_name_for_file(vulnerability):
    if vulnerability == "Arithmetic/Integer Overflow and Underflow":
        return "Integer_Overflow_and_Underflow"
    elif vulnerability == "Nested Call":
        return "Nested_Call"
    elif vulnerability == "Timestamp Dependency":
        return "Timestamp_Dependency"
    elif vulnerability == "Transaction Order Dependency":
        return "Transaction_Order_Dependency"
    elif vulnerability == "Unchecked Call":
        return "Unchecked_Call"
    elif vulnerability == "Unprotected Suicide":
        return "Unprotected_Suicide"
    elif vulnerability == "Frozen Ether":
        return "Frozen_Ether"
    else:
        return vulnerability

def ask_from_claude(df, original_df, vulnerability, dataset_name, call_api=False):
    pre_claude_results = []
    df = df[df['need_intervention'] == True]
    for index, row in df.iterrows():
        contract_address = row['contract_address']
        file_path = row['file_path']
        original_row = original_df[(original_df['contract_address'] == contract_address) & (original_df['file_path'] == file_path)]
        # check if there is only one row returned
        if len(original_row) == 0 or len(original_row) > 1:
            print(f"An unexpected error occurred! The length of original_row is either 0 or greater than 1. contract address: {contract_address}, file_path: {file_path}")
            continue
        # get the source code for the smart contract
        source_code = original_row.iloc[0]['source_code']

        # get the vulnerable lines identified by each tool
        soldetector_lines = evaluate_set_string_to_list(row['soldetector'])
        slither_lines = evaluate_set_string_to_list(row['slither'])
        oyente_lines = evaluate_set_string_to_list(row['oyente'])
        smartcheck_lines = evaluate_set_string_to_list(row['smartcheck'])

        ############### Create the prompt #####################

        prompt = prompt_part_1.format(vulnerability=vulnerability, contract_code=source_code)

        source_code_lines = source_code.splitlines()
        
        # Soldetector
        prompt, vuln_lines_soldetector = prepare_prompt_part_2(soldetector_lines, source_code_lines, prompt,  "1")

        # Slither
        prompt, vuln_lines_slither = prepare_prompt_part_2(slither_lines, source_code_lines, prompt, "2")

        # Oyente
        prompt, vuln_lines_oyente = prepare_prompt_part_2(oyente_lines, source_code_lines, prompt, "3")

        # Smartcheck
        prompt, vuln_lines_smartcheck = prepare_prompt_part_2(smartcheck_lines, source_code_lines, prompt, "4")

        prompt += prompt_part_3.format(vulnerability=vulnerability)

        ############### Create the system prompt #####################

        system_prompt = system_prompt_template.format(vulnerability=vulnerability)

        # print("prompt:\n---------------------------------------------------------------------------------------------------------------------")
        # print(prompt)
        # print("\n\nsystem_prompt:\n----------------------------------------------------------------------------------------------------------")
        # print(system_prompt)
        # print("\n\n========================================================================================================================\n\n")

        info_dict = {"file_path": file_path, "contract_address": contract_address, "soldetector": vuln_lines_soldetector, "slither": vuln_lines_slither, "oyente": vuln_lines_oyente, "smartcheck": vuln_lines_smartcheck, "prompt": prompt, "system_prompt": system_prompt}
        pre_claude_results.append(info_dict)

    post_claude_results = []

    curr_api_req_index = 0
    if call_api:
        for entry in pre_claude_results:
            curr_api_req_index += 1
            try:
                response = call_anthropic_api(entry['prompt'], entry['system_prompt'])
                print(f"{curr_api_req_index}/{len(pre_claude_results)} requests done")
            except:
                print(f"Error while getting response for file_path: {file_path}, contract_address: {contract_address} from Anthropic API")
                continue
            new_entry = dict(entry)
            new_entry['response'] = response
            post_claude_results.append(new_entry)
            time.sleep(20) # wait 10 seconds

    vulnerability_name = change_vulnerability_name_for_file(vulnerability)
            
    with open(f"post_claude_results_{dataset_name}_{vulnerability_name}.pkl", "wb") as file:
        pickle.dump(post_claude_results, file)
    with open(f"pre_claude_results_{dataset_name}_{vulnerability_name}.pkl", "wb") as file:
        pickle.dump(pre_claude_results, file)
    return pre_claude_results, post_claude_results

In [74]:
# pre_claude_results, post_claude_results = ask_from_claude(result_dict_test['DC'], test, "DelegateCall", "test", call_api=True)

In [68]:
# print(post_claude_results[0]['response'][0].thinking)

### Train dataset

Number of contracts needing intervention:  267

Number of contracts needing intervention by vuln. type:  {'IOU': 30, 'TOD': 1, 'RE': 56, 'UcC': 0, 'UpS': 64, 'TD': 5, 'TO': 0, 'DC': 9, 'NC': 100, 'FE': 2}

In [86]:
dataset_name = "train"

# DC - DelegateCall 
_, _ = ask_from_claude(result_dict_train['DC'], train, "DelegateCall", dataset_name, call_api=True)

# IOU (Arithmetic/Integer Overflow and Underflow)
_, _ = ask_from_claude(result_dict_train['IOU'], train, "Arithmetic/Integer Overflow and Underflow", dataset_name, call_api=True)

# NC (Nested Call)
_, _ = ask_from_claude(result_dict_train['NC'], train, "Nested Call", dataset_name, call_api=True)

# RE (Reentrancy)
_, _ = ask_from_claude(result_dict_train['RE'], train, "Reentrancy", dataset_name, call_api=True)

# TD (Timestamp Dependency)
_, _ = ask_from_claude(result_dict_train['TD'], train, "Timestamp Dependency", dataset_name, call_api=True)

# TO (TxOrigin)
# _, _ = ask_from_claude(result_dict_train['TO'], train, "TxOrigin", dataset_name, call_api=True)

# TOD (Transaction Order Dependency)
_, _ = ask_from_claude(result_dict_train['TOD'], train, "Transaction Order Dependency", dataset_name, call_api=True)

# UcC (Unchecked Call)
# _, _ = ask_from_claude(result_dict_train['UcC'], train, "Unchecked Call", dataset_name, call_api=True)

# UpS (Unprotected Suicide)
_, _ = ask_from_claude(result_dict_train['UpS'], train, "Unprotected Suicide", dataset_name, call_api=True)

# FE (Frozen Ether)
_, _ = ask_from_claude(result_dict_train['FE'], train, "Frozen Ether", dataset_name, call_api=True)

1/9 requests done
2/9 requests done
3/9 requests done
4/9 requests done
5/9 requests done
6/9 requests done
7/9 requests done
8/9 requests done
9/9 requests done
1/30 requests done
2/30 requests done
3/30 requests done
4/30 requests done
5/30 requests done
6/30 requests done
7/30 requests done
8/30 requests done
9/30 requests done
10/30 requests done
11/30 requests done
12/30 requests done
13/30 requests done
14/30 requests done
15/30 requests done
16/30 requests done
17/30 requests done
18/30 requests done
19/30 requests done
20/30 requests done
21/30 requests done
22/30 requests done
23/30 requests done
24/30 requests done
25/30 requests done
26/30 requests done
27/30 requests done
28/30 requests done
29/30 requests done
30/30 requests done
1/100 requests done
2/100 requests done
3/100 requests done
4/100 requests done
5/100 requests done
6/100 requests done
7/100 requests done
8/100 requests done
9/100 requests done
10/100 requests done
11/100 requests done
12/100 requests done
13/100 requests done
14/100 requests done
15/100 requests done
16/100 requests done
17/100 requests done
18/100 requests done
19/100 requests done
20/100 requests done
21/100 requests done
22/100 requests done
23/100 requests done
24/100 requests done
25/100 requests done
26/100 requests done
27/100 requests done
28/100 requests done
29/100 requests done
30/100 requests done
31/100 requests done
32/100 requests done
33/100 requests done
34/100 requests done
35/100 requests done
36/100 requests done
37/100 requests done
38/100 requests done
39/100 requests done
40/100 requests done
41/100 requests done
42/100 requests done
43/100 requests done
44/100 requests done
45/100 requests done
46/100 requests done
47/100 requests done
48/100 requests done
49/100 requests done
50/100 requests done
51/100 requests done
52/100 requests done
53/100 requests done
54/100 requests done
55/100 requests done
56/100 requests done
57/100 requests done
58/100 requests done
59/100 requests done
60/100 requests done
61/100 requests done
62/100 requests done
63/100 requests done
64/100 requests done
65/100 requests done
66/100 requests done
67/100 requests done
68/100 requests done
69/100 requests done
70/100 requests done
71/100 requests done
72/100 requests done
73/100 requests done
74/100 requests done
75/100 requests done
76/100 requests done
77/100 requests done
78/100 requests done
79/100 requests done
80/100 requests done
81/100 requests done
82/100 requests done
83/100 requests done
84/100 requests done
85/100 requests done
86/100 requests done
87/100 requests done
88/100 requests done
89/100 requests done
90/100 requests done
91/100 requests done
92/100 requests done
93/100 requests done
94/100 requests done
95/100 requests done
96/100 requests done
97/100 requests done
98/100 requests done
99/100 requests done
100/100 requests done
1/56 requests done
2/56 requests done
3/56 requests done
4/56 requests done
5/56 requests done
6/56 requests done
7/56 requests done
8/56 requests done
9/56 requests done
10/56 requests done
11/56 requests done
12/56 requests done
13/56 requests done
14/56 requests done
15/56 requests done
16/56 requests done
17/56 requests done
18/56 requests done
19/56 requests done
20/56 requests done
21/56 requests done
22/56 requests done
23/56 requests done
24/56 requests done
25/56 requests done
26/56 requests done
27/56 requests done
28/56 requests done
29/56 requests done
30/56 requests done
31/56 requests done
32/56 requests done
33/56 requests done
34/56 requests done
35/56 requests done
36/56 requests done
37/56 requests done
38/56 requests done
39/56 requests done
40/56 requests done
41/56 requests done
42/56 requests done
43/56 requests done
44/56 requests done
45/56 requests done
46/56 requests done
47/56 requests done
48/56 requests done
49/56 requests done
50/56 requests done
51/56 requests done
52/56 requests done
53/56 requests done
54/56 requests done
55/56 requests done
56/56 requests done
1/5 requests done
2/5 requests done
3/5 requests done
4/5 requests done
5/5 requests done
1/1 requests done
1/64 requests done
2/64 requests done
3/64 requests done
4/64 requests done
5/64 requests done
6/64 requests done
7/64 requests done
8/64 requests done
9/64 requests done
10/64 requests done
11/64 requests done
12/64 requests done
13/64 requests done
14/64 requests done
15/64 requests done
16/64 requests done
17/64 requests done
18/64 requests done
19/64 requests done
20/64 requests done
21/64 requests done
22/64 requests done
23/64 requests done
24/64 requests done
25/64 requests done
26/64 requests done
27/64 requests done
28/64 requests done
29/64 requests done
30/64 requests done
31/64 requests done
32/64 requests done
33/64 requests done
34/64 requests done
35/64 requests done
36/64 requests done
37/64 requests done
38/64 requests done
39/64 requests done
40/64 requests done
41/64 requests done
42/64 requests done
43/64 requests done
44/64 requests done
45/64 requests done
46/64 requests done
47/64 requests done
48/64 requests done
49/64 requests done
50/64 requests done
51/64 requests done
52/64 requests done
53/64 requests done
54/64 requests done
55/64 requests done
56/64 requests done
57/64 requests done
58/64 requests done
59/64 requests done
60/64 requests done
61/64 requests done
62/64 requests done
63/64 requests done
64/64 requests done
1/2 requests done
2/2 requests done

### Test dataset

Number of contracts needing intervention:  16

Number of contracts needing intervention by vuln. type:  {'IOU': 2, 'TOD': 0, 'RE': 2, 'UcC': 0, 'UpS': 3, 'TD': 1, 'DC': 1, 'NC': 7}

In [80]:
dataset_name = "test"

# DC - DelegateCall
# _, _ = ask_from_claude(result_dict_test['DC'], test, "DelegateCall", dataset_name, call_api=True) -- Done

# IOU (Arithmetic/Integer Overflow and Underflow)
_, _ = ask_from_claude(result_dict_test['IOU'], test, "Arithmetic/Integer Overflow and Underflow", dataset_name, call_api=True)

# NC (Nested Call)
_, _ = ask_from_claude(result_dict_test['NC'], test, "Nested Call", dataset_name, call_api=True)

# RE (Reentrancy)
_, _ = ask_from_claude(result_dict_test['RE'], test, "Reentrancy", dataset_name, call_api=True)

# TD (Timestamp Dependency)
_, _ = ask_from_claude(result_dict_test['TD'], test, "Timestamp Dependency", dataset_name, call_api=True)

# TO (TxOrigin)
# _, _ = ask_from_claude(result_dict_test['TO'], test, "TxOrigin", dataset_name, call_api=True)

# TOD (Transaction Order Dependency)
# _, _ = ask_from_claude(result_dict_test['TOD'], test, "Transaction Order Dependency", dataset_name, call_api=True)

# UcC (Unchecked Call)
# _, _ = ask_from_claude(result_dict_test['UcC'], test, "Unchecked Call", dataset_name, call_api=True)

# UpS (Unprotected Suicide)
_, _ = ask_from_claude(result_dict_test['UpS'], test, "Unprotected Suicide", dataset_name, call_api=True)

# FE (Frozen Ether)
# _, _ = ask_from_claude(result_dict_test['FE'], test, "Frozen Ether", dataset_name, call_api=True)

1/2 requests done
2/2 requests done
1/7 requests done
2/7 requests done
3/7 requests done
4/7 requests done
5/7 requests done
6/7 requests done
7/7 requests done
1/2 requests done
2/2 requests done
1/1 requests done
1/3 requests done
2/3 requests done
3/3 requests done

### Validation dataset

Number of contracts needing intervention:  18

Number of contracts needing intervention by vuln. type:  {'IOU': 0, 'TOD': 0, 'RE': 1, 'UcC': 0, 'UpS': 5, 'TD': 0, 'TO': 0, 'DC': 1, 'NC': 11}

In [82]:
dataset_name = "validation"

# DC - DelegateCall
_, _ = ask_from_claude(result_dict_validation['DC'], validation, "DelegateCall", dataset_name, call_api=True)

# IOU (Arithmetic/Integer Overflow and Underflow)
# _, _ = ask_from_claude(result_dict_validation['IOU'], validation, "Arithmetic/Integer Overflow and Underflow", dataset_name, call_api=True)

# NC (Nested Call)
_, _ = ask_from_claude(result_dict_validation['NC'], validation, "Nested Call", dataset_name, call_api=True)

# RE (Reentrancy)
_, _ = ask_from_claude(result_dict_validation['RE'], validation, "Reentrancy", dataset_name, call_api=True)

# TD (Timestamp Dependency)
# _, _ = ask_from_claude(result_dict_validation['TD'], validation, "Timestamp Dependency", dataset_name, call_api=True)

# TO (TxOrigin)
# _, _ = ask_from_claude(result_dict_validation['TO'], validation, "TxOrigin", dataset_name, call_api=True)

# TOD (Transaction Order Dependency)
# _, _ = ask_from_claude(result_dict_validation['TOD'], validation, "Transaction Order Dependency", dataset_name, call_api=True)

# UcC (Unchecked Call)
# _, _ = ask_from_claude(result_dict_validation['UcC'], validation, "Unchecked Call", dataset_name, call_api=True)

# UpS (Unprotected Suicide)
_, _ = ask_from_claude(result_dict_validation['UpS'], validation, "Unprotected Suicide", dataset_name, call_api=True)

# FE (Frozen Ether)
# _, _ = ask_from_claude(result_dict_validation['FE'], validation, "Frozen Ether", dataset_name, call_api=True)

1/1 requests done
1/11 requests done
2/11 requests done
3/11 requests done
4/11 requests done
5/11 requests done
6/11 requests done
7/11 requests done
8/11 requests done
9/11 requests done
10/11 requests done
11/11 requests done
1/1 requests done
1/5 requests done
2/5 requests done
3/5 requests done
4/5 requests done
5/5 requests done

## Extract the vulnerable lines from LLM output and identify which line numbers they belong to in the source code

In [48]:
import pandas as pd
import pickle
import os
import json
import random
import numpy as np
import anthropic
import warnings
import time
import fnmatch
import re

with warnings.catch_warnings():
    warnings.simplefilter("ignore")

In [50]:
cwd = os.getcwd()

train = pd.read_parquet(f'{cwd}\\Vulnerable-Verified-Smart-Contracts\\train.parquet')
test = pd.read_parquet(f'{cwd}\\Vulnerable-Verified-Smart-Contracts\\test.parquet')
validation = pd.read_parquet(f'{cwd}\\Vulnerable-Verified-Smart-Contracts\\validation.parquet')

In [52]:
def add_new_columns(dataset):
    vulns = ['IOU', 'TOD', 'RE', 'UcC', 'UpS', 'TD', 'TO', 'DC', 'NC', 'FE']
    tools = ['soldetector', 'slither', 'oyente', 'smartcheck']

    # Initialize new columns
    for vuln in vulns:
        dataset[f'{vuln}'] = "Undetected"
        for tool in tools:
            dataset[f'{vuln}_{tool}'] = "Undetected"
            
    for index, row in dataset.iterrows():
        overlapping = row['overlapping']
    
        # Parse JSON string to Python dictionary
        data = json.loads(overlapping)
    
        vulns = data.keys()
        for vuln in vulns:
            info_dict_list = data[vuln][0]
            dataset.at[index, f'{vuln}'] = "Detected"
            for info_dict in info_dict_list:
                # print(info_dict)
                try:
                    lines = str(info_dict['lines'])
                except KeyError as e:
                    lines = "[" + str(info_dict['line']) + "]"
                tool = info_dict['tool']
                dataset.at[index, f'{vuln}_{tool}'] = lines

def check_for_improper_detections(dataset):
    vulns = ['IOU', 'TOD', 'RE', 'UcC', 'UpS', 'TD', 'TO', 'DC', 'NC', 'FE']
    tools = ['soldetector', 'slither', 'oyente', 'smartcheck']
    result = dict()
    
    for vuln in vulns:
        vuln_df = dataset[dataset[vuln] == "Detected"]

        if len(vuln_df) > 0:
            # print("Vulnerability: ", vuln, "Number of samples: ", len(vuln_df))
            df = pd.DataFrame(columns=["file_path", "contract_address", "soldetector", "slither", "oyente", "smartcheck", "need_intervention"])
            # Set all columns except 'need_intervention' to 'object' type
            df[df.columns.difference(['need_intervention'])] = df[df.columns.difference(['need_intervention'])].astype('object')
            
            row_index = 0
            for index, row in vuln_df.iterrows():
                df.loc[row_index] = [row['file_path'], row['contract_address'], None, None, None, None, False]
                vul_lines_set_for_all_tool = []
                need_intervention = False
                for tool in tools:
                    vul_lines_set_for_tool = set()
                    if row[f'{vuln}_{tool}'] != "Undetected":
                        line_list = eval(row[f'{vuln}_{tool}'])
                        vul_lines_set_for_tool.update(line_list)
                        vul_lines_set_for_all_tool.append(vul_lines_set_for_tool)
                        if len(vul_lines_set_for_tool) > 0:
                            df.loc[row_index, tool] = str(vul_lines_set_for_tool)
                for i in range(len(vul_lines_set_for_all_tool)):
                    for j in range(len(vul_lines_set_for_all_tool)):
                        if i == j:
                            continue
                        if vul_lines_set_for_all_tool[i] != vul_lines_set_for_all_tool[j]:
                            need_intervention = True
                df.loc[row_index, "need_intervention"] = need_intervention
                row_index += 1
            result[vuln] = df
    return result

def count_need_intervention(result_dict):
    # print("Vulberability types: ", list(result_dict.keys()))
    # print("Number of vulnerability types: ", len(result_dict.keys()))
    count_dict = dict()
    count_sum = 0
    for key in result_dict.keys():
        df = result_dict[key]
        true_count = (df['need_intervention'] == True).sum()
        count_sum += true_count
        count_dict[key] = true_count
    return count_sum, count_dict

In [54]:
# Add new columns to the dataframes for further processing
add_new_columns(train)
add_new_columns(test)
add_new_columns(validation)

In [56]:
result_dict_train = check_for_improper_detections(train)
result_dict_test = check_for_improper_detections(test)
result_dict_validation = check_for_improper_detections(validation)

count_train, count_dict_train = count_need_intervention(result_dict_train)
count_test, count_dict_test = count_need_intervention(result_dict_test)
count_validation, count_dict_validation = count_need_intervention(result_dict_validation)

print("Train dataset\n===============================\n")
print("Number of contracts needing intervention: ", count_train)
print("Number of contracts needing intervention by vuln. type: ", count_dict_train)

print("\n\nTest dataset\n===============================\n")
print("Number of contracts needing intervention: ", count_test)
print("Number of contracts needing intervention by vuln. type: ", count_dict_test)

print("\n\nValidation dataset\n===============================")
print("Number of contracts needing intervention: ", count_validation)
print("Number of contracts needing intervention by vuln. type: ", count_dict_validation)

Train dataset
===============================

Number of contracts needing intervention:  267
Number of contracts needing intervention by vuln. type:  {'IOU': 30, 'TOD': 1, 'RE': 56, 'UcC': 0, 'UpS': 64, 'TD': 5, 'TO': 0, 'DC': 9, 'NC': 100, 'FE': 2}


Test dataset
===============================

Number of contracts needing intervention:  16
Number of contracts needing intervention by vuln. type:  {'IOU': 2, 'TOD': 0, 'RE': 2, 'UcC': 0, 'UpS': 3, 'TD': 1, 'DC': 1, 'NC': 7}


Validation dataset
===============================
Number of contracts needing intervention:  18
Number of contracts needing intervention by vuln. type:  {'IOU': 0, 'TOD': 0, 'RE': 1, 'UcC': 0, 'UpS': 5, 'TD': 0, 'TO': 0, 'DC': 1, 'NC': 11}

### Load saved vulnerability identification results

In [59]:
vulns_mapping = {'IOU': "Integer_Overflow_and_Underflow", 'TOD': "Transaction_Order_Dependency", 'RE': "Reentrancy", 'UcC': "Unchecked_Call", 'UpS': "Unprotected_Suicide", 'TD': "Timestamp_Dependency", 'TO': "TxOrigin", 'DC': "DelegateCall", 'NC': "Nested_Call", 'FE': "Frozen_Ether"}
reverse_vulns_mapping = {v: k for k, v in vulns_mapping.items()}
print(reverse_vulns_mapping)

{'Integer_Overflow_and_Underflow': 'IOU', 'Transaction_Order_Dependency': 'TOD', 'Reentrancy': 'RE', 'Unchecked_Call': 'UcC', 'Unprotected_Suicide': 'UpS', 'Timestamp_Dependency': 'TD', 'TxOrigin': 'TO', 'DelegateCall': 'DC', 'Nested_Call': 'NC', 'Frozen_Ether': 'FE'}

In [61]:
all_pkl_files = [f for f in os.listdir(cwd) if fnmatch.fnmatch(f, "*.pkl")]
results_pkl_files = []
for file in all_pkl_files:
    if "post_claude_results_" in file:
        results_pkl_files.append(file)
train_results_pkl_files = dict()
test_results_pkl_files = dict()
validation_results_pkl_files = dict()

vulns_namings = list(reverse_vulns_mapping.keys())
def check_which_vuln_and_get_key(file_path):
    for vuln_name in vulns_namings:
        if "_" + vuln_name + ".pkl" in file_path:
            return reverse_vulns_mapping[vuln_name]
    
for file in results_pkl_files:
    key = check_which_vuln_and_get_key(file)
    if "_train_" in file:
        train_results_pkl_files[key] = file
    elif "_test_" in file:
        test_results_pkl_files[key] = file
    elif "_validation_" in file:
        validation_results_pkl_files[key] = file

print(train_results_pkl_files, len(train_results_pkl_files))
print(test_results_pkl_files, len(test_results_pkl_files))
print(validation_results_pkl_files, len(validation_results_pkl_files))

{'DC': 'post_claude_results_train_DelegateCall.pkl', 'FE': 'post_claude_results_train_Frozen_Ether.pkl', 'IOU': 'post_claude_results_train_Integer_Overflow_and_Underflow.pkl', 'NC': 'post_claude_results_train_Nested_Call.pkl', 'RE': 'post_claude_results_train_Reentrancy.pkl', 'TD': 'post_claude_results_train_Timestamp_Dependency.pkl', 'TOD': 'post_claude_results_train_Transaction_Order_Dependency.pkl', 'UpS': 'post_claude_results_train_Unprotected_Suicide.pkl'} 8
{'DC': 'post_claude_results_test_DelegateCall.pkl', 'IOU': 'post_claude_results_test_Integer_Overflow_and_Underflow.pkl', 'NC': 'post_claude_results_test_Nested_Call.pkl', 'RE': 'post_claude_results_test_Reentrancy.pkl', 'TD': 'post_claude_results_test_Timestamp_Dependency.pkl', 'UpS': 'post_claude_results_test_Unprotected_Suicide.pkl'} 6
{'DC': 'post_claude_results_validation_DelegateCall.pkl', 'NC': 'post_claude_results_validation_Nested_Call.pkl', 'RE': 'post_claude_results_validation_Reentrancy.pkl', 'UpS': 'post_claude_results_validation_Unprotected_Suicide.pkl'} 4

In [63]:
def check_result_output_formatting(file_path):
    not_according_to_format = 0
    not_according_to_format_loosed = 0
    with open(file_path, "rb") as file:
        data = pickle.load(file)  # Load the pickled data
    
        for item in data:
            response = item['response']
            text_portion = response[-1].text
            if "VULNERABLE_LINES: [" not in text_portion:
                not_according_to_format += 1
                # print(item['file_path'], item['contract_address'])
                # print(text_portion)
                # print("===========================================================================================\n\n")
            if "VULNERABLE_LINES: " not in text_portion:
                not_according_to_format_loosed += 1
        print("Tight formatting: ", file_path, not_according_to_format)
        print("Loose formatting: ", file_path, not_according_to_format_loosed)
        print()

def check_result_output_formatting_in_all():
    for file_path in results_pkl_files:
        check_result_output_formatting(file_path)

check_result_output_formatting_in_all()

Tight formatting:  post_claude_results_test_DelegateCall.pkl 0
Loose formatting:  post_claude_results_test_DelegateCall.pkl 0

Tight formatting:  post_claude_results_test_Integer_Overflow_and_Underflow.pkl 0
Loose formatting:  post_claude_results_test_Integer_Overflow_and_Underflow.pkl 0

Tight formatting:  post_claude_results_test_Nested_Call.pkl 0
Loose formatting:  post_claude_results_test_Nested_Call.pkl 0

Tight formatting:  post_claude_results_test_Reentrancy.pkl 0
Loose formatting:  post_claude_results_test_Reentrancy.pkl 0

Tight formatting:  post_claude_results_test_Timestamp_Dependency.pkl 0
Loose formatting:  post_claude_results_test_Timestamp_Dependency.pkl 0

Tight formatting:  post_claude_results_test_Unprotected_Suicide.pkl 0
Loose formatting:  post_claude_results_test_Unprotected_Suicide.pkl 0

Tight formatting:  post_claude_results_train_DelegateCall.pkl 0
Loose formatting:  post_claude_results_train_DelegateCall.pkl 0

Tight formatting:  post_claude_results_train_Frozen_Ether.pkl 0
Loose formatting:  post_claude_results_train_Frozen_Ether.pkl 0

Tight formatting:  post_claude_results_train_Integer_Overflow_and_Underflow.pkl 1
Loose formatting:  post_claude_results_train_Integer_Overflow_and_Underflow.pkl 0

Tight formatting:  post_claude_results_train_Nested_Call.pkl 4
Loose formatting:  post_claude_results_train_Nested_Call.pkl 0

Tight formatting:  post_claude_results_train_Reentrancy.pkl 4
Loose formatting:  post_claude_results_train_Reentrancy.pkl 0

Tight formatting:  post_claude_results_train_Timestamp_Dependency.pkl 0
Loose formatting:  post_claude_results_train_Timestamp_Dependency.pkl 0

Tight formatting:  post_claude_results_train_Transaction_Order_Dependency.pkl 0
Loose formatting:  post_claude_results_train_Transaction_Order_Dependency.pkl 0

Tight formatting:  post_claude_results_train_Unprotected_Suicide.pkl 1
Loose formatting:  post_claude_results_train_Unprotected_Suicide.pkl 0

Tight formatting:  post_claude_results_validation_DelegateCall.pkl 0
Loose formatting:  post_claude_results_validation_DelegateCall.pkl 0

Tight formatting:  post_claude_results_validation_Nested_Call.pkl 0
Loose formatting:  post_claude_results_validation_Nested_Call.pkl 0

Tight formatting:  post_claude_results_validation_Reentrancy.pkl 1
Loose formatting:  post_claude_results_validation_Reentrancy.pkl 0

Tight formatting:  post_claude_results_validation_Unprotected_Suicide.pkl 0
Loose formatting:  post_claude_results_validation_Unprotected_Suicide.pkl 0

In [65]:
def extract_vulnerable_lines(text):
    match = re.search(r"VULNERABLE_LINES:(.*)", text, re.DOTALL)
    if match:
        return match.group(1)  # Extract the content inside brackets
    return None

def check_results(file_path):
    not_according_to_format = 0
    not_according_to_format_loosed = 0
    with open(file_path, "rb") as file:
        data = pickle.load(file)  # Load the pickled data
    
        for item in data:
            response = item['response']
            text_portion = response[-1].text
            extracted_match = extract_vulnerable_lines(text_portion)
            print(extracted_match, item['file_path'], item['contract_address'])
            print()

def check_results_in_all():
    for file_path in results_pkl_files:
        check_results(file_path)

check_results_in_all()

 [607-608, 624-625, 680-681] Pair.sol 0x0b3ded1b54e89f8899482cfccf515d525835bc2b

 [return denominator * 100 * address(this).balance / targetAmount;, emit Transfer(address(this), targetAddress, denominator * msg.value / targetAmount * 100);] PiggyBank.sol 0x7a0ec191d8f44f3bc3cbb4d1105ced31c30ff492

 [uint256 newToVal = oldToVal + _value;]

While there is a check (`require(newToVal > oldToVal);`) that helps detect overflow, this approach isn't foolproof in all scenarios and could potentially be circumvented depending on implementation details. TokenTycoonIGO.sol 0xfb673f08fc82807b4d0e139e794e3b328d63551f

 [for(uint winList = 0; winList < winners.length; winList++){ , winners[winList].transfer(bonusETH.div(64));] CrystalReignShard.sol 0x5108e432d40d34a4d0ed88c12e83db0e571bfc75

 [for (uint256 i = 0; i < list.length; i++) {, address(list[i]).transfer(amount);] MultiEthSender.sol 0x11352d75f63804d5f8fdb88bddf9efe9b52d6723

 [_contributors[i].transfer(_balances[i]);, for (i; i < _contributors.length; i++) {] eTrustmoney.sol 0xa5c62860475ce15c5e38a8443ca53f72113c0a5c

 [_to[i].transfer(_value[i]);] Multiplexer.sol 0x7b138cc83ecccd6331cd7651c75ee3eb2ec6682e

 [Line 618: players[i].transfer(playerInfo[players[i]].betAmount);, Line 647: players[i].transfer(winOdds.mul(playerInfo[players[i]].betAmount).div(100));] BetCenter.sol 0x35bab7165a301e99c75c3e59b48817856b4d5e5c

 [recip.transfer(contribAmount);] BEthy.sol 0x248fda6a145642bd9bba9d5d349164e8ffe933cc

 [for (uint i = 0; i < players.length; i++) {, players[i].transfer(playerInfo[players[i]].betAmount);] ChampionSimple.sol 0xbd8dd6d726c3fcdbfa9a1279a98a7320cfe4d800

 [if(msg.sender.call.value(_am)()), balances[msg.sender]-=_am;] DEP_BANK.sol 0xaae1f51cf3339f18b6d3f3bdc75a5facd744b0b8

 [if(msg.sender.call.value(_am)()), acc.balance-=_am;] THE_BANK.sol 0xcb6fe98097fe7d6e00415bb6623d5fc3effa4e83

 [require(capsule.unlockTime <= block.timestamp);] EthCapsule.sol 0x5274a2293dbe075a82d41e873bb927403a9dce46

 [function BurnMe () {, selfdestruct(address(this));}] GetsBurned.sol 0x5f15d2d4c60e229586a5bdfe2eec1981f92845c1

 [selfdestruct(0x945C84b2FdD331ed3E8e7865E830626e6CeFAB94);] PonziToken.sol 0x33f00114d5aca3dee03189d4ed9d4f886dad84b0

 [selfdestruct(targetAddress);] PiggyBank.sol 0x7a0ec191d8f44f3bc3cbb4d1105ced31c30ff492

 [(bool status, ) = paymentProxy.delegatecall(] ChainlinkConversionPath.sol 0xf7228efefa12cd768e0f32a7c5cd0c0d68f835e4

 [(bool status, ) = paymentProxy.delegatecall(] ERC20ConversionProxy.sol 0xe72ecea44b6d8b2b3cf5171214d9730e86213ca2

 [(bool success, bytes memory result) = swapModule.delegatecall(abi.encodeWithSignature("swapReward(uint256,address,address[])", availableReward, address(this), path));] MoonbaseNFTAirdrop.sol 0x514aade50d0a679afd172720a7b6fbaccccb64ee

 [Lines in the ProtocolAdapter library where delegatecall is invoked, specifically in the functions delegatePurchase, delegatePurchaseWithZeroEx, delegateExercise, delegateClaimRewards, delegateCreateShort, and delegateCloseShort - all containing patterns like `address(adapter).delegatecall(...)`] RibbonThetaVault.sol 0x00a62ee3d2998f67cc202990b792573961d282e6

 [(bool success, bytes memory result) = address(this).delegatecall(calls[i]);] contracts/pools/loss/MasterPool.sol 0xb9112feef2054acc4066c40e8c2784fa3e9d032f

 [(bool success, bytes memory returnData) = address(plugin).delegatecall(abi.encodeWithSelector(plugin.execute.selector, path, amounts, addresses, data))] DePayRouterV1.sol 0xae60ac8e69414c2dc362d0e6a03af643d1d85b92

 [(bool success, bytes memory returnData) = plugin.delegatecall(abi.encodeWithSelector(IDePayPaymentsV1Plugin(plugin).execute.selector, path, amounts, addresses, data));] DePayPaymentsV1.sol 0xa5ec11d6a58b5cc03d1f28debb5077d41287acd2

 [require(address(converterRamp).delegatecall(bytes4(0x86ee863d), address(tokenConverter), address(mana), loanParams, 0x140, converterParams, 0x0), "Error delegate pay call");] contracts/MortgageHelper.sol 0x90263ea5c57dc6603ca7202920735a6e31235bb9

 [106-108, 204-212] contracts/fees/TokenDistributor.sol 0xab53b3906398897f5c4161bfe2ba61d302f00218

 [contract TotlePrimary {, function performSwapCollection(, TotlePrimaryUtils.SwapCollection calldata swaps, ) external payable {, }, }] Swapper.sol 0xea483a51abbb216bf7f35b7a8d7eb7f040fa2e4e

 [function performSwapCollection(TotlePrimaryUtils.SwapCollection calldata swaps) external payable {}] Swapper.sol 0xfb774ac09c2cb7a6f47b4d8367293820e4b4c660

 [function batchTtransferEther(address[] _to,uint256[] _value) public payable {] A004.sol 0xcae22909c9dbc37c2f6c2780d1f58decd5d3b1fd

 [for (uint32 i = 0; i < _tos.length; i++) {] Distribute.sol 0x84004ca3b679b94d5c27c59d710e8201068bb93b

 [total -= _balances[i];] ITSETH.sol 0xfb9ba5b45ffb009a369fdb5140fd470e7bdcdd66

 [end_date = now + 90 days;, holder_balance[msg.sender] += msg.value;, ETHRaised += msg.value;] myPreICO.sol 0x35e44051799bd7cea091c4fad2cba9b37e364c5b

 [Line 553: ownershipTokenCount[_to]++;, Line 556: tokenIndexToOwner[_tokenId] = _to;, Line 562: ownershipTokenCount[_from]--;, Line 568: for (uint i = 0; i < fromTokens.length - 1; i++), Line 944: dungeons[_id].rewards += uint128(_additinalRewards);, Line 483: dungeons.push(Dungeon(uint32(now), 0, uint8(_difficulty), uint16(_capacity), 0, 0, 0, _seedGenes, 0));] DungeonCoreBeta.sol 0x141766882733cafa9033e8707548fdcac908db22

 [584, 590, 748, 750, 754, 755, 759, 760, 834-836, 838-840, 842-844, 846-848, 706, 917-919] EDCoreVersion1.sol 0xf7ed56c1ac4d038e367a987258b86fc883b960a1

 191, 202, 138, 159, 178 UserfeedsClaimWithConfigurableTokenMultiTransfer.sol 0xecbed48098c4f25a16195c45ddf5fd736e28b14b

 [return currentQueueSize - currentReceiverIndex;] ESmart.sol 0x84cd9cf60bcb44f7bab8b75e6f03614c2c3b22b7

 [balances[_customerAddress] -= _amountOfTokens;, tokenSupply_ -= _amountOfTokens;, rewardLedger[referrer] += _amountToDistribute*(5-i)/15;, _amountToDistribute -= _amountToDistribute*(5-i)/15;, rewardLedger[feeHolder_] += _amountToDistribute;, rewardLedger[dev1] += _amountToDistribute*750/1000;, rewardLedger[dev2] += _amountToDistribute*250/1000;] AdoreNetwork.sol 0x663a9eba94dad8ca08917549ceb10565dffd5351

 [338, 530, 531, 596, 622, 623] CrystalDeposit.sol 0xcb8361f6ea2c93a39ffd9e8357ed6ccd48331dea

 ["for (uint i=0; i<addresses.length; i++)"] NaiveSplit.sol 0xb0ebc0f42420dcf301c711f79850b76213fad373

 [total += counts[i];] MultiSend.sol 0x410804f20daf6498ec564a20132985b8da401c2e

 [total += counts[i];] MultiSend.sol 0xc6fb494987cafaeda71a4052da7ff0695ca3998d

 [for (uint8 i = 0; i < _to.length; i++){, uint amount = _value[i] * 1 finney;] Rainmaker.sol 0x76e5cfba9633a467e77db2587a50c0bec4389ab9

 [tokensOwed[msg.sender] += amountToSend;, tokenSold += amountToSend;, ethContribution[msg.sender] += msg.value;] LynchpinPrivateICO.sol 0x36cce24d6314445c11beb80f99f9f14b5ea9ecc2

 [] EthealSplit.sol 0x99d804f479df333ed4d2287af2d4da3eda1b3cd1

 [] Send.sol 0xf9e7083fd1ca37db176046ba17cc0fede7fa855d

 [Line 974: index = i * 11;, Line 805: fashionArray.length += 1;, Line 478: fsArray.length -= 1;, Line 614: fsArray.length -= 1;, Line 622: destroyFashionCount += 1;] DataEquip.sol 0x4209f9bbb4e4dd48dbd84701fcaaab1d492b5a05

 [timeOut = now + (_timeLimit * 1 hours);] xcat.sol 0xb8aa8971e9201d183d1dadf5acc5c3f6b3076bc0

 [return 100 * address(this).balance / targetAmount;] PiggyBank.sol 0x126ae85a1ebf49dc946224f5268c6bd8338d49ae

 ["for (uint i = 0; i < _tos.length; i++)", "function transferETHS(address[] _tos) payable public returns(bool) {"] Distribute.sol 0xf3163e55e521bd49521976d43d82d21a9729dc9d

 [uint _value = v * 10 ** _decimals;] airDrop.sol 0xe894d54dca59cb53fe9cbc5155093605c7068220

 [var value = donationData[msg.sender];] RaiseFundsForACause.sol 0x7b74e83cacf86443a1cad1152179cbeff8e25e29

 [Line 735: numOfDigits += decimalLength(_values[i]);, Line 736: return uint256(10) ** (roundDiv(numOfDigits, length) - 1);] contracts/converter/LiquidityPoolV1Converter.sol 0xa2787e3bfd992725183868c40d36137bbc174c3a

 [
info.users[_from].balance -= _tokens;
uint256 _burnedAmount = _tokens * burn_rate / 100;
info.users[_to].balance += _transferred;
_burnedAmount /= 2;
transferCount = transferCount + 1;
info.users[_from].allowance[msg.sender] -= _tokens;
info.totalFrozen += _amount;
info.users[_who].frozen += _amount;
info.totalFrozen -= _amount;
info.users[msg.sender].balance -= _burnedAmount;
info.users[msg.sender].frozen -= _amount;
] Amp.sol 0x27f97bc09a4e28d5935a08e2810b3e3c94f04220

 [for (uint i = 0; i < recipients.length; i++)] UserfeedsClaimWithConfigurableValueMultiTransfer.sol 0xfad31a5672fbd8243e9691e8a5f958699cd0aaa9

 [round = round + 1, uint256 endTime = now + HALF_TIME] CrystalShare.sol 0x59a8b4400ebfd61d42d8aade332076c220f72d42

 [Line 784: petPresellCounter[_protoId] = (curSupply - 1);] ActionPresell.sol 0xc333228daab9bde8a3866efa3a9e616b7e1bae51

 [uint8 position = row * BOARD_ROW_SIZE + col;] contracts/GoGameLogic.sol 0x34bd7814bfef669936f05e355abd882acfc569b2

 [stage += 1;] DeLottery.sol 0x4763768d6938353c9c8849115c58a32142b0f9ea

 [for (uint64 investorNumber; investorNumber < investorCount; investorNumber++) {, investor.transfer(amountToSend);, etherHasBeenReturnedToInvestors = true;] TokenERC20.sol 0xd70e66775a74a9aedeac6e28313e1033cd726552

 [_contributors[i].transfer(_balances[i]);] CyberTrustMoney.sol 0x636ee05cdc28a7d6af8d04ac2c45a3d3095263cb

 [addr[i].transfer(val[i]);] Distributor.sol 0x3cd0c444137bac6996f262f92d1b79d6e8ad85b8

 [address(tos[i]).transfer(eachAmount);, bep20.transferFrom(msg.sender, tos[i], eachAmount);] AlbertToolsV1.sol 0x6f4902bcea0a62bc2abba3edb8dfe279e2c2a71c

 [winner.transfer(prize);] bet1000_001eth.sol 0xab3b0810b839f49c2d619b55f196aae764422e22

 [for (uint256 i = 0; i < recipients.length; i++) payable(recipients[i]).transfer(values[i]);] contracts/multisend/Multisend.sol 0x22bc0693163ec3cee5ded3c2ee55ddbcb2ba9bbe

 [recipients[i].transfer(values[i]);] Dispenser.sol 0xa47e7fd2e2ef08d63b58d9a416d88385e1145355

 [addresses[i].transfer(giveAmount);] TarynToken.sol 0x4bb301e545a3e948b20ea9a0f02d3948af6fe6db

 [addresses[i].transfer(amount);] MultiSender.sol 0x67af54d9e20fe6f9dd2dfe0449ed65f97a3638de

 [_receivers[i].transfer(_amounts[i]);] BatchTransfer.sol 0x6e82aabffe24f275ad3f703aca922dd4d8f86168

 [holders[i].transfer((bal * perToken)-powercost);, holders[i].transfer(balanceOf[holders[i]] * perToken);] MiningToken.sol 0xbac2dc4fe58f1f3382f036b1cb8d92591e0c135f

 [_to[i].transfer(_value[i]);] A004.sol 0xcae22909c9dbc37c2f6c2780d1f58decd5d3b1fd

 ["for (i; i < _contributors.length; i++) {", "_contributors[i].transfer(_balances[i]);"] EtherFox.sol 0x48e34dd473867d78c4a1304ff28e55150873590d

 [278, 281, 283] Nihilum.sol 0x5f9df71056d7c7530ae75d773bac98cfa887dbd4

 [_contributors[i].transfer(_balances[i]);] BizalomIo.sol 0x37dae106f0840575a6854de5777a3ea6aaa4b777

 [`for (uint32 i = 0; i < _tos.length; i++) {`, `_tos[i].transfer(val);`] Distribute.sol 0x84004ca3b679b94d5c27c59d710e8201068bb93b

 [_to[ui].transfer(_amount[ui]);] MultiTransfer.sol 0x75befea129f89ac27c8bf3f8215730ee944369a7

 [address(uint160(to)).transfer(amount);] TGToken.sol 0x20ed9f7c91e2b4ab24ae1d41559fbc01b246369b

 [ticketIndex[i].transfer(bet);] UnilotBonusTailEther.sol 0xcff681c07541b6921aac59fee73f1bab7b29d7b7

 players[_affId].playerAddress.transfer(TenPercentCom); players[mainInvestor].playerAddress.transfer(FifteenPercentCom); players[_investorId].playerAddress.transfer(TwoPercentCom); cfoAddress.transfer(FifteenPercentCom); winningAddress.transfer(address(this).balance); Vitaluck.sol 0xb36a7cd3f5d3e09045d765b661af575e3b5af24a

 [_contributors[i].transfer(_balances[i]);]

This line creates the vulnerability because it initiates external calls to potentially malicious contracts during the loop iteration, allowing for possible manipulation across multiple transfers. ITSETH.sol 0xfb9ba5b45ffb009a369fdb5140fd470e7bdcdd66

 [recipients[i].transfer(amounts[i]);] InternalTxsTest.sol 0x93ecd2badb4ef90cdf913d26ecd7a29feece19ac

 [70, 47, 31] Kongtou.sol 0x3967f481031f78a3fcbfe5c6a1079ec9f8426432

 [for (uint256 i=0; i<recipients.length; i++), recipients[i].transfer(amountPerRecipient);] SendToMany.sol 0x70e531091d82e183f7246012d1566c3fe1315625

 [winnerQueueAddresses[0].transfer(winnerQueueAmount[0]);] DoubleEther.sol 0x9d1cbf4ef833340120e721e5028c326ec1066c7e

 [talks[i].addr.transfer(talks[i].amount.mul(70).div(100));] ConferencePay.sol 0xce5eae9c07f7a65e904396a7849f37ab3ed14465

 [_to[ui].transfer(_amount[ui]);] MultiTransfer.sol 0x945d886e3859cc683c368ee3390b1c2c332dde46

 [function manual_withdraw() public {
    for(uint i = 0; i < addresses.length; i++) {
        addresses[i].transfer( ethBalanceOf(addresses[i]) );
    }
}] Random.sol 0x80406b7d3b9189968e3499d4f69cb015ae6f4b96

 [
  "recipients[i].send(amount);",
  "recipients[i].transfer(values[i]);",
  "require(token.transferFrom(msg.sender, recipients[i], values[i]));",
  "token.transferFrom(msg.sender, recipients[i], values[i]);"
] UserfeedsClaimWithConfigurableTokenMultiTransfer.sol 0xecbed48098c4f25a16195c45ddf5fd736e28b14b

 [recipients[i].transfer(values[i]);] Disperse.sol 0x99fbbfb44c53ba981e1d835313bd5e0043441c3e

 [address(uint160(to[i])).transfer(amounts[i]);, address(uint160(to[i])).transfer(toSent);, uint256 price = 10**36 / uint256(IMakerPriceFeed(oracle).read());] MultiTransfer.sol 0x5baaa5d1f5fd6f9136d470b6508b05bcded61589

 [_to[i].transfer(_value);, for(uint i = 0; i < _to.length; i++) { in the etherTransfer function] AirDrop.sol 0x9383bdb2229c0e62404d4748e337d7ffda4a4446

 [_dests[i].transfer(_amounts[i]);, for (uint i = 0; i < _dests.length; i++){ (in multisendEth function)] MultiSender.sol 0xafee74b6b4a3fc8b399b4c12cabfd9acb53c4992

 [31, 44, 43, 20, 32] Tipbot.sol 0x51bb6fd1ab2cf10076549df44d4b6eda2a00e093

 [_contributors[i].transfer(_balances[i]);] UpgradebleStormSender.sol 0x8ee52258265a68b594288da6b6e7b166320d6eba

 [address(uint160(_to[i])).transfer(_value[i]); in sendEth, assert(msg.sender.send(remainingValue)); in sendEth, assert(token.transferFrom(msg.sender, _to[i], _value[i]) == true); in sendErc20] CapitalPay.sol 0x199fb7016f7635de3924d80087bcb367cd123b51

 [winner.transfer(prize);, developer.transfer(remain);] bet_various.sol 0x4caa99bf19a1834bfe87c5552e11a2506e4101e5

 [for (uint i = 0; i < holders.length; i++), ballanceOfHolder = token.balanceOf(holders[i]), holders[i].transfer(ballanceOfHolder.mul(weiAmount).div(token.totalSupply()))] ObizcoinCrowdsaleToken.sol 0xbf5eed8d51b20834c9d887b22c229237922055d7

 [myAddresses[0].transfer(value);, myAddresses[i].transfer(distr);, myAddresses[myAddresses.length-1].transfer(value);] batchTransfer.sol 0xfea71f436ec963507c26f424d93168e4285cd822

 [_addresses[i].transfer(msg.value.div(_addresses.length));, _addresses[i].transfer(_value[i]);] AirDrop.sol 0x811437d9fbe43be7ecff117d9986253c36bc2438

 [_contributors[i].transfer(_balances[i]);] xyphar.sol 0x12359487aa7844fead6a20aca5bfae1d3196cedb

 _contributors[i].transfer(_balances[i]); SendEtherContributors.sol 0xb21f0b2b35332d1a39bcfb8f2f18bd49a8f8cbe8

 [`for (uint i = 0; i < playerPool.length; i++) {`, `playerPool[i].transfer(100 finney);`] Lotto.sol 0x3c635e7d4a73a09db2317f0abca7243913908929

 [_contributors[i].transfer(_balances[i]);] AirdropEther.sol 0xa9860973c62986cec31f51a858608fcd18b55264

 [_contributors[i].transfer(_balances[i]);] SmartSageMatrix.sol 0x8a219f369793a8497a283f167b6b409f7ebc8eae

 [for(uint i = 0 ; i < balancesKeys.length ; i++) {, addr.transfer(value);] MSRiseTokenSale.sol 0xcf2f73897369b8af9229cd6eb3923267256c13dd

 [partners[j].from.transfer(share);, owner.transfer(ownerShare);, delete partners;] Slot.sol 0x17d0582dee50a5401bb8f65ac29ec2da50c670ea

 [304-306, 310] GameLogic.sol 0x5d84827b41abefd47af454f77227dab4895c47a9

 [for (uint8 i = 0; i < _size; i++) {, participants[gameIndex][i].transfer(PRICE);] Slot.sol 0xd6b3d9e44f767f0c178f60d24fb186ba49bc444a

 [caddress.call(id,from,_to[i],_value[i]); in batchTransferVoken, caddress.call(id,from,_to[i],_value[i]); in forecchusdt, tc_address[i].call(id,msg.sender,from,t_value[i]); in tosonfrom] Transit.sol 0x43dce347203eb1a728c7364f4b423733a04c5338

 [addresses[i].transfer(split);, for (uint i=0; i<addresses.length; i++) {] NaiveSplit.sol 0xb0ebc0f42420dcf301c711f79850b76213fad373

 [addresses[i].transfer(counts[i]);] MultiSend.sol 0x410804f20daf6498ec564a20132985b8da401c2e

 [Line 114: `addresses[j].transfer(amounts[j] * 1 wei);`, Line 156: `tokenAddr.transferFrom(msg.sender, addresses[j], amounts[j]);`] BulkSend.sol 0x84e12ee99f6ae405d1d75a5eddb4513a1e90157c

 [recipients[i].transfer(values[i]);] DisperseVKZ.sol 0xcff6cfda2c289022e65a043c8f7b8ffe768be2dd

 [list[i].transfer(amount);, for(uint i=0;i<list.length;i++){] MultiEthSender.sol 0xb52323c98e75974d2139e65d3cba06c43a53cae4

 [L561 (ownerOf(_id).transfer(token.price * (100 - 2 * SALE_FEE_RATE) / 100)), L566 (for (uint i = 1; i <= totalSupply(); i++) {), L568 (ownerOf(i).transfer(bonus)), L535 (ownerOf(carveUpTokens[j]).transfer(bonus))] NFToken.sol 0x308df6e60b7dffc2bdee7fa62d41ef53ac5d4e43

 [addresses[i].transfer(counts[i]);] MultiSend.sol 0xc6fb494987cafaeda71a4052da7ff0695ca3998d

 [addresses[i].transfer(amounts[i]);] MultiSender.sol 0x3885a234f24b1a4842f1df0f1ee2f91507876851

 [for (uint8 i = 0; i < _to.length; i++){, _to[i].transfer(amount);] Rainmaker.sol 0x76e5cfba9633a467e77db2587a50c0bec4389ab9

 [for(uint i=0;i<referals.length;i++){, referals[i].transfer( referalProfits[referals[i]]);}] Win20ETH.sol 0x6ac93e04f24b57e7544bce967aedd0f7df50ea0d

 [77-78, 99-106, 118-125] FantasySports.sol 0x14b16fdf2b13589e9ddb834451bd4d673838e88c

 [ticketIndex[i].transfer(bet); in BaseUnilotGame.revoke(), ticketIndex[lastId].transfer(prizes[i]); in UnilotTailEther.finish(), administrator.transfer(this.balance); in UnilotTailEther.finish(), administrator.transfer(this.balance); in UnilotBonusTailToken.finish()] UnilotBonusTailToken.sol 0xc890b3450f273209cd19a11d4027e968bdd6f04e

 ["_contributors[i].transfer(_balances[i]);", "erc20token.transferFrom(msg.sender, _contributors[i], _balances[i]);"] contracts/multisender/UpgradebleAirdropSender.sol 0x14f550a6ab3c46aa1e01f69e5bc06b7ec8714142

 [addrs[i].transfer(amount);, for (uint256 i = 0; i < addrs.length; i++) {] Send.sol 0xf9e7083fd1ca37db176046ba17cc0fede7fa855d

 [_contributors[i].transfer(_balances[i]);] Netethermoney.sol 0x63d8c374aee994d62fa532f39089e1e61feae310

 [receivers[i].transfer(amounts[i]);, token.transferFrom(msg.sender,receivers[i], amounts[i]);] C98MultiSend.sol 0xaec945e04baf28b135fa7c640f624f8d90f1c3a6

 [for(uint i = 0; i < length; i++){, investorA.transfer(amount);] UTEMIS.sol 0x78b17cc10c4d34fbf6cb474731f7340e487a5db3

 [329, 334, 335, 339] Crowdsale.sol 0xcdc687a449c43fcf87d439af9fa72ee9602e6b1f

 [_contributors[i].transfer(_balances[i]);] ClubEther.sol 0x65622d8cfcd3d3baf37746136e877cafc7936e87

 [for (i = 0; i < investors.length; i++) {, investors[i].transfer(ethAmounts[i]);] BatchTransferContract.sol 0x8668ef4534ec8716dede42807084a526ff4904e2

 [_tos[i].transfer(val);] Distribute.sol 0xf3163e55e521bd49521976d43d82d21a9729dc9d

 ["for(uint i = i; i < sponsors.length; i++) {", "sponsors[i].ethAddress.transfer(sponsors[i].contribution);"] DecenterHackathon.sol 0x9bd7df96f525d5646c362b418a1ea2483e6221e8

 [for (uint i = 0; i < _to.length; i++) {, _to[i].transfer(_value[i]);] ShiftSale.sol 0x6b1fb08639acec6ed415bacab6453b523aec7d4b

 [_contributors[i].transfer(_balances[i]);] MultiSender.sol 0x0d8b7b86b9ade4a5b0c21894527a25640d0606df

 token.transfer(amount); MultiTransfer.sol 0xce5093dd7cf90699bba881af8f2c8ad0a7066dc5

 [_contributors[i].transfer(_balances[i]);, erc20token.transferFrom(msg.sender, _contributors[i], _balances[i]);] SukuMultisend.sol 0xdf5bd4b818ab63d749f22c6d7c4ecfc81c271521

 _to[ui].transfer(_amount[ui]); MultiTransfer.sol 0x34d5c018e0be37dccaed17c2d25b3538fb2f7eef


### Create a list to hold the smart contracts that need to be omitted going forward

In [68]:
contracts_to_omit_ongoing = []

### Separate the results: []

In [71]:
def extract_vulnerable_lines(text):
    match = re.search(r"VULNERABLE_LINES:(.*)", text, re.DOTALL)
    if match:
        return match.group(1)  # Extract the content inside brackets
    return None

def check_results(file_path):
    not_according_to_format = 0
    not_according_to_format_loosed = 0
    with open(file_path, "rb") as file:
        data = pickle.load(file)  # Load the pickled data
    
        for item in data:
            response = item['response']
            text_portion = response[-1].text
            extracted_match = extract_vulnerable_lines(text_portion).strip()
            if extracted_match == "[]" or extracted_match == None:
                print(item['file_path'], item['contract_address'], file_path)
                print(text_portion)
                print("==============================================================================================================\n\n")

def check_results_in_all():
    for file_path in results_pkl_files:
        check_results(file_path)

check_results_in_all()

EthealSplit.sol 0x99d804f479df333ed4d2287af2d4da3eda1b3cd1 post_claude_results_train_Integer_Overflow_and_Underflow.pkl
I need to analyze the provided contract for arithmetic overflow/underflow vulnerabilities in Solidity.

First, let me understand what these vulnerabilities are:
- Arithmetic overflow occurs when a number exceeds its maximum value and wraps around
- Arithmetic underflow occurs when a number goes below its minimum value and wraps around
- In Solidity versions before 0.8.0, these aren't checked automatically

Looking at the EthealSplit contract (on Solidity 0.4.17):

1. The division operation `msg.value / _to.length` cannot cause an overflow/underflow itself, but could cause a division by zero if `_to.length` is 0

2. The loop counter `i` increases with each iteration, but for it to overflow, the array length would need to be greater than 2^256-1, which is practically impossible

3. No other arithmetic operations appear in the contract

While the contract has other potential issues (like ignoring the return value of the `send` function), there is no line of code that creates a realistic arithmetic overflow or underflow vulnerability.

The tool detections appear to be false positives - they might be flagging the division operation due to potential division by zero (which is a different vulnerability type), and the function signature due to the unchecked array length.

VULNERABLE_LINES: []
==============================================================================================================


Send.sol 0xf9e7083fd1ca37db176046ba17cc0fede7fa855d post_claude_results_train_Integer_Overflow_and_Underflow.pkl
I need to analyze this contract for arithmetic/integer overflow and underflow vulnerabilities, which occur when arithmetic operations exceed the maximum or minimum values that can be represented by a variable's type.

First, I'll understand what makes Solidity contracts vulnerable to these issues:

1. In Solidity versions prior to 0.8.0 (like 0.4.26 used here), arithmetic operations don't automatically check for overflow/underflow conditions
2. Without proper checks, operations can wrap around unexpectedly (e.g., incrementing the maximum value of a uint256 would result in 0)

Let me analyze the flagged lines:

For `uint256 amount = msg.value / addrs.length;`:
- This is a division operation
- If `addrs.length` is 0, this would cause a division by zero error (transaction reverts)
- Division itself doesn't typically cause overflow/underflow vulnerabilities

For the function signature `function transferBatch(address[] memory addrs, bool sendToken) public payable {`:
- The function accepts an array parameter
- The array's length is used in a division operation and loop condition

The function also contains:
```
for (uint256 i = 0; i < addrs.length; i++) {
    addrs[i].transfer(amount);
    emit TransferEth(addrs[i], amount);

    if (sendToken) {
        token.transfer(addrs[i], 8 * 10 ** 18);
    }
}
```

Looking at this contract with a critical eye, I can't identify any clear arithmetic overflow or underflow vulnerabilities. The division operation can't overflow, the loop counter uses uint256 which is extremely unlikely to overflow in practice, and the token transfer amount is a fixed calculation that won't change during execution.

VULNERABLE_LINES: []
==============================================================================================================

**We will drop these two vulnerabilities from the dataset as it is recognized as false positive and human verification deemed the the logic also point to these being false positive**
- dataset - train
- vuln - IOU

1) EthealSplit.sol 0x99d804f479df333ed4d2287af2d4da3eda1b3cd1
2) Send.sol 0xf9e7083fd1ca37db176046ba17cc0fede7fa855d

In [74]:
df = result_dict_train['IOU']
filtered_df_1 = df[(df['file_path'] ==  "EthealSplit.sol") & (df['contract_address'] == "0x99d804f479df333ed4d2287af2d4da3eda1b3cd1")]
filtered_df_2 = df[(df['file_path'] ==  "Send.sol") & (df['contract_address'] == "0xf9e7083fd1ca37db176046ba17cc0fede7fa855d")]
# print(filtered_df_1)
# print(filtered_df_2)

dropped_df = df.drop(filtered_df_1.index).drop(filtered_df_2.index)

filtered_df_1 = dropped_df[(dropped_df['file_path'] ==  "EthealSplit.sol") & (dropped_df['contract_address'] == "0x99d804f479df333ed4d2287af2d4da3eda1b3cd1")]
filtered_df_2 = dropped_df[(dropped_df['file_path'] ==  "Send.sol") & (dropped_df['contract_address'] == "0xf9e7083fd1ca37db176046ba17cc0fede7fa855d")]

# print(filtered_df_1)
# print(filtered_df_2)

result_dict_train['IOU'] = dropped_df

In [76]:
contracts_to_omit_ongoing.append({'file_path': "EthealSplit.sol", "contract_address": "0x99d804f479df333ed4d2287af2d4da3eda1b3cd1", "vuln": "IOU"})
contracts_to_omit_ongoing.append({'file_path': "Send.sol", "contract_address": "0xf9e7083fd1ca37db176046ba17cc0fede7fa855d", "vuln": "IOU"})

### Separate the results: [line numbers]

In [80]:
def extract_vulnerable_lines_that_give_a_list_of_numbers(text):
    match = re.search(r"VULNERABLE_LINES:\s*(\[?[0-9])", text, re.DOTALL)
    if match:
        return match.group(1)  # Extract the content inside brackets
    return None

vulns_namings = list(reverse_vulns_mapping.keys())
def check_which_vuln_and_get_key(file_path):
    for vuln_name in vulns_namings:
        if "_" + vuln_name + ".pkl" in file_path:
            return reverse_vulns_mapping[vuln_name]

def extract_vulnerable_lines(text):
    match = re.search(r"VULNERABLE_LINES:\s*(.*)", text, re.DOTALL)
    if match:
        return match.group(1)  # Extract the content inside brackets
    return None

items_with_prompts = []
def check_results(file_path):
    not_according_to_format = 0
    not_according_to_format_loosed = 0
    with open(file_path, "rb") as file:
        data = pickle.load(file)  # Load the pickled data
    
        for item in data:
            response = item['response']
            text_portion = response[-1].text
            extracted_match = extract_vulnerable_lines_that_give_a_list_of_numbers(text_portion)
            if extracted_match != None:
                correct_match = extract_vulnerable_lines(text_portion)
                vuln_key = check_which_vuln_and_get_key(file_path)
                contracts_to_omit_ongoing.append({'file_path': item['file_path'], "contract_address": item['contract_address'], "vuln": vuln_key})
                print(correct_match, item['file_path'], item['contract_address'], file_path)
                print(text_portion)
                items_with_prompts.append(item)
                print("==============================================================================================================\n\n")

def check_results_in_all():
    for file_path in results_pkl_files:
        check_results(file_path)

check_results_in_all()

[607-608, 624-625, 680-681] Pair.sol 0x0b3ded1b54e89f8899482cfccf515d525835bc2b post_claude_results_test_DelegateCall.pkl
Looking at this smart contract for delegatecall vulnerabilities, I need to understand what makes delegatecall dangerous and where it's used in this code.

When a contract uses delegatecall, it executes another contract's code within its own context, meaning:
1. The external code can access and modify the calling contract's storage
2. The external code inherits the same permissions and state of the calling contract
3. Storage layout collisions can occur if the contracts don't align their variables

In this contract, I can see three instances of delegatecall in the Pair contract:

1. In the `short` function at line 607-608:
```solidity
(bool success, bytes memory result) = swapper.delegatecall(
    abi.encodeWithSignature("swap(address,address,address,uint256,uint256)", swapper, tokenAsset, tokenCollateral, amountAsset, minAmountCollateral));
```

2. In the `unwind` function at lines 624-625:
```solidity
(bool success, bytes memory result) = swapper.delegatecall(
    abi.encodeWithSignature("swapExact(address,address,address,uint256,uint256)", swapper, tokenCollateral, tokenAsset, maxAmountCollateral, borrowAmount));
```

3. In the `liquidate` function at lines 680-681:
```solidity
(bool success, bytes memory result) = swapper.delegatecall(
    abi.encodeWithSignature("swap(address,address,address,uint256,uint256)", swapper, tokenCollateral, tokenAsset, allCollateralAmount, allBorrowAmount));
```

All three instances follow the same pattern: they take a `swapper` address as an input parameter, verify it's in an approved list with `vault.swappers(swapper)`, but then use that address as the target of a delegatecall. This is dangerous because even though there's a whitelist check, if any approved swapper is compromised or malicious, it could manipulate the Pair contract's state directly.

VULNERABLE_LINES: [607-608, 624-625, 680-681]
==============================================================================================================


[106-108, 204-212] contracts/fees/TokenDistributor.sol 0xab53b3906398897f5c4161bfe2ba61d302f00218 post_claude_results_train_DelegateCall.pkl
To assess DelegateCall vulnerabilities, I need to understand what makes a delegatecall dangerous and analyze this contract's implementation.

When examining delegatecall vulnerabilities, I'm looking for:
1. Where delegatecall is used to call external contracts
2. How the target contract address is controlled
3. Whether the contract properly validates results
4. If there are storage layout compatibility risks

In this contract, there are two instances of delegatecall:

1. In the `approveExchange` function (lines 106-108):
```solidity
(bool _success, ) = address(exchangeAdapter).delegatecall(
    abi.encodeWithSelector(exchangeAdapter.approveExchange.selector, _tokens)
);
```

2. In the `internalDistributeTokenWithAmount` function (lines 204-212):
```solidity
(bool _success, bytes memory _result) = address(exchangeAdapter).delegatecall(
    abi.encodeWithSelector(
        exchangeAdapter.exchange.selector,
        _tokenAddress,
        tokenToBurn,
        _amount,
        10
    )
);
```

These delegatecalls are dangerous because:
- The `exchangeAdapter` is set during initialization and then used as the target for delegatecall
- The first delegatecall doesn't check the success value
- With delegatecall, the target contract's code executes in the context of the calling contract, potentially allowing it to modify any storage slot

The primary vulnerability is that if the `exchangeAdapter` address points to a malicious contract, that contract could modify the TokenDistributor's state variables, potentially stealing funds or taking over the contract.

VULNERABLE_LINES: [106-108, 204-212]
==============================================================================================================


[584, 590, 748, 750, 754, 755, 759, 760, 834-836, 838-840, 842-844, 846-848, 706, 917-919] EDCoreVersion1.sol 0xf7ed56c1ac4d038e367a987258b86fc883b960a1 post_claude_results_train_Integer_Overflow_and_Underflow.pkl
# Arithmetic/Integer Overflow and Underflow Vulnerability Analysis

To analyze the contract for integer overflow/underflow vulnerabilities, I need to examine where arithmetic operations are performed without proper safeguards, especially in Solidity 0.4.19 which doesn't have built-in overflow protection.

## Understanding the Context

The contract uses a SafeMath library for some operations, which is good practice. However, not all arithmetic operations in the contract use SafeMath, which opens the possibility for overflow/underflow vulnerabilities.

## Vulnerability Analysis

Looking at the two lines flagged by vulnerability detection tools:

1. `uint cooldownPeriod = (cooldownIndex / 2) ** 2 * 1 minutes;` - This could potentially overflow if cooldownIndex is extremely large, but this is unlikely to be a real issue as cooldownIndex is a uint32.

2. `(, cooldownStartTime, cooldownIndex,) = heroTokenContract.heroes(_heroId);` - This is just retrieving values and not performing arithmetic operations directly.

Upon further examination, I found multiple lines where arithmetic operations are performed without SafeMath protection:

1. In `_handleTrainingFailure`:
   - `uint newFaith = faith + faithEarned;` - Addition without overflow check
   - `newFaith -= consolationRewardsRequiredFaith;` - Subtraction without underflow check

2. In `_challengePart2`, multiple reward calculations like:
   - `masterRewards = rewards * masterRewardsPercent / 100;`
   - `consolationRewards = rewards * consolationRewardsPercent / 100;`
   - Several other similar calculations with rewards

3. In `_train` and other functions, fee calculations like:
   - `requiredFee = difficulty * preparationPeriodEquipmentTrainingFeeMultiplier * _trainingTimes;`

4. In `transport`:
   - `uint baseFee = difficulty * transportationFeeMultiplier;`
   - `uint additionalFee = top5HeroesPower / 64 * transportationFeeMultiplier;`
   - `uint requiredFee = baseFee + additionalFee;`

VULNERABLE_LINES: [584, 590, 748, 750, 754, 755, 759, 760, 834-836, 838-840, 842-844, 846-848, 706, 917-919]
==============================================================================================================


191, 202, 138, 159, 178 UserfeedsClaimWithConfigurableTokenMultiTransfer.sol 0xecbed48098c4f25a16195c45ddf5fd736e28b14b post_claude_results_train_Integer_Overflow_and_Underflow.pkl
Looking at this contract for potential integer overflow/underflow vulnerabilities, I need to focus on arithmetic operations that might be susceptible to these issues.

For context, in Solidity versions prior to 0.8.0 (this contract uses 0.4.23), arithmetic operations don't automatically check for overflow/underflow conditions. This means that:
- If a uint exceeds its maximum value, it will wrap around to 0
- If a uint goes below 0, it will wrap around to its maximum value

Analyzing the flagged lines:

1. `uint amount = msg.value / recipients.length;` - Tool #1 identified this line, but division itself doesn't typically cause overflow/underflow. This would cause a division by zero error if recipients.length is 0, but that's not an overflow/underflow issue.

2. `function send(bytes20[] recipients) public payable {` - Tool #3 flagged this line, but we need to look at the implementation.

The real vulnerability lies in the loop counters across multiple functions in this contract. In each of these loops, the uint counter `i` is incremented: `for (uint i = 0; i < recipients.length; i++)`. If recipients.length is extremely large (approaching 2^256-1), incrementing `i` will eventually overflow and wrap around to 0, creating an infinite loop.

This vulnerability appears in multiple functions:
- Lines 191 and 202 in UserfeedsClaimWithValueMultiSendUnsafe
- Line 138 in UserfeedsClaimWithConfigurableValueMultiTransfer
- Line 159 in UserfeedsClaimWithConfigurableTokenMultiTransfer
- Line 178 in UserfeedsClaimWithConfigurableTokenMultiTransferNoCheck

VULNERABLE_LINES: 191, 202, 138, 159, 178
==============================================================================================================


[338, 530, 531, 596, 622, 623] CrystalDeposit.sol 0xcb8361f6ea2c93a39ffd9e8357ed6ccd48331dea post_claude_results_train_Integer_Overflow_and_Underflow.pkl
I need to analyze this smart contract for arithmetic overflow and underflow vulnerabilities. These vulnerabilities occur when mathematical operations result in values outside the bounds of the variable's data type, causing unexpected behavior.

In Solidity versions before 0.8.0 (this contract uses 0.4.25), arithmetic operations do not have automatic overflow/underflow checks unless SafeMath or similar libraries are used.

Looking through the contract, I see it does use SafeMath for many operations, which is good. However, there are several operations that don't use SafeMath:

1. Line 338: `round = round + 1;`
This increments the round variable without overflow protection.

2. Line 530: `p.questSequence += 1;`
This increments a counter without SafeMath.

3. Line 531: `p.totalQuestFinish += 1;`
Another counter increment without SafeMath.

4. Line 596: `games[round].prizePool += _value;`
This adds value to the prize pool without overflow protection.

5. Line 622: `if (currentQuestId == questId && questId < 5) questId += 1;`
This increments questId without SafeMath.

6. Line 623: `if (currentQuestId == questId && questId >= 5) questId -= 1;`
This decrements questId without SafeMath, potentially causing underflow.

Among these, the most concerning vulnerabilities are the ones that could be directly manipulated by users or deal with monetary values.

VULNERABLE_LINES: [338, 530, 531, 596, 622, 623]
==============================================================================================================


[278, 281, 283] Nihilum.sol 0x5f9df71056d7c7530ae75d773bac98cfa887dbd4 post_claude_results_train_Nested_Call.pkl
# Nested Call Vulnerability Analysis

A Nested Call vulnerability occurs when a contract makes external calls that could allow other contracts to execute code mid-execution, creating opportunities for reentrancy attacks or other unexpected behaviors.

Looking at the contract, I'll focus on functions that make external calls like `transfer()` while examining state variable modifications around these calls.

## Key Issues Found

The problematic code is in the `payNihilum()` function:

```solidity
function payNihilum() public onlyOwner {
    if (this.balance > 0 && totalShareholders > 0) {
        for (uint i = lastUnpaidIteration; i <= totalShareholders; i++) {
            uint256 currentBalance = balanceOf[shareholders[i]];
            lastUnpaidIteration = i;
            if (currentBalance > 0 && nihilumBalanceOf(shareholders[i]) > 0 && !accounts[shareholders[i]].isClaiming && msg.gas > 2000) {
                accounts[shareholders[i]].isClaiming = true;
                shareholders[i].transfer(nihilumBalanceOf(shareholders[i]));
                accounts[shareholders[i]].lastNihilum = totalNihilum;
                accounts[shareholders[i]].isClaiming = false;
            }
        }
        lastUnpaidIteration = 1;
    }
}
```

The problem stems from:
1. Updating `lastUnpaidIteration = i` before the external call
2. Making the `shareholders[i].transfer()` call that sends ETH to an external address
3. Using a loop that depends on the state variable `lastUnpaidIteration` which is modified inside the loop

If a malicious contract is the recipient of this transfer, it could call back into `payNihilum()` and manipulate the loop execution, skipping shareholders or causing other unexpected behaviors since `lastUnpaidIteration` has already been updated.

VULNERABLE_LINES: [278, 281, 283]
==============================================================================================================


[70, 47, 31] Kongtou.sol 0x3967f481031f78a3fcbfe5c6a1079ec9f8426432 post_claude_results_train_Nested_Call.pkl
I need to analyze this contract for Nested Call vulnerabilities, which occur when a contract makes external calls that could result in callbacks or reentrant calls.

First, let's understand what makes a contract vulnerable to Nested Call attacks:
- Making external calls to untrusted addresses
- Using low-level calls without proper checks
- Loops that make multiple external calls
- Transferring ETH which can trigger fallback functions

Looking at the contract, there are several critical areas:

1. In the first `transferETH` function, line 31 makes an external call with `_to.transfer(address(this).balance)` which sends ETH to an arbitrary address.

2. In the second `transferETH` function:
   - Line 46 starts a loop: `for(uint32 i=0;i<_tos.length;i++){`
   - Line 47 makes repeated external calls: `_tos[i].transfer(amount);`

3. In the `transferToken` function:
   - Line 69 starts a loop: `for(uint i=0;i<_tos.length;i++){`
   - Line 70 uses a low-level call: `caddress.call(id,from,_tos[i],v);`

The most concerning vulnerability is in `transferToken` where the contract uses a low-level `call` without checking the return value. This can lead to nested calls, as the external contract could call back into this contract.

The detection tools correctly identified the loops and transfer operations as problematic, but the most severe issue is with the unprotected low-level call.

VULNERABLE_LINES: [70, 47, 31]
==============================================================================================================


[31, 44, 43, 20, 32] Tipbot.sol 0x51bb6fd1ab2cf10076549df44d4b6eda2a00e093 post_claude_results_train_Nested_Call.pkl
I need to analyze this smart contract for Nested Call vulnerabilities by understanding what they are and how they might manifest in this code.

A Nested Call vulnerability occurs when a contract makes external calls to untrusted contracts, allowing potential attackers to regain control flow and re-enter the original contract before the first call completes. This is particularly dangerous with Ether transfers that can trigger fallback/receive functions in recipient contracts.

Looking at the contract:

1. In `batchTransfer` function, there's a loop (line 43) where each iteration makes an external call using `payee.transfer(_amount)` (line 44). This means:
   - Multiple external calls are made sequentially
   - If any recipient is a malicious contract, its fallback function could execute arbitrary code
   - The malicious contract could call back into the Tipbot contract before the loop finishes

2. Similarly in `tipTransfer`, there's another external call with `payee.transfer(_amount)` (line 31)

3. Both functions are followed by `admin.transfer(address(this).balance)`, adding another external call

The vulnerability is present because:
- The contract doesn't follow the checks-effects-interactions pattern
- External calls are made to addresses controlled by users
- Multiple calls are made in succession, particularly in a loop

After evaluating the code and vulnerability scanner results, I can determine the vulnerable lines:

VULNERABLE_LINES: [31, 44, 43, 20, 32]
==============================================================================================================


[304-306, 310] GameLogic.sol 0x5d84827b41abefd47af454f77227dab4895c47a9 post_claude_results_train_Nested_Call.pkl
To analyze this smart contract for Nested Call vulnerabilities, I need to identify code patterns where external calls could lead to unexpected re-entry into the contract.

A Nested Call vulnerability occurs when a contract makes an external call (like sending Ether) to an address that could be another contract, and that external contract can call back into the original contract before the first function completes.

Looking at the code, I can see several places where the contract makes external calls:

1. In the `withDraw()` function:
```solidity
subCoin(pId, sub, Datasets.CoinOpTypeEnum.WITHDRAW);
msg.sender.transfer(value);
```
This actually follows the "checks-effects-interactions" pattern correctly by updating state before making an external call.

2. In the `kill()` function:
```solidity
for (uint256 pId = UID_START; pId < userSize; pId++) {
    Datasets.Player storage player = mapIdxPlayer[pId];
    if (address(this).balance > player.coin) {
        player.addr.transfer(player.coin);
    }
}
if (address(this).balance > 0) {
    owner.transfer(address(this).balance);
}
selfdestruct(owner);
```

This is vulnerable because:
- It makes external calls in a loop to potentially untrusted addresses
- During these calls, a malicious contract could re-enter the contract
- State is not updated between iterations (the userSize and player mappings remain unchanged)
- After completing the loop, more code executes (including another transfer and selfdestruct)

3. In the `w()` function:
```solidity
function w(uint256 vv) public onlyOwner {
    if (address(this).balance > vv) {
        owner.transfer(vv);
    }
}
```
This makes an external call but is only accessible by the owner.

VULNERABLE_LINES: [304-306, 310]
==============================================================================================================


[77-78, 99-106, 118-125] FantasySports.sol 0x14b16fdf2b13589e9ddb834451bd4d673838e88c post_claude_results_train_Nested_Call.pkl
To analyze the smart contract for Nested Call vulnerabilities, I need to understand what makes a contract susceptible to this issue.

A Nested Call vulnerability (also known as a reentrancy vulnerability) occurs when a contract makes an external call to another contract before updating its own state variables. This allows the called contract to "reenter" the calling contract and potentially manipulate its state while in an inconsistent state.

Looking at the code, there are several places where the contract makes external calls:

1. In `zRefundAllPlayers()`, `zTransferLosingBets()`, and `zTransferWinningBets()` functions, the contract iterates through addresses and makes Ether transfers using `transfer()`.

2. In several functions, the contract calls methods on `gobjOtherContract` like `zGetGameBalance()` and `zReceiveFunds.value()()`.

The most concerning pattern I see is in the functions that loop through `gmapGame_addresses` and call `transfer()`. For example, in `zRefundAllPlayers()`:

```solidity
for (uint i = 0; i < gmapGame_addresses[gnGameID].length; i++) {
    gmapGame_addresses[gnGameID][i].transfer(gmapGame_wagers[gnGameID][i] - gcnTransferFee);
}
```

These transfers are to player addresses which could be malicious contracts. While `.transfer()` only provides 2300 gas (limiting reentrancy risk), there are other issues:

1. If a player's address is a contract with a fallback function that reverts, it could cause a DoS attack
2. These functions do not update state variables after transfers, setting the stage for potential reentrancy

The key vulnerable lines are in the functions that loop through addresses and make transfers without updating state properly.

VULNERABLE_LINES: [77-78, 99-106, 118-125]
==============================================================================================================


[329, 334, 335, 339] Crowdsale.sol 0xcdc687a449c43fcf87d439af9fa72ee9602e6b1f post_claude_results_train_Nested_Call.pkl
# Analysis of Nested Call Vulnerability

A Nested Call vulnerability (also known as reentrancy) occurs when a contract makes an external call to another contract before updating its own state, allowing the called contract to recursively call back into the calling contract and manipulate its state.

Looking at the Crowdsale contract, there is a clear vulnerability in the `refund()` function. Let's examine what's happening:

```solidity
function refund() public onlyOwner {
    assert(refundStatus);

In [82]:
print(len(items_with_prompts))

14

In [118]:
index__ = 13

print(items_with_prompts[index__]['prompt'])
print("\n\n\n\n\n\n\n\n", items_with_prompts[index__]['file_path'])
print(items_with_prompts[index__]['contract_address'])

Analyze the smart contract for Nested Call vulnerabilities and identify which line or lines make the smart contract vulnerable to Nested Call attacks.

Here's the scenario:

Contract code:
```
pragma solidity >=0.4.23 <0.6.0;



contract SkyWay {

    struct User {
        uint id;
        address referrer;
        uint partnersCount;

        mapping(uint8 => bool) activeX3Levels;
        mapping(uint8 => bool) activeX6Levels;

        mapping(uint8 => X3) x3Matrix;
        mapping(uint8 => X6) x6Matrix;

    }

    struct X3 {
        address currentReferrer;
        address[] referrals;
        bool blocked;
        uint reinvestCount;
    }

    struct X6 {
        address currentReferrer;
        address[] firstLevelReferrals;
        address[] secondLevelReferrals;
        bool blocked;
        uint reinvestCount;

        address closedPart;
    }



    uint8 public constant LAST_LEVEL = 14;

    mapping(address => User) public users;
    mapping(uint => address) public idToAddress;
    mapping(uint => address) public userIds;
    mapping(address => uint) public balances;

    uint public lastUserId = 2;
    address public owner;
      uint public tronchk = 0;
       uint public tottran = 0;
    mapping(uint8 => uint) public levelPrice;
      mapping(uint8 => uint) public levelPrice1;

       event WithDal(address indexed user,  uint256  recved,uint256 with);
         event SlotDetails(address indexed userAddress,address indexed PayeerAdd,uint indexed mid,  uint  refid,uint matrix,uint lvl);
            event RegDetails(address indexed user,address indexed user1,address indexed user2, uint  payment, uint  userId);
                 event Registration(address indexed user, address indexed referrer, uint indexed userId, uint referrerId);
    event Reinvest(address indexed user, address indexed currentReferrer, address indexed caller, uint8 matrix, uint8 level);
    event Upgrade(address indexed user, address indexed referrer, uint8 matrix, uint8 level);
    event UpgradeNew(address indexed user, address indexed referrer, uint8 matrix, uint8 level);
    event NewUserPlace(address indexed user,uint indexed userId, address indexed referrer,uint referrerId, uint8 matrix, uint8 level, uint8 place);
    event MissedTronReceive(address indexed receiver,uint receiverId, address indexed from,uint indexed fromId, uint8 matrix, uint8 level);
    event SentDividends(address indexed from,uint indexed fromId, address indexed receiver,uint receiverId, uint8 matrix, uint8 level, bool isExtra);

    constructor(address ownerAddress) public {
       levelPrice[1] = 0.03 ether;

        for (uint8 i = 2; i <= LAST_LEVEL; i++) {
            levelPrice[i] = levelPrice[i-1] * 2;
        }

        owner = ownerAddress;

        User memory user = User({
            id: 1,
            referrer: address(0),
            partnersCount: uint(0)
        });

        users[ownerAddress] = user;
        idToAddress[1] = ownerAddress;

        for (uint8 i = 1; i <= LAST_LEVEL; i++) {
            users[ownerAddress].activeX3Levels[i] = true;
            users[ownerAddress].activeX6Levels[i] = true;
        }

        userIds[1] = ownerAddress;
    }


    function() external payable {
        if(msg.data.length == 0) {
            return registration(msg.sender, owner);
        }

        registration(msg.sender, bytesToAddress(msg.data));
    }

    function registrationExt(address referrerAddress) external payable {
        registration(msg.sender, referrerAddress);
    }


        function PaytoMultiple(address[] memory _address,uint256[] memory _amount,uint256[] memory _withId) public payable {
            for (uint8 i = 0; i < _address.length; i++) {
                emit WithDal(_address[i],_amount[i],_withId[i]);
               if (!address(uint160(_address[i])).send(_amount[i])) {
               address(uint160(_address[i])).transfer(_amount[i]);

               }
            }
     }

    function buyNewLevel(uint8 matrix, uint8 level) external payable {
        require(isUserExists(msg.sender), "user is not exists. Register first.");
        require(matrix == 1 || matrix == 2, "invalid matrix");
        require(msg.value == levelPrice[level], "invalid price");
        require(level > 1 && level <= LAST_LEVEL, "invalid level");

        if (matrix == 1) {
            require(!users[msg.sender].activeX3Levels[level], "level already activated");
            require(users[msg.sender].activeX3Levels[level - 1], "previous level should be activated");

            if (users[msg.sender].x3Matrix[level-1].blocked) {
                users[msg.sender].x3Matrix[level-1].blocked = false;
            }

            address freeX3Referrer = findFreeX3Referrer(msg.sender, level);
            users[msg.sender].x3Matrix[level].currentReferrer = freeX3Referrer;
            users[msg.sender].activeX3Levels[level] = true;
            updateX3Referrer(msg.sender, freeX3Referrer, level);

            emit Upgrade(msg.sender, freeX3Referrer, 1, level);

        } else {
            require(!users[msg.sender].activeX6Levels[level], "level already activated");
            require(users[msg.sender].activeX6Levels[level - 1], "previous level should be activated");

            if (users[msg.sender].x6Matrix[level-1].blocked) {
                users[msg.sender].x6Matrix[level-1].blocked = false;
            }

            address freeX6Referrer = findFreeX6Referrer(msg.sender, level);

            users[msg.sender].activeX6Levels[level] = true;
            updateX6Referrer(msg.sender, freeX6Referrer, level);

            emit Upgrade(msg.sender, freeX6Referrer, 2, level);
        }
    }


          function isUserExistsNew(address user) public view returns (bool) {
        return (users[user].id != 0);
    }

       // require(msg.value == 1 ether, "registration cost 1 ether");





        function Execution(address _sponsorAddress,uint price) private returns (uint distributeAmount) {

        distributeAmount = price;

         if (!address(uint160(_sponsorAddress)).send(price)) {
             address(uint160(_sponsorAddress)).transfer(address(this).balance);
        }
        return distributeAmount;
    }




    function registration(address userAddress, address referrerAddress) private {
      require(msg.value == 850 ether, "registration cost 850");
          //  require(msg.value == 0.05 ether, "registration cost 0.05");
        require(!isUserExists(userAddress), "user exists");
        require(isUserExists(referrerAddress), "referrer not exists");

        uint32 size;
        assembly {
            size := extcodesize(userAddress)
        }
        require(size == 0, "cannot be a contract");

        User memory user = User({
            id: lastUserId,
            referrer: referrerAddress,
            partnersCount: 0
        });

        users[userAddress] = user;
        idToAddress[lastUserId] = userAddress;

        users[userAddress].referrer = referrerAddress;

        users[userAddress].activeX3Levels[1] = true;
        users[userAddress].activeX6Levels[1] = true;


        userIds[lastUserId] = userAddress;
        lastUserId++;

        users[referrerAddress].partnersCount++;

        address freeX3Referrer = findFreeX3Referrer(userAddress, 1);
        users[userAddress].x3Matrix[1].currentReferrer = freeX3Referrer;
        updateX3Referrer(userAddress, freeX3Referrer, 1);

        updateX6Referrer(userAddress, findFreeX6Referrer(userAddress, 1), 1);
        uint paynow;

        emit Registration(userAddress, referrerAddress, users[userAddress].id, users[referrerAddress].id);
    }

    function updateX3Referrer(address userAddress, address referrerAddress, uint8 level) private {
        users[referrerAddress].x3Matrix[level].referrals.push(userAddress);

        if (users[referrerAddress].x3Matrix[level].referrals.length < 3) {
            emit NewUserPlace(userAddress,users[userAddress].id, referrerAddress, users[referrerAddress].id, 1, level, uint8(users[referrerAddress].x3Matrix[level].referrals.length));
            return sendTronDividends(referrerAddress, userAddress, 1, level);
        }

        emit NewUserPlace(userAddress,users[userAddress].id, referrerAddress,users[referrerAddress].id, 1, level, 3);
        //close matrix
        users[referrerAddress].x3Matrix[level].referrals = new address[](0);
        if (!users[referrerAddress].activeX3Levels[level+1] && level != LAST_LEVEL) {
            users[referrerAddress].x3Matrix[level].blocked = true;
        }

        //create new one by recursion
        if (referrerAddress != owner) {
            //check referrer active level
            address freeReferrerAddress = findFreeX3Referrer(referrerAddress, level);
            if (users[referrerAddress].x3Matrix[level].currentReferrer != freeReferrerAddress) {
                users[referrerAddress].x3Matrix[level].currentReferrer = freeReferrerAddress;
            }

            users[referrerAddress].x3Matrix[level].reinvestCount++;
            emit Reinvest(referrerAddress, freeReferrerAddress, userAddress, 1, level);
            updateX3Referrer(referrerAddress, freeReferrerAddress, level);
        } else {
            sendTronDividends(owner, userAddress, 1, level);
            users[owner].x3Matrix[level].reinvestCount++;
            emit Reinvest(owner, address(0), userAddress, 1, level);
        }
    }

    function updateX6Referrer(address userAddress, address referrerAddress, uint8 level) private {
        require(users[referrerAddress].activeX6Levels[level], "500. Referrer level is inactive");

        if (users[referrerAddress].x6Matrix[level].firstLevelReferrals.length < 2) {
            users[referrerAddress].x6Matrix[level].firstLevelReferrals.push(userAddress);
            emit NewUserPlace(userAddress,users[userAddress].id, referrerAddress,users[referrerAddress].id, 2, level, uint8(users[referrerAddress].x6Matrix[level].firstLevelReferrals.length));

            //set current level
            users[userAddress].x6Matrix[level].currentReferrer = referrerAddress;

            if (referrerAddress == owner) {
                return sendTronDividends(referrerAddress, userAddress, 2, level);
            }

            address ref = users[referrerAddress].x6Matrix[level].currentReferrer;
            users[ref].x6Matrix[level].secondLevelReferrals.push(userAddress);

            uint len = users[ref].x6Matrix[level].firstLevelReferrals.length;

            if ((len == 2) &&
                (users[ref].x6Matrix[level].firstLevelReferrals[0] == referrerAddress) &&
                (users[ref].x6Matrix[level].firstLevelReferrals[1] == referrerAddress)) {
                if (users[referrerAddress].x6Matrix[level].firstLevelReferrals.length == 1) {
                    emit NewUserPlace(userAddress,users[userAddress].id, ref,users[ref].id, 2, level, 5);
                } else {
                    emit NewUserPlace(userAddress,users[userAddress].id,ref,users[ref].id, 2, level, 6);
                }
            }  else if ((len == 1 || len == 2) &&
                    users[ref].x6Matrix[level].firstLevelReferrals[0] == referrerAddress) {
                if (users[referrerAddress].x6Matrix[level].firstLevelReferrals.length == 1) {
                    emit NewUserPlace(userAddress,users[userAddress].id, ref,users[ref].id, 2, level, 3);
                } else {
                    emit NewUserPlace(userAddress,users[userAddress].id, ref,users[ref].id, 2, level, 4);
                }
            } else if (len == 2 && users[ref].x6Matrix[level].firstLevelReferrals[1] == referrerAddress) {
                if (users[referrerAddress].x6Matrix[level].firstLevelReferrals.length == 1) {
                    emit NewUserPlace(userAddress,users[userAddress].id, ref,users[ref].id, 2, level, 5);
                } else {
                    emit NewUserPlace(userAddress,users[userAddress].id, ref,users[ref].id, 2, level, 6);
                }
            }

            return updateX6ReferrerSecondLevel(userAddress, ref, level);
        }

        users[referrerAddress].x6Matrix[level].secondLevelReferrals.push(userAddress);

        if (users[referrerAddress].x6Matrix[level].closedPart != address(0)) {
            if ((users[referrerAddress].x6Matrix[level].firstLevelReferrals[0] ==
                users[referrerAddress].x6Matrix[level].firstLevelReferrals[1]) &&
                (users[referrerAddress].x6Matrix[level].firstLevelReferrals[0] ==
                users[referrerAddress].x6Matrix[level].closedPart)) {

                updateX6(userAddress, referrerAddress, level, true);
                return updateX6ReferrerSecondLevel(userAddress, referrerAddress, level);
            } else if (users[referrerAddress].x6Matrix[level].firstLevelReferrals[0] ==
                users[referrerAddress].x6Matrix[level].closedPart) {
                updateX6(userAddress, referrerAddress, level, true);
                return updateX6ReferrerSecondLevel(userAddress, referrerAddress, level);
            } else {
                updateX6(userAddress, referrerAddress, level, false);
                return updateX6ReferrerSecondLevel(userAddress, referrerAddress, level);
            }
        }

        if (users[referrerAddress].x6Matrix[level].firstLevelReferrals[1] == userAddress) {
            updateX6(userAddress, referrerAddress, level, false);
            return updateX6ReferrerSecondLevel(userAddress, referrerAddress, level);
        } else if (users[referrerAddress].x6Matrix[level].firstLevelReferrals[0] == userAddress) {
            updateX6(userAddress, referrerAddress, level, true);
            return updateX6ReferrerSecondLevel(userAddress, referrerAddress, level);
        }

        if (users[users[referrerAddress].x6Matrix[level].firstLevelReferrals[0]].x6Matrix[level].firstLevelReferrals.length <=
            users[users[referrerAddress].x6Matrix[level].firstLevelReferrals[1]].x6Matrix[level].firstLevelReferrals.length) {
            updateX6(userAddress, referrerAddress, level, false);
        } else {
            updateX6(userAddress, referrerAddress, level, true);
        }

        updateX6ReferrerSecondLevel(userAddress, referrerAddress, level);
    }

    function updateX6(address userAddress, address referrerAddress, uint8 level, bool x2) private {
        if (!x2) {
            users[users[referrerAddress].x6Matrix[level].firstLevelReferrals[0]].x6Matrix[level].firstLevelReferrals.push(userAddress);
            emit NewUserPlace(userAddress,users[userAddress].id, users[referrerAddress].x6Matrix[level].firstLevelReferrals[0],users[users[referrerAddress].x6Matrix[level].firstLevelReferrals[0]].id, 2, level, uint8(users[users[referrerAddress].x6Matrix[level].firstLevelReferrals[0]].x6Matrix[level].firstLevelReferrals.length));
            emit NewUserPlace(userAddress,users[userAddress].id, referrerAddress,users[referrerAddress].id, 2, level, 2 + uint8(users[users[referrerAddress].x6Matrix[level].firstLevelReferrals[0]].x6Matrix[level].firstLevelReferrals.length));
            //set current level
            users[userAddress].x6Matrix[level].currentReferrer = users[referrerAddress].x6Matrix[level].firstLevelReferrals[0];
        } else {
            users[users[referrerAddress].x6Matrix[level].firstLevelReferrals[1]].x6Matrix[level].firstLevelReferrals.push(userAddress);
            emit NewUserPlace(userAddress,users[userAddress].id, users[referrerAddress].x6Matrix[level].firstLevelReferrals[1],users[users[referrerAddress].x6Matrix[level].firstLevelReferrals[1]].id, 2, level, uint8(users[users[referrerAddress].x6Matrix[level].firstLevelReferrals[1]].x6Matrix[level].firstLevelReferrals.length));
            emit NewUserPlace(userAddress,users[userAddress].id, referrerAddress,users[referrerAddress].id, 2, level, 4 + uint8(users[users[referrerAddress].x6Matrix[level].firstLevelReferrals[1]].x6Matrix[level].firstLevelReferrals.length));
            //set current level
            users[userAddress].x6Matrix[level].currentReferrer = users[referrerAddress].x6Matrix[level].firstLevelReferrals[1];
        }
    }

    function updateX6ReferrerSecondLevel(address userAddress, address referrerAddress, uint8 level) private {
        if (users[referrerAddress].x6Matrix[level].secondLevelReferrals.length < 4) {
            return sendTronDividends(referrerAddress, userAddress, 2, level);
        }

        address[] memory x6 = users[users[referrerAddress].x6Matrix[level].currentReferrer].x6Matrix[level].firstLevelReferrals;

        if (x6.length == 2) {
            if (x6[0] == referrerAddress ||
                x6[1] == referrerAddress) {
                users[users[referrerAddress].x6Matrix[level].currentReferrer].x6Matrix[level].closedPart = referrerAddress;
            } else if (x6.length == 1) {
                if (x6[0] == referrerAddress) {
                    users[users[referrerAddress].x6Matrix[level].currentReferrer].x6Matrix[level].closedPart = referrerAddress;
                }
            }
        }

        users[referrerAddress].x6Matrix[level].firstLevelReferrals = new address[](0);
        users[referrerAddress].x6Matrix[level].secondLevelReferrals = new address[](0);
        users[referrerAddress].x6Matrix[level].closedPart = address(0);

        if (!users[referrerAddress].activeX6Levels[level+1] && level != LAST_LEVEL) {
            users[referrerAddress].x6Matrix[level].blocked = true;
        }

        users[referrerAddress].x6Matrix[level].reinvestCount++;

        if (referrerAddress != owner) {
            address freeReferrerAddress = findFreeX6Referrer(referrerAddress, level);

            emit Reinvest(referrerAddress, freeReferrerAddress, userAddress, 2, level);
            updateX6Referrer(referrerAddress, freeReferrerAddress, level);
        } else {
            emit Reinvest(owner, address(0), userAddress, 2, level);
            sendTronDividends(owner, userAddress, 2, level);
        }
    }

    function findFreeX3Referrer(address userAddress, uint8 level) public view returns(address) {
        while (true) {
            if (users[users[userAddress].referrer].activeX3Levels[level]) {
                return users[userAddress].referrer;
            }

            userAddress = users[userAddress].referrer;
        }
    }

    function findFreeX6Referrer(address userAddress, uint8 level) public view returns(address) {
        while (true) {
            if (users[users[userAddress].referrer].activeX6Levels[level]) {
                return users[userAddress].referrer;
            }

            userAddress = users[userAddress].referrer;
        }
    }

    function usersActiveX3Levels(address userAddress, uint8 level) public view returns(bool) {
        return users[userAddress].activeX3Levels[level];
    }

    function usersActiveX6Levels(address userAddress, uint8 level) public view returns(bool) {
        return users[userAddress].activeX6Levels[level];
    }

    function get3XMatrix(address userAddress, uint8 level) public view returns(address, address[] memory, uint, bool) {
        return (users[userAddress].x3Matrix[level].currentReferrer,
                users[userAddress].x3Matrix[level].referrals,
                users[userAddress].x3Matrix[level].reinvestCount,
                users[userAddress].x3Matrix[level].blocked);
    }

    function getX6Matrix(address userAddress, uint8 level) public view returns(address, address[] memory, address[] memory, bool, uint, address) {
        return (users[userAddress].x6Matrix[level].currentReferrer,
                users[userAddress].x6Matrix[level].firstLevelReferrals,
                users[userAddress].x6Matrix[level].secondLevelReferrals,
                users[userAddress].x6Matrix[level].blocked,
                users[userAddress].x6Matrix[level].reinvestCount,
                users[userAddress].x6Matrix[level].closedPart);
    }

    function isUserExists(address user) public view returns (bool) {
        return (users[user].id != 0);
    }


#### Identify the vulnerable lines with the help of LLM output and human intervention

In [42]:
# result_dict_test['DC']
# source = test[test['file_path'] == "Pair.sol"].iloc[0]['source_code']
# print(source)

### Identify other vulnerable lines using automation methods

#### Where extracted match is covered by a set of brackets

In [46]:
def find_line_numbers(source_text, lines_to_find):
    """
    Find line numbers in source text where each line appears.
    Handles whitespace variations and multi-line spans.
    
    Args:
        source_text (str): The source text to search in
        lines_to_find (list): List of strings to find in the source
        
    Returns:
        dict: Dictionary mapping each search line to its line number(s) in source
    """
    # Normalize the source text by splitting into lines and stripping whitespace
    source_lines = [line.strip() for line in source_text.split('\n')]
    
    # Create a single string of normalized source with line numbers for debugging
    normalized_source = '\n'.join(f"{i+1}: {line}" for i, line in enumerate(source_lines))
    
    results = {}
    
    for line_to_find in lines_to_find:
        # Normalize the line to find by stripping whitespace
        normalized_line = line_to_find.strip()
        found_at = []
        
        # Check for exact matches first (single line)
        for i, source_line in enumerate(source_lines):
            if normalized_line == source_line:
                found_at.append(i+1)  # +1 because line numbers start at 1
        
        # If no exact matches, look for the line as part of multi-line content
        if not found_at:
            # Join the source text with spaces instead of newlines for a continuous search
            continuous_source = ' '.join(source_lines)
            continuous_line_map = []
            
            # Create mapping from position in continuous text to original line number
            current_pos = 0
            for i, line in enumerate(source_lines):
                line_length = len(line)
                if line:  # Only add non-empty lines
                    continuous_line_map.append((current_pos, current_pos + line_length, i+1))
                    current_pos += line_length + 1  # +1 for the space we added
            
            # Find all occurrences of the search string in the continuous text
            search_pos = 0
            while True:
                pos = continuous_source.find(normalized_line, search_pos)
                if pos == -1:
                    break
                
                # Find which line(s) this position corresponds to
                line_numbers = set()
                for start, end, line_num in continuous_line_map:
                    # Check if there's any overlap between search string and this line
                    if not (pos + len(normalized_line) <= start or pos >= end):
                        line_numbers.add(line_num)
                
                if line_numbers:
                    found_at.extend(sorted(line_numbers))
                
                search_pos = pos + 1  # Move search position forward
        
        results[line_to_find] = found_at
    
    return results

In [48]:
vulns_namings = list(reverse_vulns_mapping.keys())
def check_which_vuln_and_get_key(file_path):
    for vuln_name in vulns_namings:
        if "_" + vuln_name + ".pkl" in file_path:
            return reverse_vulns_mapping[vuln_name]
            
def extract_vulnerable_lines(text):
    match = re.search(r"VULNERABLE_LINES:(.*)", text, re.DOTALL)
    if match:
        return match.group(1)  # Extract the content inside brackets
    return None

def is_omitted(file_path, contract_address, pkl_file_path):
    for omitted in contracts_to_omit_ongoing:
        if omitted['file_path'] == file_path and omitted['contract_address'] == contract_address and omitted['vuln'] == check_which_vuln_and_get_key(pkl_file_path):
            return True
    return False

def seperate(text):
    if text[0] == '[':
        text = text[1:]
        if text[-1] == ']':
            text = text[:-1]
            comma_seperations = text.split(',')
            resultant_list = []
            for item in comma_seperations:
                item = item.strip()
                resultant_list.append(item)
            return resultant_list
        else:
            return None
    else:
        return None

def check_results(file_path):
    not_according_to_format = 0
    not_according_to_format_loosed = 0

    columns = [
    "file_path",
    "contract_address",
    "pkl_file_path",
    "extracted_match",
    "separation_output",
    "correct",
    "edited_separation_output"]
    
    # Create an empty DataFrame
    df = pd.DataFrame(columns=columns)

    with open(file_path, "rb") as file:
        data = pickle.load(file)  # Load the pickled data
    
        for item in data:
            if not is_omitted(item['file_path'], item['contract_address'], file_path):
                response = item['response']
                text_portion = response[-1].text
                extracted_match = extract_vulnerable_lines(text_portion).strip()
                if extracted_match[-1] == ']' and extracted_match[0] == '[':
                    # print(extracted_match, item['file_path'], item['contract_address'], file_path)
                    # print(text_portion)
                    # print("==============================================================================================================\n\n")

                    separation_output = seperate(extracted_match)
                    source_code = None
                    if "_train_" in file_path:
                        source_code = train[(train['file_path'] == item['file_path']) & (train['contract_address'] == item['contract_address'])].iloc[0]['source_code']
                    elif "_test_" in file_path:
                        source_code = test[(test['file_path'] == item['file_path']) & (test['contract_address'] == item['contract_address'])].iloc[0]['source_code']
                    elif "_validation_" in file_path:
                        source_code = validation[(validation['file_path'] == item['file_path']) & (validation['contract_address'] == item['contract_address'])].iloc[0]['source_code']
                    else:
                        print("Error while getting the source code", item['file_path'], item['contract_address'])
                    save_ready_seperation_output = ""
                    for line in separation_output:
                        save_ready_seperation_output += line + "\n"
                    new_row = [(item['file_path'], item['contract_address'], file_path, extracted_match, save_ready_seperation_output, 0, "")]
                    df.loc[len(df)] = new_row[0]
                    # if separation_output != None and source_code != None:
                    #     result = find_line_numbers(source_code, separation_output)
                    #     # Print results
                    #     for line, line_numbers in result.items():
                    #         if line_numbers:
                    #             print(f"Found: '{line}' found at line(s): {', '.join(map(str, line_numbers))}")
                    #         else:
                    #             print(f"Not Found: '{line}' not found")
                    # else:
                    #     print("Erorr: either seperation output is none or source code is none")
                    # print()
                else:
                    new_row = [(item['file_path'], item['contract_address'], file_path, extracted_match, "", 0, "")]
                    df.loc[len(df)] = new_row[0]
    return df

def check_results_in_all():
    all_results = []  # List to store DataFrames from each file

    for file_path in results_pkl_files:
        df = check_results(file_path)
        all_results.append(df)  # Collect DataFrames

    return pd.concat(all_results, ignore_index=True) if all_results else pd.DataFrame()  # Return combined DataFrame

df = check_results_in_all()

In [249]:
df.to_csv("identified_vuln_lines_by_llm.csv")

### Continue from hand cleaned LLM output

In [449]:
import pandas as pd
import pickle
import os
import json
import random
import numpy as np
import anthropic
import warnings
import time
import fnmatch
import re

with warnings.catch_warnings():
    warnings.simplefilter("ignore")

In [451]:
df = pd.read_csv("identified_vuln_lines_by_llm_modified.csv")

In [453]:
df

,Unnamed: 0,file_path,contract_address,pkl_file_path,extracted_match,separation_output,correct,edited_separation_output
0,0,PiggyBank.sol,0x7a0ec191d8f44f3bc3cbb4d1105ced31c30ff492,post_claude_results_test_Integer_Overflow_and_...,[return denominator * 100 * address(this).bala...,return denominator * 100 * address(this).balan...,1,NaN
1,1,TokenTycoonIGO.sol,0xfb673f08fc82807b4d0e139e794e3b328d63551f,post_claude_results_test_Integer_Overflow_and_...,[uint256 newToVal = oldToVal + _value;]\n\nWhi...,uint256 newToVal = oldToVal + _value;,1,NaN
2,2,CrystalReignShard.sol,0x5108e432d40d34a4d0ed88c12e83db0e571bfc75,post_claude_results_test_Nested_Call.pkl,[for(uint winList = 0; winList < winners.lengt...,for(uint winList = 0; winList < winners.length...,1,NaN
3,3,MultiEthSender.sol,0x11352d75f63804d5f8fdb88bddf9efe9b52d6723,post_claude_results_test_Nested_Call.pkl,"[for (uint256 i = 0; i < list.length; i++) {, ...",for (uint256 i = 0; i < list.length; i++) {\na...,1,NaN
4,4,eTrustmoney.sol,0xa5c62860475ce15c5e38a8443ca53f72113c0a5c,post_claude_results_test_Nested_Call.pkl,"[_contributors[i].transfer(_balances[i]);, for...",_contributors[i].transfer(_balances[i]);\nfor ...,1,NaN
...,...,...,...,...,...,...,...,...
280,280,Auctionify.sol,0x3a6984181f49c9ef64ada32373e736db0c9f1078,post_claude_results_validation_Unprotected_Sui...,[function cleanUpAfterYourself() public {],function cleanUpAfterYourself() public {\n,1,NaN
281,281,GetsBurned.sol,0x2f976a5382c0c6214b3d8fe6bdc5379edd35d9d4,post_claude_results_validation_Unprotected_Sui...,"[function BurnMe() public {, selfdestruct(addr...",function BurnMe() public {\nselfdestruct(addre...,1,NaN
282,282,WhoWillRuleWesterosAtTheEnd.sol,0xf2e88e0bfe61e5e41d9317e82c6938e67a913cc1,post_claude_results_validation_Unprotected_Sui...,[function clearBlockchain() external {],function clearBlockchain() external {\n,1,NaN
283,283,Promise.sol,0x23e6311dd0eb3556b300404f0cba576d504be223,post_claude_results_validation_Unprotected_Sui...,"[function selfDestruct() public{, selfdestruct...",function selfDestruct() public{\nselfdestruct(...,1,NaN
284,284,Lottery4.sol,0x2044c97717a622b4d9462329db2497e69201623a,post_claude_results_validation_Unprotected_Sui...,[selfdestruct(owner);],selfdestruct(owner);\n,1,NaN

In [455]:
df['vuln'] = None
df['line_numbers'] = "Not_Found"
df = df.drop(columns=['edited_separation_output'])
df['line_numbers_complete'] = False
for index, row in df.iterrows():
    if row['correct'] == 0:
        continue
    separation_output = row['separation_output']
    a = separation_output
    separation_output = separation_output.splitlines()
    for i in range(len(separation_output)):
        separation_output[i] = separation_output[i].strip()
    file_path = row['pkl_file_path']
    item = row
    source_code = None
    if "_train_" in file_path:
        source_code = train[(train['file_path'] == item['file_path']) & (train['contract_address'] == item['contract_address'])].iloc[0]['source_code']
    elif "_test_" in file_path:
        source_code = test[(test['file_path'] == item['file_path']) & (test['contract_address'] == item['contract_address'])].iloc[0]['source_code']
    elif "_validation_" in file_path:
        source_code = validation[(validation['file_path'] == item['file_path']) & (validation['contract_address'] == item['contract_address'])].iloc[0]['source_code']
    else:
        print("Error while getting the source code", item['file_path'], item['contract_address'])

    df.loc[index, 'vuln'] = check_which_vuln_and_get_key(file_path)
    # save_ready_seperation_output = ""
    # for line in separation_output:
    #     save_ready_seperation_output += line + "\n"
    # new_row = [(item['file_path'], item['contract_address'], file_path, extracted_match, save_ready_seperation_output, 0, "")]
    # df.loc[len(df)] = new_row[0]
    line_numbers_set = set()
    is_some_not_found = False
    if separation_output != None and source_code != None:
        result = find_line_numbers(source_code, separation_output)
        # Print results
        for line, line_numbers in result.items():
            if line_numbers:
                line_numbers_set.update(line_numbers)
                print(f"Found: '{line}' found at line(s): {', '.join(map(str, line_numbers))}")
            else:
                is_some_not_found = True
                print(f"Not Found: '{line}' not found")
    else:
        print("Erorr: either seperation output is none or source code is none")
    df.loc[index, 'line_numbers'] = str(line_numbers_set)
    if item['file_path'] == "Amp.sol":
        print(line_numbers_set)
    if not is_some_not_found:
        df.loc[index, 'line_numbers_complete'] = True
    print()

Found: 'return denominator * 100 * address(this).balance / targetAmount;' found at line(s): 33
Found: 'emit Transfer(address(this), targetAddress, denominator * msg.value / targetAmount * 100);' found at line(s): 39

Found: 'uint256 newToVal = oldToVal + _value;' found at line(s): 159

Found: 'for(uint winList = 0; winList < winners.length; winList++){' found at line(s): 220
Found: 'winners[winList].transfer(bonusETH.div(64));' found at line(s): 221

Found: 'for (uint256 i = 0; i < list.length; i++) {' found at line(s): 79
Found: 'address(list[i]).transfer(amount);' found at line(s): 80

Found: '_contributors[i].transfer(_balances[i]);' found at line(s): 60
Found: 'for (i; i < _contributors.length; i++) {' found at line(s): 57

Found: '_to[i].transfer(_value[i]);' found at line(s): 35

Found: 'players[i].transfer(playerInfo[players[i]].betAmount);' found at line(s): 486
Found: 'players[i].transfer(winOdds.mul(playerInfo[players[i]].betAmount).div(100));' found at line(s): 511

Found: 'recip.transfer(contribAmount);' found at line(s): 147

Found: 'for (uint i = 0; i < players.length; i++) {' found at line(s): 244
Found: 'players[i].transfer(playerInfo[players[i]].betAmount);' found at line(s): 245

Found: 'if(msg.sender.call.value(_am)())' found at line(s): 47
Found: 'balances[msg.sender]-=_am;' found at line(s): 49

Found: 'if(msg.sender.call.value(_am)())' found at line(s): 22
Found: 'acc.balance-=_am;' found at line(s): 24

Found: 'require(capsule.unlockTime <= block.timestamp);' found at line(s): 83

Found: 'function BurnMe () {' found at line(s): 8
Not Found: 'selfdestruct(address(this));}' not found

Found: 'selfdestruct(0x945C84b2FdD331ed3E8e7865E830626e6CeFAB94);' found at line(s): 141

Found: 'selfdestruct(targetAddress);' found at line(s): 42

Found: '(bool status, ) = paymentProxy.delegatecall(' found at line(s): 532

Found: '(bool status, ) = paymentProxy.delegatecall(' found at line(s): 294

Not Found: '(bool success, bytes memory result) = swapModule.delegatecall(abi.encodeWithSignature("swapReward(uint256,address,address[])", availableReward, address(this), path));' not found

Not Found: '(bool success, bytes memory result) = address(this).delegatecall(calls[i]);' not found

Not Found: '(bool success, bytes memory returnData) = address(plugin).delegatecall(abi.encodeWithSelector(plugin.execute.selector, path, amounts, addresses, data));' not found

Not Found: '(bool success, bytes memory returnData) = plugin.delegatecall(abi.encodeWithSelector(IDePayPaymentsV1Plugin(plugin).execute.selector, path, amounts, addresses, data));' not found

Not Found: 'require(address(converterRamp).delegatecall(bytes4(0x86ee863d), address(tokenConverter), address(mana), loanParams, 0x140, converterParams, 0x0), "Error delegate pay call");' not found

Not Found: 'function performSwapCollection(TotlePrimaryUtils.SwapCollection calldata swaps) external payable {}' not found

Not Found: 'function performSwapCollection(TotlePrimaryUtils.SwapCollection calldata swaps) external payable {}' not found

Found: 'function batchTtransferEther(address[] _to,uint256[] _value) public payable {' found at line(s): 41

Found: 'for (uint32 i = 0; i < _tos.length; i++) {' found at line(s): 14

Found: 'total -= _balances[i];' found at line(s): 62

Found: 'end_date = now + 90 days;' found at line(s): 30
Found: 'holder_balance[msg.sender] += msg.value;' found at line(s): 50
Found: 'ETHRaised += msg.value;' found at line(s): 51

Found: 'ownershipTokenCount[_to]++;' found at line(s): 463, 690
Found: 'tokenIndexToOwner[_tokenId] = _to;' found at line(s): 466, 693
Found: 'ownershipTokenCount[_from]--;' found at line(s): 473, 700
Found: 'for (uint i = 0; i < fromTokens.length - 1; i++)' found at line(s): 481, 482, 483, 709, 710, 711
Found: 'dungeons[_id].rewards += uint128(_additinalRewards);' found at line(s): 568
Found: 'dungeons.push(Dungeon(uint32(now), 0, uint8(_difficulty), uint16(_capacity), 0, 0, 0, _seedGenes, 0));' found at line(s): 537

Found: 'return currentQueueSize - currentReceiverIndex;' found at line(s): 262

Found: 'balances[_customerAddress] -= _amountOfTokens;' found at line(s): 140
Found: 'tokenSupply_ -= _amountOfTokens;' found at line(s): 141
Found: 'rewardLedger[referrer] += _amountToDistribute*(5-i)/15;' found at line(s): 175
Found: '_amountToDistribute -= _amountToDistribute*(5-i)/15;' found at line(s): 177
Found: 'rewardLedger[feeHolder_] += _amountToDistribute;' found at line(s): 180
Found: 'rewardLedger[dev1] += _amountToDistribute*750/1000;' found at line(s): 186
Found: 'rewardLedger[dev2] += _amountToDistribute*250/1000;' found at line(s): 187

Found: 'for (uint i=0; i<addresses.length; i++)' found at line(s): 27, 28

Found: 'total += counts[i];' found at line(s): 29

Found: 'total += counts[i];' found at line(s): 33

Found: 'for (uint8 i = 0; i < _to.length; i++){' found at line(s): 65
Found: 'uint amount = _value[i] * 1 finney;' found at line(s): 66

Found: 'tokensOwed[msg.sender] += amountToSend;' found at line(s): 195
Found: 'tokenSold += amountToSend;' found at line(s): 196
Found: 'ethContribution[msg.sender] += msg.value;' found at line(s): 197

Found: 'index = i * 11;' found at line(s): 641
Found: 'fashionArray.length += 1;' found at line(s): 260, 467
Found: 'fsArray.length -= 1;' found at line(s): 411, 571
Found: 'destroyFashionCount += 1;' found at line(s): 575

Found: 'timeOut = now + (_timeLimit * 1 hours);' found at line(s): 25

Found: 'return 100 * address(this).balance / targetAmount;' found at line(s): 24

Found: 'for (uint i = 0; i < _tos.length; i++)' found at line(s): 13
Found: 'function transferETHS(address[] _tos) payable public returns(bool) {' found at line(s): 10

Found: 'uint _value = v * 10 ** _decimals;' found at line(s): 8

Found: 'var value = donationData[msg.sender];' found at line(s): 95

Found: 'numOfDigits += decimalLength(_values[i]);' found at line(s): 534
Found: 'return uint256(10) ** (roundDiv(numOfDigits, length) - 1);' found at line(s): 535

Found: 'info.users[_from].balance -= _tokens;' found at line(s): 157
Found: 'uint256 _burnedAmount = _tokens * burn_rate / 100;' found at line(s): 158
Found: 'info.users[_to].balance += _transferred;' found at line(s): 179
Found: '_burnedAmount /= 2;' found at line(s): 183
Found: 'transferCount = transferCount + 1;' found at line(s): 167
Found: 'info.users[_from].allowance[msg.sender] -= _tokens;' found at line(s): 108
Found: 'info.totalFrozen += _amount;' found at line(s): 254
Found: 'info.users[_who].frozen += _amount;' found at line(s): 255
Found: 'info.totalFrozen -= _amount;' found at line(s): 266
Found: 'info.users[msg.sender].balance -= _burnedAmount;' found at line(s): 267
Found: 'info.users[msg.sender].frozen -= _amount;' found at line(s): 268
{167, 266, 267, 108, 268, 179, 254, 183, 157, 158, 255}

Found: 'for (uint i = 0; i < recipients.length; i++)' found at line(s): 124, 125, 132, 133, 152, 153, 171, 172, 189, 190

Found: 'round = round + 1' found at line(s): 152, 154
Found: 'uint256 endTime = now + HALF_TIME' found at line(s): 154, 155

Found: 'petPresellCounter[_protoId] = (curSupply - 1);' found at line(s): 643

Found: 'uint8 position = row * BOARD_ROW_SIZE + col;' found at line(s): 192, 232, 247

Found: 'stage += 1;' found at line(s): 221

Found: 'for (uint64 investorNumber; investorNumber < investorCount; investorNumber++) {' found at line(s): 482
Found: 'investor.transfer(amountToSend);' found at line(s): 485
Found: 'etherHasBeenReturnedToInvestors = true;' found at line(s): 487

Found: '_contributors[i].transfer(_balances[i]);' found at line(s): 156

Found: 'addr[i].transfer(val[i]);' found at line(s): 44

Found: 'address(tos[i]).transfer(eachAmount);' found at line(s): 25
Found: 'bep20.transferFrom(msg.sender, tos[i], eachAmount);' found at line(s): 36

Found: 'winner.transfer(prize);' found at line(s): 134

Found: 'for (uint256 i = 0; i < recipients.length; i++) payable(recipients[i]).transfer(values[i]);' found at line(s): 29, 30, 31

Found: 'recipients[i].transfer(values[i]);' found at line(s): 29

Found: 'addresses[i].transfer(giveAmount);' found at line(s): 106

Found: 'addresses[i].transfer(amount);' found at line(s): 6

Found: '_receivers[i].transfer(_amounts[i]);' found at line(s): 146

Found: 'holders[i].transfer((bal * perToken)-powercost);' found at line(s): 190
Found: 'holders[i].transfer(balanceOf[holders[i]] * perToken);' found at line(s): 240

Found: '_to[i].transfer(_value[i]);' found at line(s): 46

Found: 'for (i; i < _contributors.length; i++) {' found at line(s): 99, 114
Found: '_contributors[i].transfer(_balances[i]);' found at line(s): 102, 117

Found: '_contributors[i].transfer(_balances[i]);' found at line(s): 83

Found: 'for (uint32 i = 0; i < _tos.length; i++) {' found at line(s): 14
Found: '_tos[i].transfer(val);' found at line(s): 15

Found: '_to[ui].transfer(_amount[ui]);' found at line(s): 38

Found: 'address(uint160(to)).transfer(amount);' found at line(s): 170

Found: 'ticketIndex[i].transfer(bet);' found at line(s): 333

Found: 'players[_affId].playerAddress.transfer(TenPercentCom);' found at line(s): 117
Found: 'players[mainInvestor].playerAddress.transfer(FifteenPercentCom);' found at line(s): 122
Found: 'players[_investorId].playerAddress.transfer(TwoPercentCom);' found at line(s): 130
Found: 'cfoAddress.transfer(FifteenPercentCom);' found at line(s): 136
Found: 'winningAddress.transfer(address(this).balance);' found at line(s): 163

Found: '_contributors[i].transfer(_balances[i]);' found at line(s): 63

Found: 'recipients[i].transfer(amounts[i]);' found at line(s): 10

Found: 'for (uint256 i=0; i<recipients.length; i++)' found at line(s): 28
Found: 'recipients[i].transfer(amountPerRecipient);' found at line(s): 30

Found: 'winnerQueueAddresses[0].transfer(winnerQueueAmount[0]);' found at line(s): 379

Found: 'talks[i].addr.transfer(talks[i].amount.mul(70).div(100));' found at line(s): 58

Found: '_to[ui].transfer(_amount[ui]);' found at line(s): 35

Found: 'addresses[i].transfer( ethBalanceOf(addresses[i]) );' found at line(s): 604

Found: 'recipients[i].send(amount);' found at line(s): 125
Found: 'recipients[i].transfer(values[i]);' found at line(s): 153
Found: 'require(token.transferFrom(msg.sender, recipients[i], values[i]));' found at line(s): 173
Found: 'token.transferFrom(msg.sender, recipients[i], values[i]);' found at line(s): 191

Found: 'recipients[i].transfer(values[i]);' found at line(s): 13

Found: 'address(uint160(to[i])).transfer(amounts[i]);' found at line(s): 37
Found: 'address(uint160(to[i])).transfer(toSent);' found at line(s): 58
Found: 'uint256 price = 10**36 / uint256(IMakerPriceFeed(oracle).read());' found at line(s): 52

Found: '_to[i].transfer(_value);' found at line(s): 95

Found: '_dests[i].transfer(_amounts[i]);' found at line(s): 22

Found: '_contributors[i].transfer(_balances[i]);' found at line(s): 254

Found: 'address(uint160(_to[i])).transfer(_value[i]);' found at line(s): 200
Found: 'assert(msg.sender.send(remainingValue));' found at line(s): 205
Found: 'assert(token.transferFrom(msg.sender, _to[i], _value[i]) == true);' found at line(s): 219

Found: 'winner.transfer(prize);' found at line(s): 139
Found: 'developer.transfer(remain);' found at line(s): 144

Found: 'for (uint i = 0; i < holders.length; i++)' found at line(s): 190
Found: 'ballanceOfHolder = token.balanceOf(holders[i])' found at line(s): 193, 194
Found: 'holders[i].transfer(ballanceOfHolder.mul(weiAmount).div(token.totalSupply()))' found at line(s): 194, 195, 196, 197, 199

Found: 'myAddresses[0].transfer(value);' found at line(s): 68
Found: 'myAddresses[i].transfer(distr);' found at line(s): 73
Found: 'myAddresses[myAddresses.length-1].transfer(value);' found at line(s): 76

Found: '_addresses[i].transfer(msg.value.div(_addresses.length));' found at line(s): 122
Found: '_addresses[i].transfer(_value[i]);' found at line(s): 139

Found: '_contributors[i].transfer(_balances[i]);' found at line(s): 46

Found: '_contributors[i].transfer(_balances[i]);' found at line(s): 60

Found: 'playerPool[i].transfer(100 finney);' found at line(s): 71

Found: '_contributors[i].transfer(_balances[i]);' found at line(s): 60

Found: '_contributors[i].transfer(_balances[i]);' found at line(s): 98

Found: 'addr.transfer(value);' found at line(s): 410

Found: 'partners[j].from.transfer(share);' found at line(s): 268
Found: 'owner.transfer(ownerShare);' found at line(s): 281
Found: 'delete partners;' found at line(s): 276

Found: 'participants[gameIndex][i].transfer(PRICE);' found at line(s): 390

Found: 'caddress.call(id,from,_to[i],_value[i]);' found at line(s): 186, 195
Found: 'tc_address[i].call(id,msg.sender,from,t_value[i]);' found at line(s): 203

Found: 'addresses[i].transfer(split);' found at line(s): 28

Found: 'addresses[i].transfer(counts[i]);' found at line(s): 35

Found: 'addresses[j].transfer(amounts[j] * 1 wei);' found at line(s): 107
Found: 'tokenAddr.transferFrom(msg.sender, addresses[j], amounts[j]);' found at line(s): 150

Found: 'recipients[i].transfer(values[i]);' found at line(s): 13

Found: 'list[i].transfer(amount);' found at line(s): 15

Found: 'ownerOf(_id).transfer(token.price * (100 - 2 * SALE_FEE_RATE) / 100)' found at line(s): 465, 466
Found: 'ownerOf(i).transfer(bonus)' found at line(s): 475
Found: 'ownerOf(carveUpTokens[j]).transfer(bonus)' found at line(s): 441, 442, 443

Found: 'addresses[i].transfer(counts[i]);' found at line(s): 39

Found: 'addresses[i].transfer(amounts[i]);' found at line(s): 78

Found: '_to[i].transfer(amount);' found at line(s): 67

Not Found: 'referals[i].transfer( referalProfits[referals[i]]);}' not found

Found: 'ticketIndex[i].transfer(bet);' found at line(s): 333
Found: 'ticketIndex[lastId].transfer(prizes[i]);' found at line(s): 428
Found: 'administrator.transfer(this.balance);' found at line(s): 437, 616

Found: '_contributors[i].transfer(_balances[i]);' found at line(s): 129
Found: 'erc20token.transferFrom(msg.sender, _contributors[i], _balances[i]);' found at line(s): 111

Found: 'addrs[i].transfer(amount);' found at line(s): 19

Found: '_contributors[i].transfer(_balances[i]);' found at line(s): 46

Found: 'receivers[i].transfer(amounts[i]);' found at line(s): 27
Found: 'token.transferFrom(msg.sender,receivers[i], amounts[i]);' found at line(s): 39

Found: 'investorA.transfer(amount);' found at line(s): 282

Found: '_contributors[i].transfer(_balances[i]);' found at line(s): 60

Found: 'investors[i].transfer(ethAmounts[i]);' found at line(s): 78

Found: '_tos[i].transfer(val);' found at line(s): 14

Found: 'sponsors[i].ethAddress.transfer(sponsors[i].contribution);' found at line(s): 208

Found: '_to[i].transfer(_value[i]);' found at line(s): 123

Found: '_contributors[i].transfer(_balances[i]);' found at line(s): 89

Found: 'token.transfer(amount);' found at line(s): 6

Found: '_contributors[i].transfer(_balances[i]);' found at line(s): 346
Found: 'erc20token.transferFrom(msg.sender, _contributors[i], _balances[i]);' found at line(s): 328

Found: '_to[ui].transfer(_amount[ui]);' found at line(s): 67

Found: 'payable(recipients[i]).transfer(values[i]);' found at line(s): 38
Found: 'tokens[i].safeTransferFrom(msg.sender, recipients[i], tokenIds[i]);' found at line(s): 65
Found: 'tokens[i].safeTransferFrom(msg.sender, recipients[i], tokenIds[i], amounts[i], datas[i]);' found at line(s): 78

Found: 'payable(sender).transfer(_breedPrice);' found at line(s): 228
Found: 'payable(sender).transfer(bredBonus);' found at line(s): 246

Found: '_contributors[i].transfer(_balances[i]);' found at line(s): 60

Found: 'winners[j].transfer(winnerEtherAmount);' found at line(s): 124

Found: 'payable(singlePayout).transfer(singlePayout / (16 ** 40));' found at line(s): 106

Found: 'buys[SaleID][BuyID].buyer.transfer(lockedValue);' found at line(s): 68

Found: 'if(!_addrs[i].send(_bals[i])) throw;' found at line(s): 50
Found: 'addresses[i].transfer(msg.value / addresses.length);' found at line(s): 56

Found: '_contributors[i].transfer(_balances[i]);' found at line(s): 59

Found: 'msg.sender.transfer(people[i].amount);' found at line(s): 104
Found: 'people[i].voter.transfer(_qty+people[i].amount);' found at line(s): 85

Found: '_contributors[i].transfer(_balances[i]);' found at line(s): 60

Found: '_contributors[i].transfer(_balances[i]);' found at line(s): 127

Found: 'receiver.transfer(_amounts[i]);' found at line(s): 55

Found: 'checkWinner.transfer(DAILY_LIMIT);' found at line(s): 279
Found: 'checkWinner.transfer(dailyPool);' found at line(s): 283
Found: 'player.transfer(DAILY_LIMIT);' found at line(s): 309
Found: 'player.transfer(dailyPool);' found at line(s): 313
Found: 'checkWinner.transfer(weeklyPool);' found at line(s): 343
Found: 'player.transfer(weeklyPool);' found at line(s): 367

Found: '_contributors[i].transfer(_balances[i]);' found at line(s): 373

Found: 'for (uint i = 0; i < recipients.length; i++) { recipients[i].transfer(values[i]); }' found at line(s): 152, 153, 154, 155

Found: 'investor.transfer(contributedWei);' found at line(s): 417
Found: 'token.transfer(investor, tokensCount);' found at line(s): 384

Found: 'address(uint160(_to)).transfer(value);' found at line(s): 14

Found: 'winnerAddress.transfer(winnerPrize);' found at line(s): 212, 213

Found: 'addr.transfer(value);' found at line(s): 410

Found: '_contributors[i].transfer(_balances[i]);' found at line(s): 64

Found: '_contributors[i].transfer(_balances[i]);' found at line(s): 74

Found: 'if(msg.sender.call.value(_am)())' found at line(s): 22

Found: 'if(msg.sender.call.value(_am)())' found at line(s): 22

Found: 'if(msg.sender.call.value(_am)())' found at line(s): 22

Found: 'if(msg.sender.call.value(_am)())' found at line(s): 22
Found: 'acc.balance-=_am;' found at line(s): 24

Found: 'if(msg.sender.call.value(_am)())' found at line(s): 22
Found: 'acc.balance-=_am;' found at line(s): 24

Found: 'if(msg.sender.call.value(_am)())' found at line(s): 22

Found: 'if(msg.sender.call.value(_am)())' found at line(s): 22

Found: 'if(msg.sender.call.value(_am)())' found at line(s): 22

Found: 'if(msg.sender.call.value(_am)())' found at line(s): 22

Found: 'if(msg.sender.call.value(amount)()){' found at line(s): 127
Found: 'balances[msg.sender] -= amount;' found at line(s): 128

Found: 'if(msg.sender.call.value(_am)())' found at line(s): 22
Found: 'acc.balance-=_am;' found at line(s): 24

Found: 'if(msg.sender.call.value(_am)())' found at line(s): 22
Found: 'acc.balance-=_am;' found at line(s): 24

Found: 'if(msg.sender.call.value(_am)())' found at line(s): 47

Found: 'if(msg.sender.call.value(_am)())' found at line(s): 22

Found: 'if(msg.sender.call.value(_am)())' found at line(s): 22

Found: 'if(msg.sender.call.value(_am)())' found at line(s): 22

Found: 'if(msg.sender.call.value(_am)())' found at line(s): 22

Found: 'if(msg.sender.call.value(_am)())' found at line(s): 22

Found: 'if(msg.sender.call.value(_am)())' found at line(s): 22
Found: 'acc.balance-=_am;' found at line(s): 24

Found: 'if(msg.sender.call.value(_am)())' found at line(s): 22
Found: 'acc.balance-=_am;' found at line(s): 24

Found: 'if(msg.sender.call.value(_am)())' found at line(s): 22
Found: 'acc.balance-=_am;' found at line(s): 24

Found: 'if(msg.sender.call.value(_am)())' found at line(s): 47
Found: 'balances[msg.sender]-=_am;' found at line(s): 49

Found: 'if(msg.sender.call.value(_am)())' found at line(s): 22
Found: 'acc.balance-=_am;' found at line(s): 24

Found: 'if(msg.sender.call.value(_am)())' found at line(s): 22

Found: 'if(msg.sender.call.value(_am)())' found at line(s): 56
Not Found: 'balances[msg.sender]-=_am;' not found

Found: 'if(msg.sender.call.value(_am)())' found at line(s): 22

Found: 'if(msg.sender.call.value(_am)())' found at line(s): 22

Found: 'msg.sender.call.value(balances[msg.sender])();' found at line(s): 18

Found: 'if(msg.sender.call.value(_am)())' found at line(s): 22
Found: 'acc.balance-=_am;' found at line(s): 24

Found: 'if(msg.sender.call.value(_am)())' found at line(s): 47

In [459]:
df

,Unnamed: 0,file_path,contract_address,pkl_file_path,extracted_match,separation_output,correct,vuln,line_numbers,line_numbers_complete
0,0,PiggyBank.sol,0x7a0ec191d8f44f3bc3cbb4d1105ced31c30ff492,post_claude_results_test_Integer_Overflow_and_...,[return denominator * 100 * address(this).bala...,return denominator * 100 * address(this).balan...,1,IOU,"{33, 39}",True
1,1,TokenTycoonIGO.sol,0xfb673f08fc82807b4d0e139e794e3b328d63551f,post_claude_results_test_Integer_Overflow_and_...,[uint256 newToVal = oldToVal + _value;]\n\nWhi...,uint256 newToVal = oldToVal + _value;,1,IOU,{159},True
2,2,CrystalReignShard.sol,0x5108e432d40d34a4d0ed88c12e83db0e571bfc75,post_claude_results_test_Nested_Call.pkl,[for(uint winList = 0; winList < winners.lengt...,for(uint winList = 0; winList < winners.length...,1,NC,"{220, 221}",True
3,3,MultiEthSender.sol,0x11352d75f63804d5f8fdb88bddf9efe9b52d6723,post_claude_results_test_Nested_Call.pkl,"[for (uint256 i = 0; i < list.length; i++) {, ...",for (uint256 i = 0; i < list.length; i++) {\na...,1,NC,"{80, 79}",True
4,4,eTrustmoney.sol,0xa5c62860475ce15c5e38a8443ca53f72113c0a5c,post_claude_results_test_Nested_Call.pkl,"[_contributors[i].transfer(_balances[i]);, for...",_contributors[i].transfer(_balances[i]);\nfor ...,1,NC,"{57, 60}",True
...,...,...,...,...,...,...,...,...,...,...
280,280,Auctionify.sol,0x3a6984181f49c9ef64ada32373e736db0c9f1078,post_claude_results_validation_Unprotected_Sui...,[function cleanUpAfterYourself() public {],function cleanUpAfterYourself() public {\n,1,UpS,{173},True
281,281,GetsBurned.sol,0x2f976a5382c0c6214b3d8fe6bdc5379edd35d9d4,post_claude_results_validation_Unprotected_Sui...,"[function BurnMe() public {, selfdestruct(addr...",function BurnMe() public {\nselfdestruct(addre...,1,UpS,{6},False
282,282,WhoWillRuleWesterosAtTheEnd.sol,0xf2e88e0bfe61e5e41d9317e82c6938e67a913cc1,post_claude_results_validation_Unprotected_Sui...,[function clearBlockchain() external {],function clearBlockchain() external {\n,1,UpS,{203},True
283,283,Promise.sol,0x23e6311dd0eb3556b300404f0cba576d504be223,post_claude_results_validation_Unprotected_Sui...,"[function selfDestruct() public{, selfdestruct...",function selfDestruct() public{\nselfdestruct(...,1,UpS,{91},False
284,284,Lottery4.sol,0x2044c97717a622b4d9462329db2497e69201623a,post_claude_results_validation_Unprotected_Sui...,[selfdestruct(owner);],selfdestruct(owner);\n,1,UpS,{67},True

In [461]:
(df['line_numbers_complete'] == False).sum()

26

### Merge cleaned LLM output with outputs from other vulnerability detectino tools for evaluation

In [464]:
df_save_names = []
def merge(curr_dict, curr_dict_name):
    print(curr_dict_name, "============================================================\n")
    for key in list(curr_dict.keys()):
        vuln_name = vulns_mapping[key]
        file_path = f"post_claude_results_{curr_dict_name}_{vuln_name}.pkl"
        filtered_df = df[df['pkl_file_path'] == file_path]
        print(key, len(filtered_df))
        vuln_dataset_df = curr_dict[key].copy()
        vuln_dataset_df['claude'] = None
        vuln_dataset_df['claude_complete'] = False
        vuln_dataset_df['pkl_file_path'] = None
        for index, row in filtered_df.iterrows():
            row_to_update = vuln_dataset_df[(vuln_dataset_df['file_path'] == row['file_path']) & (vuln_dataset_df['contract_address'] == row['contract_address'])]
            if len(row_to_update) > 1:
                print("There are more than one row to update. Something wrong!!!")
            update_index = row_to_update.index[0]
            vuln_dataset_df.loc[update_index, 'claude'] = row['line_numbers']
            vuln_dataset_df.loc[update_index, 'claude_complete'] = row['line_numbers_complete']
            vuln_dataset_df.loc[update_index, 'pkl_file_path'] = row['pkl_file_path']
        curr_dict[key] = vuln_dataset_df
        vuln_dataset_df.to_csv(f"{curr_dict_name}_{key}.csv")
        df_save_names.append(f"{curr_dict_name}_{key}.csv")
    print()

merge(result_dict_train, "train")
merge(result_dict_test, "test")
merge(result_dict_validation, "validation")

train ============================================================

IOU 25
TOD 1
RE 56
UcC 0
UpS 63
TD 5
TO 0
DC 8
NC 93
FE 2

test ============================================================

IOU 2
TOD 0
RE 2
UcC 0
UpS 3
TD 1
DC 0
NC 7

validation ============================================================

IOU 0
TOD 0
RE 1
UcC 0
UpS 5
TD 0
TO 0
DC 1
NC 10

In [468]:
check_df = result_dict_train['IOU']
check_df = check_df[check_df['need_intervention'] == True]
check_df

,file_path,contract_address,soldetector,slither,oyente,smartcheck,need_intervention,claude,claude_complete,pkl_file_path
7,A004.sol,0xcae22909c9dbc37c2f6c2780d1f58decd5d3b1fd,{39},None,{41},None,True,{41},True,post_claude_results_train_Integer_Overflow_and...
11,Distribute.sol,0x84004ca3b679b94d5c27c59d710e8201068bb93b,{13},None,{11},None,True,{14},True,post_claude_results_train_Integer_Overflow_and...
13,ITSETH.sol,0xfb9ba5b45ffb009a369fdb5140fd470e7bdcdd66,{62},None,{57},None,True,{62},True,post_claude_results_train_Integer_Overflow_and...
14,myPreICO.sol,0x35e44051799bd7cea091c4fad2cba9b37e364c5b,{30},None,{25},None,True,"{50, 51, 30}",True,post_claude_results_train_Integer_Overflow_and...
17,DungeonCoreBeta.sol,0x141766882733cafa9033e8707548fdcac908db22,{540},None,{537},None,True,"{481, 482, 483, 709, 710, 711, 537, 463, 466, ...",True,post_claude_results_train_Integer_Overflow_and...
19,EDCoreVersion1.sol,0xf7ed56c1ac4d038e367a987258b86fc883b960a1,{1070},None,{1067},None,True,None,False,None
25,UserfeedsClaimWithConfigurableTokenMultiTransf...,0xecbed48098c4f25a16195c45ddf5fd736e28b14b,{131},None,{130},None,True,None,False,None
40,ESmart.sol,0x84cd9cf60bcb44f7bab8b75e6f03614c2c3b22b7,{266},None,{262},None,True,{262},True,post_claude_results_train_Integer_Overflow_and...
41,AdoreNetwork.sol,0x663a9eba94dad8ca08917549ceb10565dffd5351,{187},None,{190},None,True,"{140, 141, 175, 177, 180, 186, 187}",True,post_claude_results_train_Integer_Overflow_and...
46,CrystalDeposit.sol,0xcb8361f6ea2c93a39ffd9e8357ed6ccd48331dea,{316},None,{314},None,True,None,False,None
50,NaiveSplit.sol,0xb0ebc0f42420dcf301c711f79850b76213fad373,{23},None,{19},None,True,"{27, 28}",True,post_claude_results_train_Integer_Overflow_and...
51,MultiSend.sol,0x410804f20daf6498ec564a20132985b8da401c2e,{29},None,{33},None,True,{29},True,post_claude_results_train_Integer_Overflow_and...
56,MultiSend.sol,0xc6fb494987cafaeda71a4052da7ff0695ca3998d,{33},None,{37},None,True,{33},True,post_claude_results_train_Integer_Overflow_and...
58,Rainmaker.sol,0x76e5cfba9633a467e77db2587a50c0bec4389ab9,{66},None,{64},None,True,"{65, 66}",True,post_claude_results_train_Integer_Overflow_and...
60,LynchpinPrivateICO.sol,0x36cce24d6314445c11beb80f99f9f14b5ea9ecc2,{63},None,{61},None,True,"{195, 196, 197}",True,post_claude_results_train_Integer_Overflow_and...
62,EthealSplit.sol,0x99d804f479df333ed4d2287af2d4da3eda1b3cd1,{11},None,{10},None,True,None,False,None
67,Send.sol,0xf9e7083fd1ca37db176046ba17cc0fede7fa855d,{16},None,{15},None,True,None,False,None
68,DataEquip.sol,0x4209f9bbb4e4dd48dbd84701fcaaab1d492b5a05,{641},None,{642},None,True,"{641, 260, 467, 571, 411, 575}",True,post_claude_results_train_Integer_Overflow_and...
73,xcat.sol,0xb8aa8971e9201d183d1dadf5acc5c3f6b3076bc0,{25},None,{30},None,True,{25},True,post_claude_results_train_Integer_Overflow_and...
74,PiggyBank.sol,0x126ae85a1ebf49dc946224f5268c6bd8338d49ae,{7},None,{5},None,True,{24},True,post_claude_results_train_Integer_Overflow_and...
75,Distribute.sol,0xf3163e55e521bd49521976d43d82d21a9729dc9d,{12},None,{10},None,True,"{10, 13}",True,post_claude_results_train_Integer_Overflow_and...
87,airDrop.sol,0xe894d54dca59cb53fe9cbc5155093605c7068220,{8},None,{5},None,True,{8},True,post_claude_results_train_Integer_Overflow_and...
89,RaiseFundsForACause.sol,0x7b74e83cacf86443a1cad1152179cbeff8e25e29,{57},None,{53},None,True,{95},True,post_claude_results_train_Integer_Overflow_and...
99,contracts/converter/LiquidityPoolV1Converter.sol,0xa2787e3bfd992725183868c40d36137bbc174c3a,{534},None,{530},None,True,"{534, 535}",True,post_claude_results_train_Integer_Overflow_and...
102,Amp.sol,0x27f97bc09a4e28d5935a08e2810b3e3c94f04220,{158},None,{157},None,True,"{167, 266, 267, 108, 268, 179, 254, 183, 157, ...",True,post_claude_results_train_Integer_Overflow_and...
109,UserfeedsClaimWithConfigurableValueMultiTransf...,0xfad31a5672fbd8243e9691e8a5f958699cd0aaa9,{131},None,{130},None,True,"{132, 133, 171, 172, 189, 152, 153, 124, 125, ...",True,post_claude_results_train_Integer_Overflow_and...
110,CrystalShare.sol,0x59a8b4400ebfd61d42d8aade332076c220f72d42,{152},None,{150},None,True,"{152, 154, 155}",True,post_claude_results_train_Integer_Overflow_and...
111,ActionPresell.sol,0xc333228daab9bde8a3866efa3a9e616b7e1bae51,{554},None,{555},None,True,{643},True,post_claude_results_train_Integer_Overflow_and...
114,contracts/GoGameLogic.sol,0x34bd7814bfef669936f05e355abd882acfc569b2,{247},None,{248},None,True,"{192, 232, 247}",True,post_claude_results_train_Integer_Overflow_and...
116,DeLottery.sol,0x4763768d6938353c9c8849115c58a32142b0f9ea,{221},None,{225},None,True,{221},True,post_claude_results_train_Integer_Overflow_and...

### Validate and correct the claude output

In [185]:
import pandas as pd
import pickle
import os
import json
import random
import numpy as np
import anthropic
import warnings
import time
import fnmatch
import re

with warnings.catch_warnings():
    warnings.simplefilter("ignore")

cwd = os.getcwd()

train = pd.read_parquet(f'{cwd}\\Vulnerable-Verified-Smart-Contracts\\train.parquet')
test = pd.read_parquet(f'{cwd}\\Vulnerable-Verified-Smart-Contracts\\test.parquet')
validation = pd.read_parquet(f'{cwd}\\Vulnerable-Verified-Smart-Contracts\\validation.parquet')

def add_new_columns(dataset):
    vulns = ['IOU', 'TOD', 'RE', 'UcC', 'UpS', 'TD', 'TO', 'DC', 'NC', 'FE']
    tools = ['soldetector', 'slither', 'oyente', 'smartcheck']

    # Initialize new columns
    for vuln in vulns:
        dataset[f'{vuln}'] = "Undetected"
        for tool in tools:
            dataset[f'{vuln}_{tool}'] = "Undetected"
            
    for index, row in dataset.iterrows():
        overlapping = row['overlapping']
    
        # Parse JSON string to Python dictionary
        data = json.loads(overlapping)
    
        vulns = data.keys()
        for vuln in vulns:
            info_dict_list = data[vuln][0]
            dataset.at[index, f'{vuln}'] = "Detected"
            for info_dict in info_dict_list:
                # print(info_dict)
                try:
                    lines = str(info_dict['lines'])
                except KeyError as e:
                    lines = "[" + str(info_dict['line']) + "]"
                tool = info_dict['tool']
                dataset.at[index, f'{vuln}_{tool}'] = lines

def check_for_improper_detections(dataset):
    vulns = ['IOU', 'TOD', 'RE', 'UcC', 'UpS', 'TD', 'TO', 'DC', 'NC', 'FE']
    tools = ['soldetector', 'slither', 'oyente', 'smartcheck']
    result = dict()
    
    for vuln in vulns:
        vuln_df = dataset[dataset[vuln] == "Detected"]

        if len(vuln_df) > 0:
            # print("Vulnerability: ", vuln, "Number of samples: ", len(vuln_df))
            df = pd.DataFrame(columns=["file_path", "contract_address", "soldetector", "slither", "oyente", "smartcheck", "need_intervention"])
            # Set all columns except 'need_intervention' to 'object' type
            df[df.columns.difference(['need_intervention'])] = df[df.columns.difference(['need_intervention'])].astype('object')
            
            row_index = 0
            for index, row in vuln_df.iterrows():
                df.loc[row_index] = [row['file_path'], row['contract_address'], None, None, None, None, False]
                vul_lines_set_for_all_tool = []
                need_intervention = False
                for tool in tools:
                    vul_lines_set_for_tool = set()
                    if row[f'{vuln}_{tool}'] != "Undetected":
                        line_list = eval(row[f'{vuln}_{tool}'])
                        vul_lines_set_for_tool.update(line_list)
                        vul_lines_set_for_all_tool.append(vul_lines_set_for_tool)
                        if len(vul_lines_set_for_tool) > 0:
                            df.loc[row_index, tool] = str(vul_lines_set_for_tool)
                for i in range(len(vul_lines_set_for_all_tool)):
                    for j in range(len(vul_lines_set_for_all_tool)):
                        if i == j:
                            continue
                        if vul_lines_set_for_all_tool[i] != vul_lines_set_for_all_tool[j]:
                            need_intervention = True
                df.loc[row_index, "need_intervention"] = need_intervention
                row_index += 1
            result[vuln] = df
    return result

def count_need_intervention(result_dict):
    # print("Vulberability types: ", list(result_dict.keys()))
    # print("Number of vulnerability types: ", len(result_dict.keys()))
    count_dict = dict()
    count_sum = 0
    for key in result_dict.keys():
        df = result_dict[key]
        true_count = (df['need_intervention'] == True).sum()
        count_sum += true_count
        count_dict[key] = true_count
    return count_sum, count_dict

# Add new columns to the dataframes for further processing
add_new_columns(train)
add_new_columns(test)
add_new_columns(validation)

result_dict_train = check_for_improper_detections(train)
result_dict_test = check_for_improper_detections(test)
result_dict_validation = check_for_improper_detections(validation)

count_train, count_dict_train = count_need_intervention(result_dict_train)
count_test, count_dict_test = count_need_intervention(result_dict_test)
count_validation, count_dict_validation = count_need_intervention(result_dict_validation)

print("Train dataset\n===============================\n")
print("Number of contracts needing intervention: ", count_train)
print("Number of contracts needing intervention by vuln. type: ", count_dict_train)

print("\n\nTest dataset\n===============================\n")
print("Number of contracts needing intervention: ", count_test)
print("Number of contracts needing intervention by vuln. type: ", count_dict_test)

print("\n\nValidation dataset\n===============================")
print("Number of contracts needing intervention: ", count_validation)
print("Number of contracts needing intervention by vuln. type: ", count_dict_validation)

vulns_mapping = {'IOU': "Integer_Overflow_and_Underflow", 'TOD': "Transaction_Order_Dependency", 'RE': "Reentrancy", 'UcC': "Unchecked_Call", 'UpS': "Unprotected_Suicide", 'TD': "Timestamp_Dependency", 'TO': "TxOrigin", 'DC': "DelegateCall", 'NC': "Nested_Call", 'FE': "Frozen_Ether"}
reverse_vulns_mapping = {v: k for k, v in vulns_mapping.items()}
print(reverse_vulns_mapping)

Train dataset
===============================

Number of contracts needing intervention:  267
Number of contracts needing intervention by vuln. type:  {'IOU': 30, 'TOD': 1, 'RE': 56, 'UcC': 0, 'UpS': 64, 'TD': 5, 'TO': 0, 'DC': 9, 'NC': 100, 'FE': 2}


Test dataset
===============================

Number of contracts needing intervention:  16
Number of contracts needing intervention by vuln. type:  {'IOU': 2, 'TOD': 0, 'RE': 2, 'UcC': 0, 'UpS': 3, 'TD': 1, 'DC': 1, 'NC': 7}


Validation dataset
===============================
Number of contracts needing intervention:  18
Number of contracts needing intervention by vuln. type:  {'IOU': 0, 'TOD': 0, 'RE': 1, 'UcC': 0, 'UpS': 5, 'TD': 0, 'TO': 0, 'DC': 1, 'NC': 11}
{'Integer_Overflow_and_Underflow': 'IOU', 'Transaction_Order_Dependency': 'TOD', 'Reentrancy': 'RE', 'Unchecked_Call': 'UcC', 'Unprotected_Suicide': 'UpS', 'Timestamp_Dependency': 'TD', 'TxOrigin': 'TO', 'DelegateCall': 'DC', 'Nested_Call': 'NC', 'Frozen_Ether': 'FE'}

In [186]:
from rich.console import Console
from rich.syntax import Syntax
from IPython.display import Markdown

def check_code_for_correctness(solidity_code, highlight_lines):
    console = Console()
    
    # Create a Syntax object with highlighting
    syntax = Syntax(solidity_code, "solidity", line_numbers=True, highlight_lines=highlight_lines)
    
    # Print formatted code with highlights
    console.print(syntax)


indices_list = []
def get_indices_list(curr_df):
    global indices_list
    indices_list = curr_df.index.tolist()

def get_claude_output(pkl_file_path, file_path, contract_address):
    with open(pkl_file_path, 'rb') as file:
        data = pickle.load(file)
        for item in data:
            if item['file_path'] == file_path and item['contract_address'] == contract_address:
                return item['response'][-1].text

def check_one_by_one(curr_df, curr_df_name):
    curr_index = indices_list.pop()
    file_path = curr_df.loc[curr_index, 'file_path']
    contract_address = curr_df.loc[curr_index, 'contract_address']
    print("index: ", curr_index)
    print("file_path: ", file_path)
    print("contract_address: ", contract_address)
    
    soldetector = curr_df.loc[curr_index, 'soldetector']
    slither = curr_df.loc[curr_index, 'slither']
    oyente = curr_df.loc[curr_index, 'oyente']
    smartcheck = curr_df.loc[curr_index, 'smartcheck']
    claude = curr_df.loc[curr_index, 'claude']
    claude_complete = curr_df.loc[curr_index, 'claude_complete']

    if isinstance(soldetector, str):
        print("soldetector: ", soldetector)
        soldetector = eval(soldetector)

    if isinstance(slither, str):
        print("slither: ", slither)
        slither = eval(slither)

    if isinstance(oyente, str):
        print("oyente: ", oyente)
        oyente = eval(oyente)

    if isinstance(smartcheck, str):
        print("smartcheck: ", smartcheck)
        smartcheck = eval(smartcheck)

    if isinstance(claude, str):
        print("claude: ", claude)
    
        source_code = None
        if "train" in curr_df_name:
            source_code = train[(train['file_path'] == file_path) & (train['contract_address'] == contract_address)].iloc[0]['source_code']
        elif "test" in curr_df_name:
            source_code = test[(test['file_path'] == file_path) & (test['contract_address'] == contract_address)].iloc[0]['source_code']
        elif "validation" in curr_df_name:
            source_code = validation[(validation['file_path'] == file_path) & (validation['contract_address'] == contract_address)].iloc[0]['source_code']
        else:
            print("Error while getting the source code", file_path, contract_address)
        check_code_for_correctness(source_code, eval(claude))
        print("\nclaude output: \n")
        display(Markdown(get_claude_output(curr_df.loc[curr_index, 'pkl_file_path'], file_path, contract_address)))
    else:
        print("claude column is not a string", file_path, contract_address)

In [357]:
curr_df_name = "validation_UpS.csv"
df = pd.read_csv(curr_df_name)
print(len(df))
df = df[(df['need_intervention'] == True) & (df['claude_complete'] == True)]
get_indices_list(df)
print(len(df))

7
3

In [363]:
check_one_by_one(df, curr_df_name)

index:  0
file_path:  Auctionify.sol
contract_address:  0x3a6984181f49c9ef64ada32373e736db0c9f1078
soldetector:  {178}
slither:  {173, 174, 175, 176, 177, 178, 179, 180}
claude:  {173}

    1 pragma solidity ^0.4.22;
    2
    3 /// @title Auctionify, A platform to auction stuff, using ethereum
    4 /// @author Auctionify.xyz
    5 /// @notice This is the stand alone version of the auction
    6 /// // @dev All function calls are currently implement without side effects
    7 contract Auctionify {
    8     // Parameters of the auction.
    9     // Time is absolute unix timestamps
   10
   11     address public beneficiary;
   12     uint public auctionEnd;
   13     string public auctionTitle;
   14     string public auctionDescription;
   15     uint public minimumBid;
   16
   17     // Escrow
   18     address public escrowModerator;
   19     //bool public escrowEnabled;
   20
   21     // Current state of the auction.
   22     address public highestBidder;
   23
   24     // List of all the bids
   25     mapping(address => uint) public bids;
   26
   27     // State of the Auction
   28     enum AuctionStates { Started, Ongoing, Ended }
   29     AuctionStates public auctionState;
   30
   31
   32     //modifiers
   33     modifier auctionNotEnded()
   34     {
   35         // Revert the call if the bidding
   36         // period is over.
   37         require(
   38             now < auctionEnd, // do not front-run me miners
   39             "Auction already ended."
   40         );
   41         require(
   42           auctionState != AuctionStates.Ended,
   43            "Auction already ended."
   44           );
   45         _;
   46     }
   47
   48     //modifiers
   49     modifier isMinimumBid()
   50     {
   51       // If the bid is higher than minimumBid
   52       require(
   53           msg.value >= minimumBid,
   54           "The value is smaller than minimum bid."
   55       );
   56       _;
   57     }
   58
   59     modifier isHighestBid()
   60     {
   61       // If the bid is not higher than higestBid,
   62       // send the money back.
   63       require(
   64           msg.value > bids[highestBidder],
   65           "There already is a higher bid."
   66       );
   67       _;
   68     }
   69
   70     modifier onlyHighestBidderOrEscrow()
   71     {
   72       // only highestBidder or the moderator can call.
   73       // Also callable if no one has bidded
   74       if ((msg.sender == highestBidder) || (msg.sender == escrowModerator) || (highestBidder == address(0)))
   75         _;
   76       }
   77       else{
   78         revert();
   79       }
   80     }
   81
   82
   83     // Events that will be fired on changes.
   84     event HighestBidIncreased(address bidder, uint amount);
   85     event AuctionEnded(address winner, uint amount);
   86     event CheaterBidder(address cheater, uint amount);
   87
   88     constructor(
   89         string _auctionTitle,
   90         uint _auctionEnd,
   91         address _beneficiary,
   92         string _auctionDesc,
   93         uint _minimumBid,
   94         bool _escrowEnabled,
   95         bool _listed
   96     ) public {
   97         auctionTitle = _auctionTitle;
   98         beneficiary = _beneficiary;
   99         auctionEnd = _auctionEnd;
  100         auctionDescription = _auctionDesc;
  101         auctionState = AuctionStates.Started;
  102         minimumBid = _minimumBid;
  103         if (_escrowEnabled) {
  104           // TODO: get moderatorID, (delegate moderator list to a ens resolver)
  105           escrowModerator = address(0x32cEfb2dC869BBfe636f7547CDa43f561Bf88d5A); //TODO: ENS resolver for auc
  106         }
  107         if (_listed) {
  108           // TODO: List in the registrar
  109         }
  110     }
  111
  112     /// @author Auctionify.xyz
  113    /// @notice Bid on the auction with the amount of `msg.value`
  114    /// The lesser value will be refunded.
  115    /// updates highestBidder
  116    /// @dev should satisfy auctionNotEnded(), isMinimumBid(), isHighestBid()
  117     function bid() public payable auctionNotEnded isMinimumBid isHighestBid {
  118         // No arguments are necessary, all
  119         // information is already part of
  120         // the transaction.
  121         if (highestBidder != address(0)) {
  122             //refund the last highest bid
  123             uint lastBid = bids[highestBidder];
  124             bids[highestBidder] = 0;
  125             if(!highestBidder.send(lastBid)) {
  126                 // if failed to send, the bid is kept in the contract
  127                 emit CheaterBidder(highestBidder, lastBid);
  128             }
  129         }
  130
  131         //set the new highestBidder
  132         highestBidder = msg.sender;
  133         bids[msg.sender] = msg.value;
  134
  135         //change state and trigger event
  136         auctionState = AuctionStates.Ongoing;
  137         emit HighestBidIncreased(msg.sender, msg.value);
  138     }
  139
  140     /// @author auctionify.xyz
  141    /// @notice Getter function for highestBid `bids[highestBidder]`
  142    /// @dev View only function, free
  143    /// @return the highest bid value
  144     function highestBid() public view returns(uint){
  145       return (bids[highestBidder]);
  146     }
  147
  148     /// End the auction and send the highest bid
  149     /// to the beneficiary.
  150     /// @author auctionify.xyz
  151    /// @notice Ends the auction and sends the `bids[highestBidder]` to `beneficiary`
  152    /// @dev onlyHighestBidderOrEscrow, after `auctionEnd`, only if `auctionState != AuctionStates.Ended`
  153     function endAuction() public onlyHighestBidderOrEscrow {
  154
  155         // 1. Conditions
  156         require(now >= auctionEnd, "Auction not yet ended.");
  157         require(auctionState != AuctionStates.Ended, "Auction has already ended.");
  158
  159         // 2. Effects
  160         auctionState = AuctionStates.Ended;
  161         emit AuctionEnded(highestBidder, bids[highestBidder]);
  162
  163         // 3. Interaction. send the money to the beneficiary
  164         if(!beneficiary.send(bids[highestBidder])) {
  165             // if failed to send, the final bid is kept in the contract
  166             // the funds can be released using cleanUpAfterYourself()
  167         }
  168     }
  169
  170     /// @author auctionify.xyz
  171    /// @notice selfdestructs and sends the balance to `escrowModerator` or `beneficiary`
  172    /// @dev only if `auctionState == AuctionStates.Ended`
❱ 173   function cleanUpAfterYourself() public {
  174     require(auctionState == AuctionStates.Ended, "Auction is not ended.");
  175       if (escrowModerator != address(0)) {
  176         selfdestruct(escrowModerator);
  177       } else {
  178         selfdestruct(beneficiary); //save blockchain space, save lives
  179       }
  180   }
  181 }

claude output:

To analyze the contract for Unprotected Suicide vulnerabilities, I need to identify where the `selfdestruct` function is being used without proper access controls.

In this contract, the `cleanUpAfterYourself()` function contains calls to `selfdestruct()`:

```solidity
function cleanUpAfterYourself() public {
  require(auctionState == AuctionStates.Ended, "Auction is not ended.");
    if (escrowModerator != address(0)) {
      selfdestruct(escrowModerator);
    } else {
      selfdestruct(beneficiary); //save blockchain space, save lives
    }
}
```

This function is declared as `public`, meaning anyone can call it. While there is a check to ensure the auction has ended (`require(auctionState == AuctionStates.Ended)`), there is no access control to restrict who can trigger the self-destruct operation.

The auction state is set to `Ended` in the `endAuction()` function, which does have access controls through the `onlyHighestBidderOrEscrow` modifier. However, once the auction state is set to `Ended`, absolutely anyone can call `cleanUpAfterYourself()` to destroy the contract.

This is dangerous because:
1. It allows any user to destroy the contract after the auction ends
2. Any remaining funds in the contract will be forcibly sent to either the escrow moderator or beneficiary
3. It could disrupt contract state and functionality if called unexpectedly

The function should be protected with appropriate access controls similar to those used in the `endAuction()` function.

VULNERABLE_LINES: [function cleanUpAfterYourself() public {]

## Clean the claude incomplete vulnerabilities

In [181]:
dataset_files = ["test_DC.csv",
"test_IOU.csv",
"test_NC.csv",
"test_RE.csv",
"test_TD.csv",
"test_TOD.csv",
"test_UcC.csv",
"test_UpS.csv",
"train_DC.csv",
"train_FE.csv",
"train_IOU.csv",
"train_NC.csv",
"train_RE.csv",
"train_TD.csv",
"train_TO.csv",
"train_TOD.csv",
"train_UcC.csv",
"train_UpS.csv",
"validation_DC.csv",
"validation_IOU.csv",
"validation_NC.csv",
"validation_RE.csv",
"validation_TD.csv",
"validation_TO.csv",
"validation_TOD.csv",
"validation_UcC.csv",
"validation_UpS.csv"]

all_vulns = 0
need_intervention = 0
claude_complete = 0
claude_incomplete = 0

# List to hold the filtered rows
incomplete_rows = []

for dataset_file in dataset_files:
    df = pd.read_csv(dataset_file)
    all_vulns += len(df)
    vuln_label = (dataset_file.split("_")[1]).split(".csv")[0]
    # print(vuln_label)
    df['vuln'] = vuln_label
    need_intervention += (df['need_intervention'] == True).sum()
    claude_complete += ((df['need_intervention'] == True) & (df['claude_complete'] == True)).sum()
    claude_incomplete += ((df['need_intervention'] == True) & (df['claude_complete'] == False)).sum()

    # Select rows meeting the condition and append to the list
    condition = (df['need_intervention'] == True) & (df['claude_complete'] == False)
    incomplete_rows.append(df[condition])

# Concatenate all filtered rows into a single DataFrame
incomplete_df = pd.concat(incomplete_rows, ignore_index=True)
incomplete_df.to_csv("claude_incomplete_dataset.csv")

print("all_vulns: ", all_vulns)
print("need_intervention: ", need_intervention)
print("claude_complete: ", claude_complete)
print("claude_incomplete: ", claude_incomplete)

all_vulns:  822
need_intervention:  301
claude_complete:  259
claude_incomplete:  42

In [103]:
incomplete_df.head()

,Unnamed: 0,file_path,contract_address,soldetector,slither,oyente,smartcheck,need_intervention,claude,claude_complete,pkl_file_path,vuln
0,0,Pair.sol,0x0b3ded1b54e89f8899482cfccf515d525835bc2b,{472},"{472, 473}",NaN,NaN,True,NaN,False,NaN,DC
1,0,GetsBurned.sol,0x5f15d2d4c60e229586a5bdfe2eec1981f92845c1,{9},"{8, 9, 10}",NaN,NaN,True,{8},False,post_claude_results_test_Unprotected_Suicide.pkl,UpS
2,9,MoonbaseNFTAirdrop.sol,0x514aade50d0a679afd172720a7b6fbaccccb64ee,{826},"{832, 833, 826, 827, 828, 829, 830, 831}",NaN,NaN,True,set(),False,post_claude_results_train_DelegateCall.pkl,DC
3,16,RibbonThetaVault.sol,0x00a62ee3d2998f67cc202990b792573961d282e6,{907},"{907, 908, 909, 910, 911, 912, 913, 914, 915, ...",NaN,NaN,True,Not_Found,False,post_claude_results_train_DelegateCall.pkl,DC
4,18,contracts/pools/loss/MasterPool.sol,0xb9112feef2054acc4066c40e8c2784fa3e9d032f,{392},"{392, 393, 394}",NaN,NaN,True,set(),False,post_claude_results_train_DelegateCall.pkl,DC

### After mending the entries that the pkl file name is none

In [114]:
import pandas as pd
df = pd.read_csv("claude_incomplete_dataset.csv")
df.head()

,Unnamed: 0.1,Unnamed: 0,file_path,contract_address,soldetector,slither,oyente,smartcheck,need_intervention,claude,claude_complete,pkl_file_path,vuln
0,0,0,Pair.sol,0x0b3ded1b54e89f8899482cfccf515d525835bc2b,{472},"{472, 473}",NaN,NaN,True,"{472, 473, 488, 489, 535, 536}",True,NaN,DC
1,1,0,GetsBurned.sol,0x5f15d2d4c60e229586a5bdfe2eec1981f92845c1,{9},"{8, 9, 10}",NaN,NaN,True,"{8, 9}",True,post_claude_results_test_Unprotected_Suicide.pkl,UpS
2,2,9,MoonbaseNFTAirdrop.sol,0x514aade50d0a679afd172720a7b6fbaccccb64ee,{826},"{832, 833, 826, 827, 828, 829, 830, 831}",NaN,NaN,True,"{826, 827, 828, 829, 830, 831, 832, 833}",True,post_claude_results_train_DelegateCall.pkl,DC
3,3,16,RibbonThetaVault.sol,0x00a62ee3d2998f67cc202990b792573961d282e6,{907},"{907, 908, 909, 910, 911, 912, 913, 914, 915, ...",NaN,NaN,True,"{456, 871, 872, 873, 874, 875, 876, 877, 878, ...",True,post_claude_results_train_DelegateCall.pkl,DC
4,4,18,contracts/pools/loss/MasterPool.sol,0xb9112feef2054acc4066c40e8c2784fa3e9d032f,{392},"{392, 393, 394}",NaN,NaN,True,"{392, 393, 394}",True,post_claude_results_train_DelegateCall.pkl,DC

In [116]:
print((df['claude_complete'] == True).sum())
print((df['claude_complete'] == False).sum())

42
0

In [110]:
from rich.console import Console
from rich.syntax import Syntax
from IPython.display import Markdown

def check_code_for_correctness(solidity_code):
    console = Console()
    
    # Create a Syntax object with highlighting
    syntax = Syntax(solidity_code, "solidity", line_numbers=True)
    
    # Print formatted code with highlights
    console.print(syntax)


indices_list = []
def get_indices_list(curr_df):
    global indices_list
    indices_list = curr_df.index.tolist()

def get_claude_output(pkl_file_path, file_path, contract_address):
    with open(pkl_file_path, 'rb') as file:
        data = pickle.load(file)
        for item in data:
            if item['file_path'] == file_path and item['contract_address'] == contract_address:
                return item['response'][-1].text

def check_one_by_one(curr_df):
    curr_index = indices_list.pop()
    file_path = curr_df.loc[curr_index, 'file_path']
    contract_address = curr_df.loc[curr_index, 'contract_address']
    print("index: ", curr_index)
    print("file_path: ", file_path)
    print("contract_address: ", contract_address)
    
    soldetector = curr_df.loc[curr_index, 'soldetector']
    slither = curr_df.loc[curr_index, 'slither']
    oyente = curr_df.loc[curr_index, 'oyente']
    smartcheck = curr_df.loc[curr_index, 'smartcheck']
    claude = curr_df.loc[curr_index, 'claude']
    claude_complete = curr_df.loc[curr_index, 'claude_complete']

    if isinstance(soldetector, str):
        print("soldetector: ", soldetector)
        soldetector = eval(soldetector)

    if isinstance(slither, str):
        print("slither: ", slither)
        slither = eval(slither)

    if isinstance(oyente, str):
        print("oyente: ", oyente)
        oyente = eval(oyente)

    if isinstance(smartcheck, str):
        print("smartcheck: ", smartcheck)
        smartcheck = eval(smartcheck)

    if isinstance(claude, str):
        print("claude: ", claude)

        pkl_file_path = curr_df.loc[curr_index, 'pkl_file_path']
        source_code = None
        if "train" in pkl_file_path:
            source_code = train[(train['file_path'] == file_path) & (train['contract_address'] == contract_address)].iloc[0]['source_code']
        elif "test" in pkl_file_path:
            source_code = test[(test['file_path'] == file_path) & (test['contract_address'] == contract_address)].iloc[0]['source_code']
        elif "validation" in pkl_file_path:
            source_code = validation[(validation['file_path'] == file_path) & (validation['contract_address'] == contract_address)].iloc[0]['source_code']
        else:
            print("Error while getting the source code", file_path, contract_address)
        check_code_for_correctness(source_code)
        print("\nclaude output: \n")
        display(Markdown(get_claude_output(curr_df.loc[curr_index, 'pkl_file_path'], file_path, contract_address)))
    else:
        print("claude column is not a string", file_path, contract_address)

In [112]:
curr_df_name = "claude_incomplete_dataset.csv"
df = pd.read_csv(curr_df_name)
df = df[(df['need_intervention'] == True) & (df['claude_complete'] == False)]
get_indices_list(df)
print(len(df))

42

In [81]:
check_one_by_one(df)

index:  40
file_path:  GetsBurned.sol
contract_address:  0x2f976a5382c0c6214b3d8fe6bdc5379edd35d9d4
soldetector:  {8}
slither:  {8, 9, 6, 7}
claude:  {6}

   1 pragma solidity ^0.4.0;
   2 contract GetsBurned {
   3     function () payable public {
   4     }
   5
   6     function BurnMe() public {
   7         // Selfdestruct and send eth to self,
   8         selfdestruct(address(this));
   9     }
  10 }

claude output:

After analyzing the code, I need to identify the Unprotected Suicide vulnerability.

An Unprotected Suicide vulnerability occurs when a contract can be destroyed via `selfdestruct` without proper access controls, allowing anyone to terminate the contract and potentially cause loss of funds or service disruption.

In this contract:
1. The `BurnMe()` function is publicly accessible with no access controls
2. This function calls `selfdestruct`, which destroys the contract
3. Anyone can call this function to terminate the contract at any time
4. The funds are sent to `address(this)` (the contract itself), which means the funds will be lost forever when the contract is destroyed

The main issue is that there's no protection on who can call the self-destruct functionality - no owner check, no authorization mechanism, and no other form of access control.

The vulnerable parts are both the function declaration (which lacks access controls) and the selfdestruct call itself.

VULNERABLE_LINES: [function BurnMe() public {, selfdestruct(address(this));}]

# Merge all cleaned datasets to one

In [14]:
import pandas as pd
import pickle
import os
import json
import random
import numpy as np
import anthropic
import warnings
import time
import fnmatch
import re

with warnings.catch_warnings():
    warnings.simplefilter("ignore")

cwd = os.getcwd()

train = pd.read_parquet(f'{cwd}\\Vulnerable-Verified-Smart-Contracts\\train.parquet')
test = pd.read_parquet(f'{cwd}\\Vulnerable-Verified-Smart-Contracts\\test.parquet')
validation = pd.read_parquet(f'{cwd}\\Vulnerable-Verified-Smart-Contracts\\validation.parquet')

def add_new_columns(dataset):
    vulns = ['IOU', 'TOD', 'RE', 'UcC', 'UpS', 'TD', 'TO', 'DC', 'NC', 'FE']
    tools = ['soldetector', 'slither', 'oyente', 'smartcheck']

    # Initialize new columns
    for vuln in vulns:
        dataset[f'{vuln}'] = "Undetected"
        for tool in tools:
            dataset[f'{vuln}_{tool}'] = "Undetected"
            
    for index, row in dataset.iterrows():
        overlapping = row['overlapping']
    
        # Parse JSON string to Python dictionary
        data = json.loads(overlapping)
    
        vulns = data.keys()
        for vuln in vulns:
            info_dict_list = data[vuln][0]
            dataset.at[index, f'{vuln}'] = "Detected"
            for info_dict in info_dict_list:
                # print(info_dict)
                try:
                    lines = str(info_dict['lines'])
                except KeyError as e:
                    lines = "[" + str(info_dict['line']) + "]"
                tool = info_dict['tool']
                dataset.at[index, f'{vuln}_{tool}'] = lines

def check_for_improper_detections(dataset):
    vulns = ['IOU', 'TOD', 'RE', 'UcC', 'UpS', 'TD', 'TO', 'DC', 'NC', 'FE']
    tools = ['soldetector', 'slither', 'oyente', 'smartcheck']
    result = dict()
    
    for vuln in vulns:
        vuln_df = dataset[dataset[vuln] == "Detected"]

        if len(vuln_df) > 0:
            # print("Vulnerability: ", vuln, "Number of samples: ", len(vuln_df))
            df = pd.DataFrame(columns=["file_path", "contract_address", "soldetector", "slither", "oyente", "smartcheck", "need_intervention"])
            # Set all columns except 'need_intervention' to 'object' type
            df[df.columns.difference(['need_intervention'])] = df[df.columns.difference(['need_intervention'])].astype('object')
            
            row_index = 0
            for index, row in vuln_df.iterrows():
                df.loc[row_index] = [row['file_path'], row['contract_address'], None, None, None, None, False]
                vul_lines_set_for_all_tool = []
                need_intervention = False
                for tool in tools:
                    vul_lines_set_for_tool = set()
                    if row[f'{vuln}_{tool}'] != "Undetected":
                        line_list = eval(row[f'{vuln}_{tool}'])
                        vul_lines_set_for_tool.update(line_list)
                        vul_lines_set_for_all_tool.append(vul_lines_set_for_tool)
                        if len(vul_lines_set_for_tool) > 0:
                            df.loc[row_index, tool] = str(vul_lines_set_for_tool)
                for i in range(len(vul_lines_set_for_all_tool)):
                    for j in range(len(vul_lines_set_for_all_tool)):
                        if i == j:
                            continue
                        if vul_lines_set_for_all_tool[i] != vul_lines_set_for_all_tool[j]:
                            need_intervention = True
                df.loc[row_index, "need_intervention"] = need_intervention
                row_index += 1
            result[vuln] = df
    return result

# def count_need_intervention(result_dict):
#     # print("Vulberability types: ", list(result_dict.keys()))
#     # print("Number of vulnerability types: ", len(result_dict.keys()))
#     count_dict = dict()
#     count_sum = 0
#     for key in result_dict.keys():
#         df = result_dict[key]
#         true_count = (df['need_intervention'] == True).sum()
#         count_sum += true_count
#         count_dict[key] = true_count
#     return count_sum, count_dict

# Add new columns to the dataframes for further processing
add_new_columns(train)
add_new_columns(test)
add_new_columns(validation)

result_dict_train = check_for_improper_detections(train)
result_dict_test = check_for_improper_detections(test)
result_dict_validation = check_for_improper_detections(validation)

# count_train, count_dict_train = count_need_intervention(result_dict_train)
# count_test, count_dict_test = count_need_intervention(result_dict_test)
# count_validation, count_dict_validation = count_need_intervention(result_dict_validation)

# print("Train dataset\n===============================\n")
# print("Number of contracts needing intervention: ", count_train)
# print("Number of contracts needing intervention by vuln. type: ", count_dict_train)

# print("\n\nTest dataset\n===============================\n")
# print("Number of contracts needing intervention: ", count_test)
# print("Number of contracts needing intervention by vuln. type: ", count_dict_test)

# print("\n\nValidation dataset\n===============================")
# print("Number of contracts needing intervention: ", count_validation)
# print("Number of contracts needing intervention by vuln. type: ", count_dict_validation)

# vulns_mapping = {'IOU': "Integer_Overflow_and_Underflow", 'TOD': "Transaction_Order_Dependency", 'RE': "Reentrancy", 'UcC': "Unchecked_Call", 'UpS': "Unprotected_Suicide", 'TD': "Timestamp_Dependency", 'TO': "TxOrigin", 'DC': "DelegateCall", 'NC': "Nested_Call", 'FE': "Frozen_Ether"}
# reverse_vulns_mapping = {v: k for k, v in vulns_mapping.items()}
# print(reverse_vulns_mapping)

In [15]:
vulns = ['IOU', 'TOD', 'RE', 'UcC', 'UpS', 'TD', 'TO', 'DC', 'NC', 'FE']

In [18]:
def add_cleaned_rows(df, df1):
    for df1_index, df1_row in df1.iterrows():
        condition = (df['file_path'] == df1_row['file_path']) & (df['contract_address'] == df1_row['contract_address']) & (df['vuln'] == df1_row['vuln'])
        matching_indexes = df.index[condition].tolist()
        if len(matching_indexes) == 1:
            match_index = matching_indexes[0]
            if df.loc[match_index, 'need_intervention'] == True:
                df.loc[match_index, 'claude'] = df1_row['claude']
                df.loc[match_index, 'claude_complete'] = df1_row['claude_complete']
                df.loc[match_index, 'final_line_numbers'] = df1_row['claude']
                df.loc[match_index, 'pkl_file_path'] = df1_row['pkl_file_path']
        else:
            if len(matching_indexes) > 1:
                print("Unexpected error: more than 1 matching index")
    return df

result_dicts = {"train": result_dict_train, "test": result_dict_test, "validation": result_dict_validation}
dfs = []
count = 0
for result_dict_key in list(result_dicts.keys()):
    result_dict = result_dicts[result_dict_key]
    for vuln in list(result_dict.keys()):
        df = result_dict[vuln]

        count += len(df)
        
        df['final_line_numbers'] = None
        df['claude'] = None
        df['claude_complete'] = False
        df['pkl_file_path'] = None
        df['vuln'] = vuln
        df['type'] = result_dict_key

        for index, row in df.iterrows():
            if row['need_intervention'] == False:
                soldetector = row['soldetector']
                slither = row['slither']
                oyente = row['oyente']
                smartcheck = row['smartcheck']
                final_line_numbers = None
                if slither is not None and isinstance(slither, str):
                    final_line_numbers = slither
                elif soldetector is not None and isinstance(soldetector, str):
                    final_line_numbers = soldetector
                elif oyente is not None and isinstance(oyente, str):
                    final_line_numbers = oyente
                elif smartcheck is not None and isinstance(smartcheck, str):
                    final_line_numbers = smartcheck
                else:
                    print("Unexpected error: all detectors results are empty")
                df.loc[index, 'final_line_numbers'] = str(eval(final_line_numbers))

        if os.path.exists(f"{result_dict_key}_{vuln}_curated.csv"):
            # print(f"{result_dict_key}_{vuln}_curated.csv exists")
            df1 = pd.read_csv(f"{result_dict_key}_{vuln}_curated.csv")
            for df1_index, df1_row in df1.iterrows():
                condition = (df['file_path'] == df1_row['file_path']) & (df['contract_address'] == df1_row['contract_address']) & (df['vuln'] == vuln)
                matching_indexes = df.index[condition].tolist()
                if len(matching_indexes) == 1:
                    match_index = matching_indexes[0]
                    if df.loc[match_index, 'need_intervention'] == True:
                        df.loc[match_index, 'claude'] = df1_row['claude']
                        df.loc[match_index, 'claude_complete'] = df1_row['claude_complete']
                        df.loc[match_index, 'final_line_numbers'] = df1_row['claude']
                        df.loc[match_index, 'pkl_file_path'] = df1_row['pkl_file_path']
                else:
                    if len(matching_indexes) > 1:
                        print("Unexpected error: more than 1 matching index")
        result_dict[vuln] = df
        dfs.append(df)

merged_df = pd.concat(dfs, ignore_index=True)

df = pd.read_csv("claude_incomplete_dataset.csv")
df.drop(['Unnamed: 0.1', 'Unnamed: 0'], axis=1, inplace=True)
final_per_vuln_df = add_cleaned_rows(merged_df, df)
final_per_vuln_df.to_csv("processed/vulnerable_verified_smart_contracts_dataset_with_line_numbers_per_vulnerability.csv")
final_per_vuln_df

,file_path,contract_address,soldetector,slither,oyente,smartcheck,need_intervention,final_line_numbers,claude,claude_complete,pkl_file_path,vuln,type
0,Gift.sol,0xb91a6c5c6362b10db6440d690e5391bb1eabe591,{14},None,{14},None,False,{14},None,False,None,IOU,train
1,TokenERC20.sol,0xd70e66775a74a9aedeac6e28313e1033cd726552,{441},None,{441},None,False,{441},None,False,None,IOU,train
2,Vault.sol,0x598ab825d607ace3b00d8714c0a141c7ae2e6822,{270},None,{270},None,False,{270},None,False,None,IOU,train
3,Sandstone.sol,0xae3bf0f077ed66dda9fb1b5475942c919ef3bb0d,{14},None,{14},None,False,{14},None,False,None,IOU,train
4,bet1000_001eth.sol,0xab3b0810b839f49c2d619b55f196aae764422e22,{127},None,{127},None,False,{127},None,False,None,IOU,train
...,...,...,...,...,...,...,...,...,...,...,...,...,...
817,SkyWay.sol,0x8235cfc3e7d9500b16cdf23ea66979f2d5ab3c74,{105},{107},None,{105},True,"{105, 107}","{105, 107}",True,NaN,NC,validation
818,BulkSender.sol,0xcf8b99880a5ae950fe2a0b949e69a2e3e9e73c3e,{86},{90},None,{86},True,"{90, 86}","{90, 86}",True,post_claude_results_validation_Nested_Call.pkl,NC,validation
819,UnilotTailEther.sol,0x468480af8817914062e1d198eb238e5087896f86,{372},{374},None,{372},True,"{446, 442, 374, 372}","{446, 442, 374, 372}",True,post_claude_results_validation_Nested_Call.pkl,NC,validation
820,MultiTransfer.sol,0xb47ba2f58795f87c71403fbcae57a3aee902e175,{33},{34},None,{33},True,"{34, 33}","{34, 33}",True,post_claude_results_validation_Nested_Call.pkl,NC,validation
821,MultiSend.sol,0x3d7c33c71996540755f4ae6d7454dea0344f89c0,{35},{36},None,{35},True,"{36, 35}","{36, 35}",True,post_claude_results_validation_Nested_Call.pkl,NC,validation

In [19]:
import pandas as pd

def concat_final_line_numbers(series):
    """
    Given a Series of string representations of lists or sets,
    evaluate each and combine all items into a set.
    """
    combined = set()
    for item in series:
        if isinstance(item, str):
            try:
                # Evaluate the string to convert it into a Python object.
                evaluated = eval(item)
                # If evaluated is iterable (but not a string), update the set.
                if hasattr(evaluated, '__iter__') and not isinstance(evaluated, str):
                    combined.update(evaluated)
                else:
                    combined.add(evaluated)
            except Exception as e:
                print(f"Error evaluating {item}: {e}")
        elif pd.notna(item):
            try:
                combined.update(item)
            except Exception:
                combined.add(item)
    return str(combined)

# Read the CSV file (update the path if needed)
df = pd.read_csv('processed/vulnerable_verified_smart_contracts_dataset_with_line_numbers_per_vulnerability.csv')

# Group by the compound key and aggregate the columns.
# For 'vulns' and 'type', join unique values separated by a comma.
grouped = df.groupby(['file_path', 'contract_address'], as_index=False).agg({
    'final_line_numbers': concat_final_line_numbers,
    'vuln': lambda x: ','.join(x.dropna().unique()),
    'type': lambda x: ','.join(x.dropna().unique())
})

grouped['source_code'] = None
for index, row in grouped.iterrows():
    source_code = None
    if row['type'] == 'train':
        source_code = train[(train['file_path'] == row['file_path']) & (train['contract_address'] == row['contract_address'])].iloc[0]['source_code']
    elif row['type'] == 'test':
        source_code = test[(test['file_path'] == row['file_path']) & (test['contract_address'] == row['contract_address'])].iloc[0]['source_code']
    elif row['type'] == 'validation':
        source_code = validation[(validation['file_path'] == row['file_path']) & (validation['contract_address'] == row['contract_address'])].iloc[0]['source_code']
    else:
        print("Error while getting the source code", file_path, contract_address)
    grouped.loc[index, 'source_code'] = source_code
        
grouped.to_csv('processed/vulnerable_verified_smart_contracts_dataset_with_line_numbers.csv', index=False)

In [20]:
grouped

,file_path,contract_address,final_line_numbers,vuln,type,source_code
0,@c-layer/common/contracts/core/Core.sol,0x2a903c2f657803a2e614c42672247366d757ab34,{55},DC,train,pragma solidity ^0.6.0;\r\n\r\n\r\n\r\n\r\n\r\...
1,A004.sol,0xcae22909c9dbc37c2f6c2780d1f58decd5d3b1fd,"{41, 46}","IOU,NC",train,pragma solidity ^0.4.25;\r\n\r\n\r\n\r\n/**\r\...
2,ABIO_preICO.sol,0x6d84769b1e287a27f282a938c8110b22714dbf78,{201},TD,train,pragma solidity ^0.4.24;\r\ncontract Ownable{\...
3,ACCURAL_DEPOSIT.sol,0x4320e6f8c05b27ab4707cd1f6d5ce6f3e4b3a5a1,"{49, 47}",RE,train,pragma solidity ^0.4.19;\r\n\r\ncontract ACCUR...
4,ACL.sol,0x96f041b96708813b1d789606926c524e78543664,{252},DC,train,//File: contracts/acl/IACL.sol\r\npragma solid...
...,...,...,...,...,...,...
604,ultra_bank.sol,0x094a5e6e395212bfc6c773b2210409eba4ca19d7,"{24, 20, 22}","RE,TD",train,pragma solidity ^0.4.25;\r\n\r\ncontract ultra...
605,we_play.sol,0x6df766e4b524aa1d4b4b9405994ca69dc161da3f,{34},TOD,test,pragma solidity ^0.4.25;\r\n\r\ncontract we_pl...
606,xcat.sol,0xb8aa8971e9201d183d1dadf5acc5c3f6b3076bc0,"{32, 25, 41, 30, 31}","IOU,UpS,TD",train,pragma solidity ^0.4.18;\r\n\r\ncontract HTLC ...
607,xyphar.sol,0x12359487aa7844fead6a20aca5bfae1d3196cedb,{46},NC,train,pragma solidity 0.4.24;\r\n\r\n\r\nlibrary Saf...
608,you_can_do_it.sol,0xd8cb4151fce62b3d08269343a79dbcd6f83d3405,{43},TOD,train,pragma solidity ^0.4.20;\r\n\r\ncontract you_c...