In [15]:
import os
import shutil
import pandas as pd

cwd = os.getcwd()

parent_folder = f"{cwd}\\DefiVulnLabs\\src\\test"

In [3]:
cwd = os.getcwd()

parent_folder = f"{cwd}\\DefiVulnLabs\\src\\test"

def list_solidity_files(parent_folder: str):
    return [f for f in os.listdir(parent_folder) if f.endswith(".sol")]

def read_file(path: str):
    with open(path, 'r', encoding='utf-8') as file:
        return file.read()

In [5]:
vuln_sol_files = list_solidity_files(parent_folder)
len(vuln_sol_files)

224

In [7]:
vuln_sol_files_copies = []
# Assuming vuln_sol_files contains the full paths of the Solidity files
for file_name in vuln_sol_files:
    file_path = f"{parent_folder}\\{file_name}"
    folder, filename = os.path.split(file_path)
    name, ext = os.path.splitext(filename)
    new_filename = f"{name}_modified{ext}"
    new_file_path = os.path.join(folder, new_filename)
    vuln_sol_files_copies.append(new_file_path)
    
    shutil.copy(file_path, new_file_path)

print("Copies created successfully.")

Copies created successfully.

In [25]:
print(len(list_solidity_files(parent_folder)))

224

In [31]:
data = {"filename": vuln_sol_files_copies}
df = pd.DataFrame(data)
df['done'] = 0
df.to_csv("defi_vuln_labs_dataset.csv")

In [35]:
df['file'] = None
for index, row in df.iterrows():
    df.loc[index, 'file'] = row['filename'].split("\\")[-1]

In [39]:
(df['file'] == None).sum()

0

In [41]:
df

,filename,done,file
0,D:\UoM\Final_Year_Project_New\vulnerability-de...,0,ApproveScam_modified.sol
1,D:\UoM\Final_Year_Project_New\vulnerability-de...,0,Array-deletion_modified.sol
2,D:\UoM\Final_Year_Project_New\vulnerability-de...,0,Backdoor-assembly_modified.sol
3,D:\UoM\Final_Year_Project_New\vulnerability-de...,0,Bypasscontract_modified.sol
4,D:\UoM\Final_Year_Project_New\vulnerability-de...,0,DataLocation_modified.sol
5,D:\UoM\Final_Year_Project_New\vulnerability-de...,0,Delegatecall_modified.sol
6,D:\UoM\Final_Year_Project_New\vulnerability-de...,0,Dirtybytes_modified.sol
7,D:\UoM\Final_Year_Project_New\vulnerability-de...,0,Divmultiply_modified.sol
8,D:\UoM\Final_Year_Project_New\vulnerability-de...,0,DOS_modified.sol
9,D:\UoM\Final_Year_Project_New\vulnerability-de...,0,ecrecover_modified.sol
10,D:\UoM\Final_Year_Project_New\vulnerability-de...,0,empty-loop_modified.sol
11,D:\UoM\Final_Year_Project_New\vulnerability-de...,0,ERC777-reentrancy_modified.sol
12,D:\UoM\Final_Year_Project_New\vulnerability-de...,0,fee-on-transfer_modified.sol
13,D:\UoM\Final_Year_Project_New\vulnerability-de...,0,first-deposit_modified.sol
14,D:\UoM\Final_Year_Project_New\vulnerability-de...,0,Flashloan-flaw_modified.sol
15,D:\UoM\Final_Year_Project_New\vulnerability-de...,0,gas-price_modified.sol
16,D:\UoM\Final_Year_Project_New\vulnerability-de...,0,Hash-collisions_modified.sol
17,D:\UoM\Final_Year_Project_New\vulnerability-de...,0,Immunefi_ch1_modified.sol
18,D:\UoM\Final_Year_Project_New\vulnerability-de...,0,Immunefi_ch2_modified.sol
19,D:\UoM\Final_Year_Project_New\vulnerability-de...,0,Incorrect_sanity_checks_modified.sol
20,D:\UoM\Final_Year_Project_New\vulnerability-de...,0,interface_modified.sol
21,D:\UoM\Final_Year_Project_New\vulnerability-de...,0,Invariant_modified.sol
22,D:\UoM\Final_Year_Project_New\vulnerability-de...,0,NFT-transfer_modified.sol
23,D:\UoM\Final_Year_Project_New\vulnerability-de...,0,NFTMint_exposedMetadata_modified.sol
24,D:\UoM\Final_Year_Project_New\vulnerability-de...,0,Oracle-stale_modified.sol
25,D:\UoM\Final_Year_Project_New\vulnerability-de...,0,Overflow_modified.sol
26,D:\UoM\Final_Year_Project_New\vulnerability-de...,0,Overflow2_modified.sol
27,D:\UoM\Final_Year_Project_New\vulnerability-de...,0,payable-transfer_modified.sol
28,D:\UoM\Final_Year_Project_New\vulnerability-de...,0,phantom-permit_modified.sol
29,D:\UoM\Final_Year_Project_New\vulnerability-de...,0,Precision-loss_modified.sol
30,D:\UoM\Final_Year_Project_New\vulnerability-de...,0,Price_manipulation_modified.sol
31,D:\UoM\Final_Year_Project_New\vulnerability-de...,0,Privatedata_modified.sol
32,D:\UoM\Final_Year_Project_New\vulnerability-de...,0,Randomness_modified.sol
33,D:\UoM\Final_Year_Project_New\vulnerability-de...,0,ReadOnlyReentrancy_modified.sol
34,D:\UoM\Final_Year_Project_New\vulnerability-de...,0,recoverERC20_modified.sol
35,D:\UoM\Final_Year_Project_New\vulnerability-de...,0,Reentrancy_modified.sol
36,D:\UoM\Final_Year_Project_New\vulnerability-de...,0,return-break_modified.sol
37,D:\UoM\Final_Year_Project_New\vulnerability-de...,0,Returnfalse_modified.sol
38,D:\UoM\Final_Year_Project_New\vulnerability-de...,0,Returnvalue_modified.sol
39,D:\UoM\Final_Year_Project_New\vulnerability-de...,0,self-transfer_modified.sol
40,D:\UoM\Final_Year_Project_New\vulnerability-de...,0,Selfdestruct_modified.sol
41,D:\UoM\Final_Year_Project_New\vulnerability-de...,0,Selfdestruct2_modified.sol
42,D:\UoM\Final_Year_Project_New\vulnerability-de...,0,SenseFinance_exp_modified.sol
43,D:\UoM\Final_Year_Project_New\vulnerability-de...,0,SignatureReplay_modified.sol
44,D:\UoM\Final_Year_Project_New\vulnerability-de...,0,SignatureReplayNBA_modified.sol
45,D:\UoM\Final_Year_Project_New\vulnerability-de...,0,Slippage-deadline_modified.sol
46,D:\UoM\Final_Year_Project_New\vulnerability-de...,0,Storage-collision-audio_modified.sol
47,D:\UoM\Final_Year_Project_New\vulnerability-de...,0,Storage-collision_modified.sol
48,D:\UoM\Final_Year_Project_New\vulnerability-de...,0,Struct-deletion_modified.sol
49,D:\UoM\Final_Year_Project_New\vulnerability-de...,0,txorigin_modified.sol
50,D:\UoM\Final_Year_Project_New\vulnerability-de...,0,Uninitialized_variables_modified.sol
51,D:\UoM\Final_Year_Project_New\vulnerability-de...,0,UniswapV3ETHRefundExploit_modified.sol
52,D:\UoM\Final_Year_Project_New\vulnerability-de...,0,Unprotected-callback_modified.sol
53,D:\UoM\Final_Year_Project_New\vulnerability-de...,0,unsafe-downcast_modified.sol
54,D:\UoM\Final_Year_Project_New\vulnerability-de...,0,UnsafeCall_modified.sol
55,D:\UoM\Final_Year_Project_New\vulnerability-de...,0,Visibility_modified.sol

In [43]:
df.to_csv("defi_vuln_labs_dataset.csv")

# After the hand labeling of vulnerability localization

In [17]:
df = pd.read_csv("defi_vuln_labs_dataset.csv")
df

,Unnamed: 0,filename,done,file,unclear
0,0,D:\UoM\Final_Year_Project_New\vulnerability-de...,1,ApproveScam_modified.sol,1
1,1,D:\UoM\Final_Year_Project_New\vulnerability-de...,1,Array-deletion_modified.sol,0
2,2,D:\UoM\Final_Year_Project_New\vulnerability-de...,1,Backdoor-assembly_modified.sol,0
3,3,D:\UoM\Final_Year_Project_New\vulnerability-de...,1,Bypasscontract_modified.sol,0
4,4,D:\UoM\Final_Year_Project_New\vulnerability-de...,1,DataLocation_modified.sol,0
5,5,D:\UoM\Final_Year_Project_New\vulnerability-de...,1,Delegatecall_modified.sol,0
6,6,D:\UoM\Final_Year_Project_New\vulnerability-de...,1,Dirtybytes_modified.sol,0
7,7,D:\UoM\Final_Year_Project_New\vulnerability-de...,1,Divmultiply_modified.sol,0
8,8,D:\UoM\Final_Year_Project_New\vulnerability-de...,1,DOS_modified.sol,0
9,9,D:\UoM\Final_Year_Project_New\vulnerability-de...,1,ecrecover_modified.sol,0
10,10,D:\UoM\Final_Year_Project_New\vulnerability-de...,1,empty-loop_modified.sol,1
11,11,D:\UoM\Final_Year_Project_New\vulnerability-de...,1,ERC777-reentrancy_modified.sol,0
12,12,D:\UoM\Final_Year_Project_New\vulnerability-de...,1,fee-on-transfer_modified.sol,0
13,13,D:\UoM\Final_Year_Project_New\vulnerability-de...,1,first-deposit_modified.sol,0
14,14,D:\UoM\Final_Year_Project_New\vulnerability-de...,1,Flashloan-flaw_modified.sol,0
15,15,D:\UoM\Final_Year_Project_New\vulnerability-de...,1,gas-price_modified.sol,0
16,16,D:\UoM\Final_Year_Project_New\vulnerability-de...,1,Hash-collisions_modified.sol,0
17,17,D:\UoM\Final_Year_Project_New\vulnerability-de...,1,Immunefi_ch1_modified.sol,0
18,18,D:\UoM\Final_Year_Project_New\vulnerability-de...,1,Immunefi_ch2_modified.sol,0
19,19,D:\UoM\Final_Year_Project_New\vulnerability-de...,1,Incorrect_sanity_checks_modified.sol,0
20,20,D:\UoM\Final_Year_Project_New\vulnerability-de...,-1,interface_modified.sol,1
21,21,D:\UoM\Final_Year_Project_New\vulnerability-de...,1,Invariant_modified.sol,0
22,22,D:\UoM\Final_Year_Project_New\vulnerability-de...,1,NFT-transfer_modified.sol,1
23,23,D:\UoM\Final_Year_Project_New\vulnerability-de...,-1,NFTMint_exposedMetadata_modified.sol,1
24,24,D:\UoM\Final_Year_Project_New\vulnerability-de...,-1,Oracle-stale_modified.sol,1
25,25,D:\UoM\Final_Year_Project_New\vulnerability-de...,1,Overflow_modified.sol,0
26,26,D:\UoM\Final_Year_Project_New\vulnerability-de...,1,Overflow2_modified.sol,0
27,27,D:\UoM\Final_Year_Project_New\vulnerability-de...,1,payable-transfer_modified.sol,1
28,28,D:\UoM\Final_Year_Project_New\vulnerability-de...,1,phantom-permit_modified.sol,0
29,29,D:\UoM\Final_Year_Project_New\vulnerability-de...,1,Precision-loss_modified.sol,0
30,30,D:\UoM\Final_Year_Project_New\vulnerability-de...,1,Price_manipulation_modified.sol,0
31,31,D:\UoM\Final_Year_Project_New\vulnerability-de...,1,Privatedata_modified.sol,0
32,32,D:\UoM\Final_Year_Project_New\vulnerability-de...,1,Randomness_modified.sol,0
33,33,D:\UoM\Final_Year_Project_New\vulnerability-de...,1,ReadOnlyReentrancy_modified.sol,0
34,34,D:\UoM\Final_Year_Project_New\vulnerability-de...,1,recoverERC20_modified.sol,0
35,35,D:\UoM\Final_Year_Project_New\vulnerability-de...,1,Reentrancy_modified.sol,0
36,36,D:\UoM\Final_Year_Project_New\vulnerability-de...,1,return-break_modified.sol,0
37,37,D:\UoM\Final_Year_Project_New\vulnerability-de...,-1,Returnfalse_modified.sol,1
38,38,D:\UoM\Final_Year_Project_New\vulnerability-de...,-1,Returnvalue_modified.sol,1
39,39,D:\UoM\Final_Year_Project_New\vulnerability-de...,1,self-transfer_modified.sol,0
40,40,D:\UoM\Final_Year_Project_New\vulnerability-de...,1,Selfdestruct_modified.sol,0
41,41,D:\UoM\Final_Year_Project_New\vulnerability-de...,1,Selfdestruct2_modified.sol,1
42,42,D:\UoM\Final_Year_Project_New\vulnerability-de...,-1,SenseFinance_exp_modified.sol,1
43,43,D:\UoM\Final_Year_Project_New\vulnerability-de...,1,SignatureReplay_modified.sol,0
44,44,D:\UoM\Final_Year_Project_New\vulnerability-de...,1,SignatureReplayNBA_modified.sol,0
45,45,D:\UoM\Final_Year_Project_New\vulnerability-de...,-1,Slippage-deadline_modified.sol,1
46,46,D:\UoM\Final_Year_Project_New\vulnerability-de...,1,Storage-collision-audio_modified.sol,0
47,47,D:\UoM\Final_Year_Project_New\vulnerability-de...,1,Storage-collision_modified.sol,0
48,48,D:\UoM\Final_Year_Project_New\vulnerability-de...,1,Struct-deletion_modified.sol,0
49,49,D:\UoM\Final_Year_Project_New\vulnerability-de...,1,txorigin_modified.sol,0
50,50,D:\UoM\Final_Year_Project_New\vulnerability-de...,1,Uninitialized_variables_modified.sol,0
51,51,D:\UoM\Final_Year_Project_New\vulnerability-de...,-1,UniswapV3ETHRefundExploit_modified.sol,1
52,52,D:\UoM\Final_Year_Project_New\vulnerability-de...,1,Unprotected-callback_modified.sol,0
53,53,D:\UoM\Final_Year_Project_New\vulnerability-de...,1,unsafe-downcast_modified.sol,0
54,54,D:\UoM\Final_Year_Project_New\vulnerability-de...,1,UnsafeCall_modified.sol,0
55,55,D:\UoM\Final_Year_Project_New\vulnerability-de...,1,Visibility_modified.sol,0

In [19]:
(df['done'] == 1).sum()

48

In [21]:
((df['done'] == 1) & (df['unclear'] == 0)).sum()

43

In [23]:
import re

def extract_vulnerable_lines(source_code):
    match = re.search(r'@vulnerable_at_lines:\s*([-?\d,\s]+)', source_code)
    if match:
        line_numbers = set(map(int, match.group(1).split(',')))
        return line_numbers
    return set()

def read_file(path):
    with open(path, 'r', encoding='utf-8') as file:
        return file.read()

def extract_and_update_vulnerable_lines_in_df(df):
    df['source_code'] = None
    df['vuln_lines'] = None
    for index, row in df.iterrows():
        file_path = f"{parent_folder}\\{row['file']}"
        content = read_file(file_path)
        if content is not None:
            line_numbers = extract_vulnerable_lines(content)
            if len(line_numbers) > 0:
                df.loc[index, "source_code"] = content
                df.loc[index, "vuln_lines"] = str(line_numbers)
                print(f"Success: {file_path} - {str(line_numbers)}")
            else:
                print(f"Something went wrong: empty line numbers set for {file_path}")
        else:
            print(f"Something went wrong: empty source code for {file_path}")

In [25]:
extract_and_update_vulnerable_lines_in_df(df)

Something went wrong: empty line numbers set for D:\UoM\Final_Year_Project_New\vulnerability-detection-and-localization\datasets\DefiVulnLabs\src\test\ApproveScam_modified.sol
Something went wrong: empty line numbers set for D:\UoM\Final_Year_Project_New\vulnerability-detection-and-localization\datasets\DefiVulnLabs\src\test\Array-deletion_modified.sol
Something went wrong: empty line numbers set for D:\UoM\Final_Year_Project_New\vulnerability-detection-and-localization\datasets\DefiVulnLabs\src\test\Backdoor-assembly_modified.sol
Something went wrong: empty line numbers set for D:\UoM\Final_Year_Project_New\vulnerability-detection-and-localization\datasets\DefiVulnLabs\src\test\Bypasscontract_modified.sol
Something went wrong: empty line numbers set for D:\UoM\Final_Year_Project_New\vulnerability-detection-and-localization\datasets\DefiVulnLabs\src\test\DataLocation_modified.sol
Something went wrong: empty line numbers set for D:\UoM\Final_Year_Project_New\vulnerability-detection-and-localization\datasets\DefiVulnLabs\src\test\Delegatecall_modified.sol
Something went wrong: empty line numbers set for D:\UoM\Final_Year_Project_New\vulnerability-detection-and-localization\datasets\DefiVulnLabs\src\test\Dirtybytes_modified.sol
Something went wrong: empty line numbers set for D:\UoM\Final_Year_Project_New\vulnerability-detection-and-localization\datasets\DefiVulnLabs\src\test\Divmultiply_modified.sol
Something went wrong: empty line numbers set for D:\UoM\Final_Year_Project_New\vulnerability-detection-and-localization\datasets\DefiVulnLabs\src\test\DOS_modified.sol
Something went wrong: empty line numbers set for D:\UoM\Final_Year_Project_New\vulnerability-detection-and-localization\datasets\DefiVulnLabs\src\test\ecrecover_modified.sol
Something went wrong: empty line numbers set for D:\UoM\Final_Year_Project_New\vulnerability-detection-and-localization\datasets\DefiVulnLabs\src\test\empty-loop_modified.sol
Something went wrong: empty line numbers set for D:\UoM\Final_Year_Project_New\vulnerability-detection-and-localization\datasets\DefiVulnLabs\src\test\ERC777-reentrancy_modified.sol
Something went wrong: empty line numbers set for D:\UoM\Final_Year_Project_New\vulnerability-detection-and-localization\datasets\DefiVulnLabs\src\test\fee-on-transfer_modified.sol
Something went wrong: empty line numbers set for D:\UoM\Final_Year_Project_New\vulnerability-detection-and-localization\datasets\DefiVulnLabs\src\test\first-deposit_modified.sol
Something went wrong: empty line numbers set for D:\UoM\Final_Year_Project_New\vulnerability-detection-and-localization\datasets\DefiVulnLabs\src\test\Flashloan-flaw_modified.sol
Something went wrong: empty line numbers set for D:\UoM\Final_Year_Project_New\vulnerability-detection-and-localization\datasets\DefiVulnLabs\src\test\gas-price_modified.sol
Something went wrong: empty line numbers set for D:\UoM\Final_Year_Project_New\vulnerability-detection-and-localization\datasets\DefiVulnLabs\src\test\Hash-collisions_modified.sol
Something went wrong: empty line numbers set for D:\UoM\Final_Year_Project_New\vulnerability-detection-and-localization\datasets\DefiVulnLabs\src\test\Immunefi_ch1_modified.sol
Something went wrong: empty line numbers set for D:\UoM\Final_Year_Project_New\vulnerability-detection-and-localization\datasets\DefiVulnLabs\src\test\Immunefi_ch2_modified.sol
Something went wrong: empty line numbers set for D:\UoM\Final_Year_Project_New\vulnerability-detection-and-localization\datasets\DefiVulnLabs\src\test\Incorrect_sanity_checks_modified.sol
Something went wrong: empty line numbers set for D:\UoM\Final_Year_Project_New\vulnerability-detection-and-localization\datasets\DefiVulnLabs\src\test\interface_modified.sol
Something went wrong: empty line numbers set for D:\UoM\Final_Year_Project_New\vulnerability-detection-and-localization\datasets\DefiVulnLabs\src\test\Invariant_modified.sol
Something went wrong: empty line numbers set for D:\UoM\Final_Year_Project_New\vulnerability-detection-and-localization\datasets\DefiVulnLabs\src\test\NFT-transfer_modified.sol
Something went wrong: empty line numbers set for D:\UoM\Final_Year_Project_New\vulnerability-detection-and-localization\datasets\DefiVulnLabs\src\test\NFTMint_exposedMetadata_modified.sol
Something went wrong: empty line numbers set for D:\UoM\Final_Year_Project_New\vulnerability-detection-and-localization\datasets\DefiVulnLabs\src\test\Oracle-stale_modified.sol
Something went wrong: empty line numbers set for D:\UoM\Final_Year_Project_New\vulnerability-detection-and-localization\datasets\DefiVulnLabs\src\test\Overflow_modified.sol
Something went wrong: empty line numbers set for D:\UoM\Final_Year_Project_New\vulnerability-detection-and-localization\datasets\DefiVulnLabs\src\test\Overflow2_modified.sol
Something went wrong: empty line numbers set for D:\UoM\Final_Year_Project_New\vulnerability-detection-and-localization\datasets\DefiVulnLabs\src\test\payable-transfer_modified.sol
Something went wrong: empty line numbers set for D:\UoM\Final_Year_Project_New\vulnerability-detection-and-localization\datasets\DefiVulnLabs\src\test\phantom-permit_modified.sol
Something went wrong: empty line numbers set for D:\UoM\Final_Year_Project_New\vulnerability-detection-and-localization\datasets\DefiVulnLabs\src\test\Precision-loss_modified.sol
Something went wrong: empty line numbers set for D:\UoM\Final_Year_Project_New\vulnerability-detection-and-localization\datasets\DefiVulnLabs\src\test\Price_manipulation_modified.sol
Something went wrong: empty line numbers set for D:\UoM\Final_Year_Project_New\vulnerability-detection-and-localization\datasets\DefiVulnLabs\src\test\Privatedata_modified.sol
Something went wrong: empty line numbers set for D:\UoM\Final_Year_Project_New\vulnerability-detection-and-localization\datasets\DefiVulnLabs\src\test\Randomness_modified.sol
Something went wrong: empty line numbers set for D:\UoM\Final_Year_Project_New\vulnerability-detection-and-localization\datasets\DefiVulnLabs\src\test\ReadOnlyReentrancy_modified.sol
Something went wrong: empty line numbers set for D:\UoM\Final_Year_Project_New\vulnerability-detection-and-localization\datasets\DefiVulnLabs\src\test\recoverERC20_modified.sol
Something went wrong: empty line numbers set for D:\UoM\Final_Year_Project_New\vulnerability-detection-and-localization\datasets\DefiVulnLabs\src\test\Reentrancy_modified.sol
Something went wrong: empty line numbers set for D:\UoM\Final_Year_Project_New\vulnerability-detection-and-localization\datasets\DefiVulnLabs\src\test\return-break_modified.sol
Something went wrong: empty line numbers set for D:\UoM\Final_Year_Project_New\vulnerability-detection-and-localization\datasets\DefiVulnLabs\src\test\Returnfalse_modified.sol
Something went wrong: empty line numbers set for D:\UoM\Final_Year_Project_New\vulnerability-detection-and-localization\datasets\DefiVulnLabs\src\test\Returnvalue_modified.sol
Something went wrong: empty line numbers set for D:\UoM\Final_Year_Project_New\vulnerability-detection-and-localization\datasets\DefiVulnLabs\src\test\self-transfer_modified.sol
Something went wrong: empty line numbers set for D:\UoM\Final_Year_Project_New\vulnerability-detection-and-localization\datasets\DefiVulnLabs\src\test\Selfdestruct_modified.sol
Something went wrong: empty line numbers set for D:\UoM\Final_Year_Project_New\vulnerability-detection-and-localization\datasets\DefiVulnLabs\src\test\Selfdestruct2_modified.sol
Something went wrong: empty line numbers set for D:\UoM\Final_Year_Project_New\vulnerability-detection-and-localization\datasets\DefiVulnLabs\src\test\SenseFinance_exp_modified.sol
Something went wrong: empty line numbers set for D:\UoM\Final_Year_Project_New\vulnerability-detection-and-localization\datasets\DefiVulnLabs\src\test\SignatureReplay_modified.sol
Something went wrong: empty line numbers set for D:\UoM\Final_Year_Project_New\vulnerability-detection-and-localization\datasets\DefiVulnLabs\src\test\SignatureReplayNBA_modified.sol
Something went wrong: empty line numbers set for D:\UoM\Final_Year_Project_New\vulnerability-detection-and-localization\datasets\DefiVulnLabs\src\test\Slippage-deadline_modified.sol
Something went wrong: empty line numbers set for D:\UoM\Final_Year_Project_New\vulnerability-detection-and-localization\datasets\DefiVulnLabs\src\test\Storage-collision-audio_modified.sol
Something went wrong: empty line numbers set for D:\UoM\Final_Year_Project_New\vulnerability-detection-and-localization\datasets\DefiVulnLabs\src\test\Storage-collision_modified.sol
Something went wrong: empty line numbers set for D:\UoM\Final_Year_Project_New\vulnerability-detection-and-localization\datasets\DefiVulnLabs\src\test\Struct-deletion_modified.sol
Something went wrong: empty line numbers set for D:\UoM\Final_Year_Project_New\vulnerability-detection-and-localization\datasets\DefiVulnLabs\src\test\txorigin_modified.sol
Something went wrong: empty line numbers set for D:\UoM\Final_Year_Project_New\vulnerability-detection-and-localization\datasets\DefiVulnLabs\src\test\Uninitialized_variables_modified.sol
Something went wrong: empty line numbers set for D:\UoM\Final_Year_Project_New\vulnerability-detection-and-localization\datasets\DefiVulnLabs\src\test\UniswapV3ETHRefundExploit_modified.sol
Something went wrong: empty line numbers set for D:\UoM\Final_Year_Project_New\vulnerability-detection-and-localization\datasets\DefiVulnLabs\src\test\Unprotected-callback_modified.sol
Something went wrong: empty line numbers set for D:\UoM\Final_Year_Project_New\vulnerability-detection-and-localization\datasets\DefiVulnLabs\src\test\unsafe-downcast_modified.sol
Something went wrong: empty line numbers set for D:\UoM\Final_Year_Project_New\vulnerability-detection-and-localization\datasets\DefiVulnLabs\src\test\UnsafeCall_modified.sol
Something went wrong: empty line numbers set for D:\UoM\Final_Year_Project_New\vulnerability-detection-and-localization\datasets\DefiVulnLabs\src\test\Visibility_modified.sol

In [57]:
df

,Unnamed: 0,filename,done,file,unclear,source_code,vuln_lines
0,0,D:\UoM\Final_Year_Project_New\vulnerability-de...,1,ApproveScam_modified.sol,1,// SPDX-License-Identifier: MIT\npragma solidi...,{72}
1,1,D:\UoM\Final_Year_Project_New\vulnerability-de...,1,Array-deletion_modified.sol,0,// SPDX-License-Identifier: MIT\npragma solidi...,{32}
2,2,D:\UoM\Final_Year_Project_New\vulnerability-de...,1,Backdoor-assembly_modified.sol,0,// SPDX-License-Identifier: MIT\npragma solidi...,"{44, 46, 47, 51, 53, 54}"
3,3,D:\UoM\Final_Year_Project_New\vulnerability-de...,1,Bypasscontract_modified.sol,0,// SPDX-License-Identifier: MIT\npragma solidi...,"{25, 26, 27, 34}"
4,4,D:\UoM\Final_Year_Project_New\vulnerability-de...,1,DataLocation_modified.sol,0,// SPDX-License-Identifier: MIT\npragma solidi...,"{36, 37}"
5,5,D:\UoM\Final_Year_Project_New\vulnerability-de...,1,Delegatecall_modified.sol,0,// SPDX-License-Identifier: MIT\npragma solidi...,{40}
6,6,D:\UoM\Final_Year_Project_New\vulnerability-de...,1,Dirtybytes_modified.sol,0,// SPDX-License-Identifier: MIT\npragma solidi...,{35}
7,7,D:\UoM\Final_Year_Project_New\vulnerability-de...,1,Divmultiply_modified.sol,0,// SPDX-License-Identifier: MIT\npragma solidi...,{37}
8,8,D:\UoM\Final_Year_Project_New\vulnerability-de...,1,DOS_modified.sol,0,// SPDX-License-Identifier: MIT\npragma solidi...,"{32, 33}"
9,9,D:\UoM\Final_Year_Project_New\vulnerability-de...,1,ecrecover_modified.sol,0,// SPDX-License-Identifier: MIT\npragma solidi...,"{40, 57}"
10,10,D:\UoM\Final_Year_Project_New\vulnerability-de...,1,empty-loop_modified.sol,1,// SPDX-License-Identifier: MIT\npragma solidi...,{41}
11,11,D:\UoM\Final_Year_Project_New\vulnerability-de...,1,ERC777-reentrancy_modified.sol,0,// SPDX-License-Identifier: MIT\npragma solidi...,"{80, 81}"
12,12,D:\UoM\Final_Year_Project_New\vulnerability-de...,1,fee-on-transfer_modified.sol,0,// SPDX-License-Identifier: MIT\npragma solidi...,"{270, 271}"
13,13,D:\UoM\Final_Year_Project_New\vulnerability-de...,1,first-deposit_modified.sol,0,// SPDX-License-Identifier: MIT\npragma solidi...,"{88, 67}"
14,14,D:\UoM\Final_Year_Project_New\vulnerability-de...,1,Flashloan-flaw_modified.sol,0,// SPDX-License-Identifier: MIT\npragma solidi...,"{64, 139}"
15,15,D:\UoM\Final_Year_Project_New\vulnerability-de...,1,gas-price_modified.sol,0,// SPDX-License-Identifier: MIT\npragma solidi...,{37}
16,16,D:\UoM\Final_Year_Project_New\vulnerability-de...,1,Hash-collisions_modified.sol,0,// SPDX-License-Identifier: MIT\npragma solidi...,"{56, 43}"
17,17,D:\UoM\Final_Year_Project_New\vulnerability-de...,1,Immunefi_ch1_modified.sol,0,// SPDX-License-Identifier: MIT\npragma solidi...,"{32, 33}"
18,18,D:\UoM\Final_Year_Project_New\vulnerability-de...,1,Immunefi_ch2_modified.sol,0,// SPDX-License-Identifier: MIT\npragma solidi...,{22}
19,19,D:\UoM\Final_Year_Project_New\vulnerability-de...,1,Incorrect_sanity_checks_modified.sol,0,// SPDX-License-Identifier: MIT\npragma solidi...,"{77, 78, 79}"
20,20,D:\UoM\Final_Year_Project_New\vulnerability-de...,-1,interface_modified.sol,1,// SPDX-License-Identifier: UNLICENSED\n\nprag...,{-1}
21,21,D:\UoM\Final_Year_Project_New\vulnerability-de...,1,Invariant_modified.sol,0,// SPDX-License-Identifier: MIT\npragma solidi...,{37}
22,22,D:\UoM\Final_Year_Project_New\vulnerability-de...,1,NFT-transfer_modified.sol,1,// SPDX-License-Identifier: MIT\npragma solidi...,"{42, 36}"
23,23,D:\UoM\Final_Year_Project_New\vulnerability-de...,-1,NFTMint_exposedMetadata_modified.sol,1,// SPDX-License-Identifier: UNLICENSED\npragma...,{-1}
24,24,D:\UoM\Final_Year_Project_New\vulnerability-de...,-1,Oracle-stale_modified.sol,1,// SPDX-License-Identifier: MIT\npragma solidi...,{-1}
25,25,D:\UoM\Final_Year_Project_New\vulnerability-de...,1,Overflow_modified.sol,0,// SPDX-License-Identifier: MIT\npragma solidi...,{51}
26,26,D:\UoM\Final_Year_Project_New\vulnerability-de...,1,Overflow2_modified.sol,0,// SPDX-License-Identifier: MIT\npragma solidi...,{66}
27,27,D:\UoM\Final_Year_Project_New\vulnerability-de...,1,payable-transfer_modified.sol,1,// SPDX-License-Identifier: MIT\npragma solidi...,{50}
28,28,D:\UoM\Final_Year_Project_New\vulnerability-de...,1,phantom-permit_modified.sol,0,// SPDX-License-Identifier: MIT\npragma solidi...,"{50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60}"
29,29,D:\UoM\Final_Year_Project_New\vulnerability-de...,1,Precision-loss_modified.sol,0,// SPDX-License-Identifier: MIT\npragma solidi...,{52}
30,30,D:\UoM\Final_Year_Project_New\vulnerability-de...,1,Price_manipulation_modified.sol,0,// SPDX-License-Identifier: MIT\npragma solidi...,{68}
31,31,D:\UoM\Final_Year_Project_New\vulnerability-de...,1,Privatedata_modified.sol,0,// SPDX-License-Identifier: MIT\npragma solidi...,"{25, 28}"
32,32,D:\UoM\Final_Year_Project_New\vulnerability-de...,1,Randomness_modified.sol,0,// SPDX-License-Identifier: MIT\npragma solidi...,"{41, 42, 43, 44, 45}"
33,33,D:\UoM\Final_Year_Project_New\vulnerability-de...,1,ReadOnlyReentrancy_modified.sol,0,// SPDX-License-Identifier: MIT\npragma solidi...,"{85, 86}"
34,34,D:\UoM\Final_Year_Project_New\vulnerability-de...,1,recoverERC20_modified.sol,0,// SPDX-License-Identifier: MIT\npragma solidi...,"{49, 53}"
35,35,D:\UoM\Final_Year_Project_New\vulnerability-de...,1,Reentrancy_modified.sol,0,// SPDX-License-Identifier: MIT\npragma solidi...,"{41, 45, 46, 47}"
36,36,D:\UoM\Final_Year_Project_New\vulnerability-de...,1,return-break_modified.sol,0,// SPDX-License-Identifier: MIT\npragma solidi...,{51}
37,37,D:\UoM\Final_Year_Project_New\vulnerability-de...,-1,Returnfalse_modified.sol,1,// SPDX-License-Identifier: MIT\npragma solidi...,{-1}
38,38,D:\UoM\Final_Year_Project_New\vulnerability-de...,-1,Returnvalue_modified.sol,1,// SPDX-License-Identifier: MIT\npragma solidi...,{-1}
39,39,D:\UoM\Final_Year_Project_New\vulnerability-de...,1,self-transfer_modified.sol,0,// SPDX-License-Identifier: MIT\npragma solidi...,"{40, 41, 42, 39}"
40,40,D:\UoM\Final_Year_Project_New\vulnerability-de...,1,Selfdestruct_modified.sol,0,// SPDX-License-Identifier: MIT\npragma solidi...,{41}
41,41,D:\UoM\Final_Year_Project_New\vulnerability-de...,1,Selfdestruct2_modified.sol,1,// SPDX-License-Identifier: MIT\npragma solidi...,{13}
42,42,D:\UoM\Final_Year_Project_New\vulnerability-de...,-1,SenseFinance_exp_modified.sol,1,// SPDX-License-Identifier: UNLICENSED\npragma...,{-1}
43,43,D:\UoM\Final_Year_Project_New\vulnerability-de...,1,SignatureReplay_modified.sol,0,// SPDX-License-Identifier: MIT\npragma solidi...,{118}
44,44,D:\UoM\Final_Year_Project_New\vulnerability-de...,1,SignatureReplayNBA_modified.sol,0,// SPDX-License-Identifier: MIT\npragma solidi...,"{96, 59, 63}"
45,45,D:\UoM\Final_Year_Project_New\vulnerability-de...,-1,Slippage-deadline_modified.sol,1,// SPDX-License-Identifier: MIT\npragma solidi...,{-1}
46,46,D:\UoM\Final_Year_Project_New\vulnerability-de...,1,Storage-collision-audio_modified.sol,0,// SPDX-License-Identifier: MIT\npragma solidi...,"{28, 44}"
47,47,D:\UoM\Final_Year_Project_New\vulnerability-de...,1,Storage-collision_modified.sol,0,// SPDX-License-Identifier: MIT\npragma solidi...,"{41, 26}"
48,48,D:\UoM\Final_Year_Project_New\vulnerability-de...,1,Struct-deletion_modified.sol,0,// SPDX-License-Identifier: MIT\npragma solidi...,{56}
49,49,D:\UoM\Final_Year_Project_New\vulnerability-de...,1,txorigin_modified.sol,0,// SPDX-License-Identifier: MIT\npragma solidi...,{42}
50,50,D:\UoM\Final_Year_Project_New\vulnerability-de...,1,Uninitialized_variables_modified.sol,0,// SPDX-License-Identifier: MIT\npragma solidi...,"{96, 98, 38, 39, 40, 89}"
51,51,D:\UoM\Final_Year_Project_New\vulnerability-de...,-1,UniswapV3ETHRefundExploit_modified.sol,1,// SPDX-License-Identifier: UNLICENSED\npragma...,{-1}
52,52,D:\UoM\Final_Year_Project_New\vulnerability-de...,1,Unprotected-callback_modified.sol,0,// SPDX-License-Identifier: MIT\npragma solidi...,{44}
53,53,D:\UoM\Final_Year_Project_New\vulnerability-de...,1,unsafe-downcast_modified.sol,0,// SPDX-License-Identifier: MIT\npragma solidi...,{34}
54,54,D:\UoM\Final_Year_Project_New\vulnerability-de...,1,UnsafeCall_modified.sol,0,// SPDX-License-Identifier: MIT\npragma solidi...,{96}
55,55,D:\UoM\Final_Year_Project_New\vulnerability-de...,1,Visibility_modified.sol,0,// SPDX-License-Identifier: MIT\npragma solidi...,"{36, 37, 38}"

In [59]:
df.to_csv("processed/defi_vuln_labs_dataset_with_vuln_line_numbers.csv")